### ISSUE TITLE
Ability to resend an invoice

### ISSUE THREAD

**Issue by adampatterson** [bytefury/crater#100]
**Is your feature request related to a problem? Please describe.**
After updating an invoice or changing the customers contact details, I would like to resend it to the client.

**Describe the solution you'd like**
- Once an update has been made to the invoice, an option to resend should show.
- From the invoice lists page, an action should be available to resend the invoice.

**Describe alternatives you've considered**
Resending the email is the main problem but in some cases, a notification sent to the customer about an invoice adjustment.

**Comment by miraro3** [comment]
+1 , I've had customers in the past who requested a re-send of an 'old' invoice

**Comment by adampatterson** [comment]
I just had this request again.

Even at a minimum being able to get the PDF URL would be helpful.

**Comment by mohitpanjwani** [comment]
Hey, thanks for the heads up. 

We'll include this feature in the next build which we're going to upload next week.

**Comment by adampatterson** [comment]
Awesome thanks!

**Comment by whitetornado** [comment]
any news about this? I have now a few time that the customer did not get the mail. A resend option will be great..

**Comment by mohitpanjwani** [comment]
Hey @whitetornado, I think I forgot to close this one but its already added in the latest release. 

You should see this option in the dropdown if your invoice is already sent.

**Comment by whitetornado** [comment]
hmm, when i go the the invoice what is sent, and then? i can Close - Record Payment - Delete or cancel

**Comment by adampatterson** [comment]
@whitetornado If you would like to resend the invoice. you can go under Invoices, go to the far right and click the three dots then click "Resend Invoice"

![image](https://user-images.githubusercontent.com/31537/84792299-ed62c700-afb0-11ea-98c7-0ab5505c3fb6.png)

If you view the invoice, you can click "Copy PDF URL" to use it in your own email.
