### ISSUE TITLE
€ position in PDFs

### ISSUE THREAD

**Issue by bumTomica** [bytefury/crater#102]
**Describe the bug**
- euro (€) symbol should be after the price
- for some reason, the layout of the items is rendering unexpected

**Screenshots**
https://imgur.com/a/iAMQkuR

**Please complete the following information:**
- Crater version: latest
- PHP version: 7.3

**Comment by ufeg02** [comment]
This is not a bug, maybe a feature? In Belgium the € symbol should be added before the price.

**Comment by nhedger** [comment]
Actually, a list of conventions can be found here : https://en.wikipedia.org/wiki/Language_and_the_euro#Written_conventions_for_the_euro_in_the_languages_of_EU_member_states. It appears the majority of countries place the sign after the amount and English-speaking countries it is placed before the amount.

**Comment by bumTomica** [comment]
Maybe an option to pick the placement of the symbol? Front or back, with space or not.

**Comment by mohitpanjwani** [comment]
We have fixed all the issues with PDF layout and sizing for columns. We will include the changes in next update.

Now for the placement of the the currency symbol, we can work on a feature to edit the currency item so it allows the user to edit the symbol, thousand symbol, and placement of the icon dynamically.
