### ISSUE TITLE
How can I run the projet in development ?

### ISSUE THREAD

**Issue by PHClement** [bytefury/crater#107]
Hello,

Can we have a tutorial to run the projet localy for development ?

Thank you ;)

**Comment by hypnodev** [comment]
You can read the Developer Guide in the docs: `https://docs.craterapp.com/developer-guide.html#installation`

**Comment by PHClement** [comment]
How can I work to the project in hot reloading mod with webpack ?

**Comment by mohitpanjwani** [comment]
After you've followed the developer guide, you can run `npm run hot` to start hot reloading with webpack. 

For more information, check how laravel-mix works. In order to develop or make changes to crater, you need basic understanding of Laravel & VueJS.
