### ISSUE TITLE
Missing steps from installation instructions

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#11]
A few things are missing from the [Developer Guide / Installation](https://docs.craterapp.com/developer-guide.html#installation) instructions.

In order to run the app you also need to
- create the .env file (i.e. `cp .env.example .env`)
- generate the app key (i.e. `art key:generate`)

**Comment by mohitpanjwani** [comment]
Yeah!! Thanks for the reminder..the developer guide isn't good right now.

I'll add the required steps asap :) 

Also if anybody wants to contribute, they can do so by adding a PR to the below repo: 
https://github.com/bytefury/crater-docs

**Comment by j4nr6n** [comment]
Maybe don't close the issue until it's fixed? It would have helped in finding the information provided by @pszucs in the initial comment.
