### ISSUE TITLE
PDF no logo and show unknown 

### ISSUE THREAD

**Issue by lamtszhin0528** [bytefury/crater#111]
it show, Image not found or type unknown, when we generate PDF
tried replace company logo but same 

- Crater version: 2.1.0
- PHP version:  7.3.7
- Database type and version:  5.5.57-MariaDB
Running on QNAP Web server

![image](https://user-images.githubusercontent.com/58826592/71562076-6cbf1580-2ab9-11ea-9a0d-c3bce579bbab.png)
![image](https://user-images.githubusercontent.com/58826592/71562088-8b251100-2ab9-11ea-9a28-5a07df051a8b.png)

**Comment by mohitpanjwani** [comment]
@lamtszhin0528 Make sure that your APP_URL is correct in the `.env` file. 

if it still happens, its an issue with media-library..  

You can also try running `php artisan storage:link` command on your root folder.

**Comment by lamtszhin0528** [comment]
How can we check the media library ?

we run it on QNAP NAS we can't run [php artisan] command 

<img width="643" alt="螢幕截圖 2020-02-03 下午8 41 27" src="https://user-images.githubusercontent.com/58826592/73654057-a9d48400-46c5-11ea-9806-86d2480f1368.png">

**Comment by LeonBuchner** [comment]
Same error here

**Comment by alignwebs** [comment]
I am also facing the same issue. Any Fix ?

**Comment by HamzaDevz** [comment]
+1 Same here ...

**Comment by HamzaDevz** [comment]
Okay I figured out, instead of using `getFullPath()` in FrontEndController I used `getPath()`.
I'm using docker and I know that if you try to put the same origin it's breaking. so getPath provide the file directly from your server. (/var/www....)

**Comment by spoutnikfr** [comment]
Same problem here on 3.0
`php artisan storage:link

   ErrorException  : symlink(): No such file or directory

  at .../vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:263
    259|      */
    260|     public function link($target, $link)
    261|     {
    262|         if (! windows_os()) {
  > 263|             return symlink($target, $link);
    264|         }
    265| 
    266|         $mode = $this->isDirectory($target) ? 'J' : 'H';
    267| 

  Exception trace:

  1   symlink(".../storage/app/public", ".../public/storage")
      .../vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:263

  2   Illuminate\Filesystem\Filesystem::link(".../storage/app/public", ".../public/storage")
      .../vendor/laravel/framework/src/Illuminate/Foundation/Console/StorageLinkCommand.php:35`

**Comment by spoutnikfr** [comment]
I found a solution :
**PLEASE NOTE THIS WORK ONLY FOR SHARED HOSTING LIKE OVH**
public/.htaccess add     
> Options +FollowSymlinks

login in .ssh and use
> cd public
> unlink storage
> ln -s ../storage/app/public/ storage

**Comment by kc9ryt** [comment]
Still not working for me. I did a manual install.

**Comment by tjimenez** [comment]
It happens when the image is uploading through the UI. If you browse and replace the image manually with the original one works again.

**Comment by mohitpanjwani** [comment]
This should no longer be an issue on the latest update.

**Comment by miah5674** [comment]
> 

Thank you so much
This command works for me
