### ISSUE TITLE
Billing/Shipping Address is not being save

### ISSUE THREAD

**Issue by guiscaranse** [bytefury/crater#114]
**Describe the bug**
After filling a customer billing address it doesn't save, so every time I open a customer I have to retype the billing address manually. Also, billing to information is not being displayed at generated PDF (not sure if it's related, might create another ticket for that)

**Expected behavior**
User should be able to edit customer billing address without the need to retype it.
User should see the "Billing to" information on the generated PDF

**Please complete the following information:**
- Crater version: 2.1
- PHP version: 7.3.13
- Database type and version: Postgres 12.1

**Optional info**
- OS: Ubuntu
- Browser: Chrome

**Comment by hypnodev** [comment]
I've made a pull request for this bug fix, atm you can use MySQL or update `BILLING_TYPE` and `SHIPPING_TYPE` to lowercase

**Comment by hypnodev** [comment]
#108

**Comment by guiscaranse** [comment]
@hypnodev That really fixed both issues, thanks.
