### ISSUE TITLE
Passport API - 400

### ISSUE THREAD

**Issue by francoismart** [bytefury/crater#116]
Hello
Once installed locally correctly, it works except I can't "logout" and "login" again. 

I have a 400 error from /api/auth/login route : 
{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided","message":"The authorization grant type is not supported by the authorization server."}

I tried to reinstall passport and regenerate keys but no luck

Any idea where to change setup please ?

**Comment by mateo2181** [comment]
Run php artisan --force passport:install and paste these credentials in your .env file.
Go to oauth_clients table and check if password_client is set to 1 and personal_access_client is set to 0 and revoked to 0.

I did that and works!

**Comment by accidentul** [comment]
can you please add a example of the keys in the env file ?

**Comment by mohitpanjwani** [comment]
You should no longer have this issue on V4. 

If you still do, please feel free to reopen this issue.
