### ISSUE TITLE
Seed VS intl

### ISSUE THREAD

**Issue by bennukem** [bytefury/crater#117]
Hello,

Why you do not use php intl ? To use your own seeds is a lot of work for nothing, no ?

**Comment by mohitpanjwani** [comment]
@bennukem Sorry I don't get what you're trying to say. can you elaborate?

**Comment by bennukem** [comment]
Sorry for my poor english...

For example this file https://github.com/bytefury/crater/blob/master/database/seeds/CurrenciesTableSeeder.php
Data are already available in php with https://www.php.net/manual/class.numberformatter.php .So why to use theses fixtures (seed) ?

Or I really missed something ?

**Comment by mohitpanjwani** [comment]
I'd be happy to review a PR if you can remove the seeded currencies with in-built PHP classes.

I don't see a way to list down all the currencies without a seeder on the given link.
