### ISSUE TITLE
Insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by bumTomica** [bytefury/crater#118]
GET for Expense Categories is loaded over HTTP.

"Mixed Content: The page at 'https://.../admin/expenses' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://.../api/categories'. This request has been blocked; the content must be served over HTTPS."

**Comment by mohitpanjwani** [comment]
Issue fixed by @hypnodev.

Please let me know if this still occurs.

Thanks
