### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#12]
The output of `npm install` reveals some security vulnerabilities in the packages used:

```
npm WARN The package cross-env is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2002 packages from 1582 contributors and audited 33828 packages in 29.829s
found 24 vulnerabilities (1 low, 1 moderate, **22 high**)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by mohitpanjwani** [comment]
We are looking into this.

**Comment by irvine48** [comment]
Found this solution for vagrant user.

`npm install --no-bin-links`

Output as below:
> vagrant@homestead:~/Code/crater$ npm install --no-bin-links
> npm WARN rollback Rolling back fsevents@1.2.9 failed (this is probably harmless): ETXTBSY: text file is busy, rmdir '/home/vagrant/Code/crater/node_modules/fsevents/node_modules'
> npm WARN The package cross-env is included as both a dev and production dependency.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2002 packages from 1582 contributors and audited 33828 packages in 90.766s
found 38 vulnerabilities (13 low, 3 moderate, 22 high)

at least no ERR! xxxxx

tested on 2.1.0.

**Comment by mohitpanjwani** [comment]
I don't see this issue anymore on V4.
