### ISSUE TITLE
403 error when trying to use Laravel Telescope

### ISSUE THREAD

**Issue by FrankyJust** [bytefury/crater#122]
For development purposes I want to use Laravel Telescope with Crater app. I've installed Telescope and when I'm trying to use it (url:localhost/telescope), I'm keeping 403 error Forbidden. I've checked several things but I' didn't find a solution. Everything seems to be correctly being set. Any suggestions?

**Comment by mohitpanjwani** [comment]
Sorry, this is unrelated to Crater so I'm closing this.
