### ISSUE TITLE
Multiple users management / user info theft

### ISSUE THREAD

**Issue by Sicaa** [bytefury/crater#123]
New user here. I've just ran into the installation process (with docker & docker-compose), and wanted to add a new user as a team member within the freshly created company.

Seems that it's not a supported/documented feature as of today (correct me if I'm wrong), but I thought "that's not a problem, I'll just have to manually insert an user in DB".

So I just ran a traditional-old-school INSERT INTO users SQL query into the crater database into MariaDB container, with the same data as the first and unique existing admin user, excepted for the name and email address. I kept the same password as the first user as I don't know how to correctly hash it, so I wanted to change it afterwards.

Next I logout from my session and tested the new created user with its own email address (but same password as the first one), and I successfully logged in. Here is the problem: in the "Settings" tab, the loaded name and email are the ones of the first user! Note that if I update settings (name or email address), it correctly update the user 2. Are the session info mixed up if two users have the same password?

So either it's a **big** security issue, or I'm missing something?

- Crater version: 2.1.0
- PHP version: 7.3
- Database type and version: 10.4.11-MariaDB-1:10.4.11+maria~bionic

Step to reproduce:
1. Fresh install & onboarding process with a first user ;
2. In the MariaDB container, run: `mysql -u root -p`, `USE crater;`,  `SELECT * FROM users` to see the newly created user and copy password ;
3. `INSERT INTO users VALUES(null, 'Bobby', 'bobby@domain.com', NULL, 'THE COPIED PASSWORD FROM USER 1', 'admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, '2020-01-04 12:35:56', '2020-01-04 12:42:25');` ;
4. Log in with bobby@domain.com email address and password ;
5. Go to the "Settings" tab ;
6. Info from the user 1: WTF?!

**Comment by mohitpanjwani** [comment]
As of now, we haven't tested authentication with multiple users. We only support one admin user on Crater version: 2.1.0. 

We have started adding multiple users with permissions but that will be on next major update: 3.0 and it will take some time as currently, we are focusing on `2.2.0`. 

If you find a security issue or have any other suggestions then please feel free to let us know here or submit a PR.
