### ISSUE TITLE
Docker Installation fails to connect to maria sql

### ISSUE THREAD

**Issue by Chalkin** [bytefury/crater#125]
**Describe the bug**
When I install crater with docker as described i can not finish the installation wizard due to the Error "SQLSTATE[HY000] [2002] Connection refused"

**Expected behavior**
SQL connection can be established with the provided credentials (crater, crater, crater) which can be found in docker.compose.yaml or in the installation documentation.

**Please complete the following information:**
- Crater version: Git Master Branch (05.12.2020)
- PHP version: 7.2 (Docker Version)
- Database type and version: Docker Version

**Optional info**
- OS:  Ubuntu 18.04
- Browser: Chrome

**Comment by Chalkin** [comment]
Any Ideas?

**Comment by ArjunKishore** [comment]
the same issue for me as well

**Comment by ggiak** [comment]
@ArjunKishore make sure that the given password is correct at your .env file
in case the password has symbols, make sure you use it with a quote.

example:
`DB_PASSWORD="my$23!@#Str0ngP@ss\w0r¤"`

**Comment by mohitpanjwani** [comment]
@Chalkin Above solutions mentioned by @ArjunKishore and @ggiak should fix the issue. 

If not, please reopen/create a new issue.

Thanks

**Comment by Chalkin** [comment]
Now it worked with using another db host. I checked Kitematic and it gave me 5cd97162c7a9 as DB Host. That worked
