### ISSUE TITLE
Installation - Company information

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#13]
When selecting "United Kingdom" from the Country dropdown the cities / towns appear in the "State" dropdown instead of the one labelled "City".

The "City" dropdown only shows one item called "Angus".

[Correction]

I said the cities appear in the State dropdown, that was incorrect. Some cities (such as Birmingham, Bristol) appear in this list but I believe they are not states like Buckinghamshire or Essex.

**Comment by mohitpanjwani** [comment]
@pszucs Hey! thanks for letting us know. can you help us list down the states and cities for the UK?  

We took the list of states, countries & city list from another open-source project.. so we'll need to fix this manually :)

**Comment by pszucs** [comment]
A quick search provided these two, potentially useful links:

https://en.wikipedia.org/wiki/List_of_counties_of_the_United_Kingdom

https://www.townscountiespostcodes.co.uk/towns-in-uk/

> Our database currently has a total of 69 Cities in UK (United Kingdom).
> Our database currently has a total of 43,588 Towns/Villages in UK (United Kingdom).

**Comment by mohitpanjwani** [comment]
Yes, I asked for the list because I was confused as I couldn't find the states.. As a user how would you feel if we treated Counties as States and Cities as towns? 

Otherwise, we'll need to make a lot of country-specific changes.. We need to think more on this..

**Comment by mohitpanjwani** [comment]
Also 43,588 towns! that's a lot of data that we would need to Seed in order to show a select box ( and that obviously increase the time it would take for installation) 

Need to check how other popular systems handle address fields for UK.

**Comment by pszucs** [comment]
> Also 43,588 towns!

Yes, that's a lot. :) I agree, it may not be a good idea to seed them during installation.

I think your association (treated Counties as States and Cities as towns) is fairly common in software that are not specifically tailored to UK customers - I'd be happy with that.

With regards to handling address fields in the UK, I think the most common and probably most user-friendly approach is to use some sort of an address lookup service so that users only need to enter their house number (if applicable) and their postcode and select the appropriate address. These services, however, usually are not free services.

For now, I think the City could be just an input element instead of a select - or keep the select but allow users to enter the city / town name manually.

**Comment by mohitpanjwani** [comment]
> > Also 43,588 towns!
> 
> Yes, that's a lot. :) I agree, it may not be a good idea to seed them during installation.
> 
> I think your association (treated Counties as States and Cities as towns) is fairly common in software that are not specifically tailored to UK customers - I'd be happy with that.
> 
> With regards to handling address fields in the UK, I think the most common and probably most user-friendly approach is to use some sort of an address lookup service so that users only need to enter their house number (if applicable) and their postcode and select the appropriate address. These services, however, usually are not free services.
> 
> For now, I think the City could be just an input element instead of a select - or keep the select but allow users to enter the city / town name manually.

Totally agreed with what you said! 

We've already implemented the process you mentioned, so on the next update, we'll delete the existing 5-10 cities that are on the system for UK in the current version and we've updated the address forms to show an text input field (instead of a select input) when no cities are found so the users can add the city/town manually.

**Comment by j4nr6n** [comment]
When you select "US" as the country, and any state, it only shows the cities in Alaska and only a few of the larger ones.

Check out [this SO answer](https://stackoverflow.com/a/27995469) for information on storing addresses and maybe consider not seeding the database. Convert everything to text fields and let users type their addresses. From experience, maintaining these kinds of lists is a nightmare.

**Comment by mohitpanjwani** [comment]
> When you select "US" as the country, and any state, it only shows the cities in Alaska and only a few of the larger ones.
> 
> Check out [this SO answer](https://stackoverflow.com/a/27995469) for information on storing addresses and maybe consider not seeding the database. Convert everything to text fields and let users type their addresses. From experience, maintaining these kinds of lists is a nightmare.

Agreed! It's going to be a huge pain to maintain the list of States & Cities for each country, so we've decided to get rid of them as you said. 

Also, installation is pretty quick as it just needs to run the migrations but many of users are reporting that they get `Executation timeout failed` error because it takes a lot of time to seed States and Cities. 

Other seeds are pretty minimal so this will also improve the installation speed 👍
