### ISSUE TITLE
Plan to integrate with Element UI

### ISSUE THREAD

**Issue by nighon** [bytefury/crater#134]
**Is your feature request related to a problem? Please describe.**
[Element UI](https://github.com/ElemeFE/element) is very popular, We want to use it in crater web app.

**Describe the solution you'd like**
Custom theme

**Describe alternatives you've considered**
Is there any plan to integrate Element UI into crater in the future?

**Comment by mohitpanjwani** [comment]
No sorry! No plans to integrate any UI kits/frameworks.

We prefer building custom components or using individual open source components.
