### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by rohit-agsft-web** [bytefury/crater#140]
**getting a below error, I cloned project and setup on the ubuntu 18.04 OS**

production.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from `settings` where `option` = profile_complete limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from `settings` where `option` = profile_complete limit 1) at /var/www/html/laravel-projects/invoice-crater-app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665)
[stacktrace]

Please see, attached screenshot 
![Crater - Self Hosted Invoicing Platform](https://user-images.githubusercontent.com/59162959/72701894-dc836600-3b76-11ea-9678-8751494c34f1.png)

**Comment by ggiak** [comment]
@rohit-agsft-web can you please show us the second step of installation regarding folder permission?

**Comment by rohit-agsft-web** [comment]
it's fixed

**Comment by joaomnb** [comment]
I bumped into the same error. @rohit-agsft-web mind sharing how you fixed it? Thanks!

**Comment by jefferdo** [comment]
There is file called "database_created" in "storage/app/". Remove the file and refresh.

**Comment by quangbahoa** [comment]
> There is file called "database_created" in "storage/app/". Remove the file and refresh.

I think this should be put to the docs. I got same errors when try to install via git.
