### ISSUE TITLE
How Can i add new module as like - Timesheet, Users OR Reminders

### ISSUE THREAD

**Issue by rohits-web** [bytefury/crater#141]
How can we add the new module into the existing project, we created models, controller but how can we load from Vue js those modules. Please assist.

**Comment by mohitpanjwani** [comment]
Sorry, If you need to customize Crater for your own needs then you will need to explore the code yourself and spend some time into learning how all of these things fit together

If you have a query related to the current implementation or a feature request then you can create another issue. 

Thanks
