### ISSUE TITLE
When token is not valid you don't get logged out

### ISSUE THREAD

**Issue by MakerLab-Dev** [bytefury/crater#146]
**Describe the bug**
If your token is not longer valid (you get a 401 error in console), instead of logging you out it shows a loading spinner and you have to remove cookies in order to be able to log in again.

**Expected behavior**
If the token is not longer valid, when the server responds with a 401 it should handle that response code and log you out

**Screenshots**
![image](https://user-images.githubusercontent.com/47223013/73138748-a35f6000-4066-11ea-8e3b-db6705c3cbf4.png)

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: demo.craterapp.com
- Database type and version: demo.craterapp.com

**Optional info**
- Browser: Chrome

**Comment by MakerLab-Dev** [comment]
While I was testing crater locally to fix this issue I found that it works as expected, I don't know why the demo of crater (https://demo.craterapp.com/) has this bug

**Comment by mohitpanjwani** [comment]
@MakerLab-Dev Thanks for reporting but actually the issue on demo occurred because I reset the database and the passport keys while installing the new version. 

If this happens on the actual app, then please let me know :)
