### ISSUE TITLE
Crater ignores MAIL_FROM_ADDRESS when sending email

### ISSUE THREAD

**Issue by proea** [bytefury/crater#148]
**Describe the bug**
Crater ignores MAIL_FROM_ADDRESS when sending email and sends with email used by an authorized administrator.

An authorized admin can use non-accounting email. It can lead to issues for outgoing emails. 
_Example from my setup_: 
email server blocks outgoing emails what sent from email what its not in allowed list 
_Config example_: 
```
smtp account: send@domain.tld, 
from address: invoice@domain.tld, 
authorized admin email: manager@domain.tld
send@domain.tld is allowed to send emails from invoice@domain.tld but not from manager@domain.tld
```

_Mailserver log:_
```
postfix/submission/smtpd[378]: NOQUEUE: reject: RCPT from XXXXXXXX: 553 5.7.1 <manager@domain.tld>: Sender address rejected: not owned by user send@domain.tld; from=<manager@domain.tld> to=<xxxxxxx@xxxxxxx.xxx> proto=ESMTP helo=<xxxxxxxx>
```

_Laravel log_:
```
[2020-01-26 xx:xx:xx] production.ERROR: Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
" {"userId":1,"exception":"[object] (Swift_TransportException(code: 554): Expected response code 354 but got code \"554\", with message \"554 5.5.1 Error: no valid recipients
\" at /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]
#0 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('554 5.5.1 Error...', Array)
\1 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\
', Array, Array, false, NULL)
```

**Expected behavior**
MAIL_FROM_ADDRESS should be used for outgoing emails OR, alternatively (better for supporting multiple companies in future), from a new field like accounting email in "Company info" settings tab).

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: 7.3-FPM

**Optional info**
- docker (latest version)

**Comment by mohitpanjwani** [comment]
Issue fixed in https://github.com/bytefury/crater/releases/tag/3.0.0
