### ISSUE TITLE
Ability to customize the invoice number

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#15]
I already have a few invoices and creating new ones with Crater would cause issues if I didn't know how to change it in the database. ;)

I believe (although I'm not an accountant) that here in the UK there's only one rule for invoice numbers which is that it has to be unique, but companies or people from other countries might have specific needs regarding the format of the invoice number.

For example, the way I do the invoicing is this: unique prefix for the client + auto increment number, so:

CLIENT1-202
CLIENT1-203
...

and then for another client:
CLIENT-2-200
CLIENT-2-201
...

I think at least the ability to overwrite the invoice number is needed. A more robust solution could be to have a prefix on the customer record and use that prefix to generate the invoice number.

**Comment by mohitpanjwani** [comment]
I agree with you on this! I'm thinking that we can enable editing an invoice-number directly. ( It should always be unique though, we'll validate that )

Also, we'll add a setting that allows the users to change the prefix, and perhaps a setting to disable automatic incrementing?

**Comment by mohitpanjwani** [comment]
I'm not too sure about the client-specific prefix though. We might look into that if we get more requests for that as I personally never felt the need to do that.

**Comment by pszucs** [comment]
> Also, we'll add a setting that allows the users to change the prefix, and perhaps a setting to disable automatic incrementing?

That's also a good idea.

**Comment by mohitpanjwani** [comment]
We'll be adding the ability to edit Invoice-Numbers in the next update. 

Also, we'll add options to disable Auto Generation of Numbers for Invoices, Estimates, Payments and Expenses.
