### ISSUE TITLE
/api/dashboard/expense/chart returns html code (404 page) instead of json

### ISSUE THREAD

**Issue by proea** [bytefury/crater#150]
**Describe the bug**
The chart does not contain information, although there are expenses and registered payments.
/api/dashboard/expense/chart returns html code (404 page) instead of json. 

**Expected behavior**
/api/dashboard/expense/chart endpoint with json data for chart. Chart with Sales and Expenses

**Screenshots**
![image](https://user-images.githubusercontent.com/2929968/73142002-f81cce00-409a-11ea-9e3e-ef8a673963cc.png)
![image](https://user-images.githubusercontent.com/2929968/73142006-010d9f80-409b-11ea-86d7-269afe728b05.png)

**Please complete the following information:**
- Crater version: 2.1
- PHP version: 7.3 fpm
- Database type and version: mysql

**Optional info**
- OS:  centos 7
- Docker
- Browser: chrome, safari

**Comment by mohitpanjwani** [comment]
Issue fixed in https://github.com/bytefury/crater/releases/tag/3.0.0
