### ISSUE TITLE
It's not possible to use new lines in address field in Company info settings

### ISSUE THREAD

**Issue by proea** [bytefury/crater#151]
**Describe the bug**
It's not possible to use new lines in address field in Company info settings. And there is no way to display new line in PDF using address field. All lines are merged into one line in PDF. 

**Expected behavior**
All new lines in address field should be displayed in PDS as a new line.

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: 7.3 fpm
- Database type and version: mysql

**Comment by mohitpanjwani** [comment]
Issue fixed in https://github.com/bytefury/crater/releases/tag/3.0.0
