### ISSUE TITLE
The repository code is broken: InvoicesController.php

### ISSUE THREAD

**Issue by proea** [bytefury/crater#155]
**Describe the bug**
The repository code is broken
https://github.com/bytefury/crater/blob/186004f7f8b25af4a26d0f39bba811049b174311/app/Http/Controllers/InvoicesController.php#L178-L188

**Screenshots**
<img width="723" alt="Screen Shot 2020-02-02 at 19 24 32" src="https://user-images.githubusercontent.com/2929968/73611315-dae38480-45f1-11ea-865f-5a8012dfa286.png">

**Comment by proea** [comment]
and also 
https://github.com/bytefury/crater/blob/186004f7f8b25af4a26d0f39bba811049b174311/app/Http/Controllers/InvoicesController.php#L417

**Comment by mohitpanjwani** [comment]
Looks like I forgot to fix this conflict. Its fixed

**Comment by mohitpanjwani** [comment]
Thanks for the report btw 👍
