### ISSUE TITLE
Getting a error on the installation

### ISSUE THREAD

**Issue by rohit-web** [bytefury/crater#162]
**showing a not found message**
*Please find the attached screenshot, I had created a virtual host on the local environment as "example.com". it's redirecting on the "on-boarding" but not showing as not found message.
Also, we have given the correct permissions to the folders and it's not showing a any error on the apache error log as well as in the laravel log.

![invoice-laravel-error](https://user-images.githubusercontent.com/16443285/74106342-2070f600-4b8c-11ea-9ad1-3c164dccaa9d.png)

**Comment by MiriShehu** [comment]
Try domain.com/public

**Comment by rizdem** [comment]
have you run composer install?

**Comment by rohit-web** [comment]
it's resolved, thank you
