### ISSUE TITLE
Unable to login after logout.

### ISSUE THREAD

**Issue by shankhadevpadam** [bytefury/crater#163]
**Describe the bug**
Unable to login after logout even login using correct username and password. I think this is due to laravel passport.  I have tried to install force laravel passport also clear passport table in database.

```
php artisan passport:keys --force
```

**Expected behavior**
```
{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}
```

**Screenshots**

**Please complete the following information:**
- Crater version: 3
- PHP version: 7.4.2
- Database type and version: Mysql 5.7

**Optional info**
- OS:  Ubuntu
- Browser: chrome

**Comment by MakerLab-Dev** [comment]
I had the same problem after installing it, but I managed to log in back again by restarting the laravel server and then everything worked.

**Comment by shankhadevpadam** [comment]
> I had the same problem after installing it, but I managed to log in back again by restarting the laravel server and then everything worked.

Not worked.

**Comment by nileshd** [comment]
Having the same problem after installation and logout.. when logging in again.. it's having an error with this message -- "The authorization grant type is not supported by the authorization server."

**Comment by afrastgeek** [comment]
In `.env` file, there's `PROXY_OAUTH_CLIENT_SECRET` directive that should be filled with the generated client secret key when running the `php artisan passport:install` command.

**Comment by shankhadevpadam** [comment]
Thanks @afrastgeek its working now.
