### ISSUE TITLE
Once items are not in the last 9 created, they are not searchable when making an invoice.

### ISSUE THREAD

**Issue by aaronduce** [bytefury/crater#167]
**Describe the bug**
Once more than 9 items are created, only the last 9 are searchable from the add item menu when creating a new invoice.

**Expected behavior**
Expected that I can search and use any of my items.

**Screenshots**
<img width="747" alt="Screenshot 2020-02-15 at 16 47 03" src="https://user-images.githubusercontent.com/20649108/74591828-26932680-5013-11ea-9ef4-9cd561e4a06d.png">
<img width="1460" alt="Screenshot 2020-02-15 at 16 47 18" src="https://user-images.githubusercontent.com/20649108/74591831-27c45380-5013-11ea-9b2f-7d516f821c05.png">

**Please complete the following information:**
- Crater version: v3.0.0
- PHP version: v7.2.27 (Virtualmin's LAMP)
- Database type and version: MySQL v5.5.64

**Optional info**
- OS:  [e.g. Ubuntu] CentOS 7 host, macOS 10.14 Client
- Browser: [e.g. chrome, safari] Safari

**Comment by aaronduce** [comment]
Any updates on this? It’s becoming a big problem as can’t create invoices with those items.

**Comment by ggiak** [comment]
Had the same problem. changed the default value to 50.

**Comment by JacksontheRocks** [comment]
I have the same problem. On the local server I was able to correct it but not on the cloud
 And it's a shame because for that nonsense makes it useless for me.

If anyone can help me I would be eternally grateful

**Comment by ggiak** [comment]
> I have the same problem. On the local server I was able to correct it but not on the cloud
> And it's a shame because for that nonsense makes it useless for me.
> 
> If anyone can help me I would be eternally grateful

why can't you correct it on the cloud ?

**Comment by JacksontheRocks** [comment]
I really don't know. In Items search perfectly all products. But when making the budget and trying to include a product from the database, just search among the last 10

**Comment by mohitpanjwani** [comment]
Guys please wait until next week. 

We are testing the update. All these issues have been fixed. 

Thank you for your patience.

**Comment by JacksontheRocks** [comment]
Ok, thank you very much

**Comment by mohitpanjwani** [comment]
Issue fixed on https://github.com/bytefury/crater/releases/tag/3.1.0

Please update your app from the settings page to receive the new changes.
