### ISSUE TITLE
Cloud backup implementation

### ISSUE THREAD

**Issue by aaronduce** [bytefury/crater#168]
**Is your feature request related to a problem? Please describe.**
There is at current no way to do an export or backup of any form in Crater. (Expanding on issue #97).

**Describe the solution you'd like**
Some sort of implementation of a cloud-storing backup solution that runs on a schedule e.g. daily at 9am or weekly on Tuesday at 7pm. Advantage of cloud storage backup solution would mean they are not stored on the server and so on event of server failure or other data access-limiting problems the data is restorable and safe.

This could supposedly use the dropbox flysystem driver (https://laravel.com/docs/master/filesystem#custom-filesystems) to upload an exported csv or backup that is done to the user-specified schedule.

One example of a similar functionality/implementation is in the UpDraftPlus plugin for WordPress - backup on a schedule and when complete is uploaded to the cloud storage driver/provider. e.g. for dropbox it stores the backups in Dropbox / Apps / UpDraftPlus / *.

**Describe alternatives you've considered**
Not really any alternatives, just a straight forward backup solution.

**Comment by mohitpanjwani** [comment]
Hey! We are working on this already.

Thanks for the feedback

**Comment by jpmurray** [comment]
@mohitpanjwani Can you elaborate what you're backup scheme is ? I was about to work on an PR to implement Spatie's backup packages ;-)

**Comment by mohitpanjwani** [comment]
> @mohitpanjwani Can you elaborate what you're backup scheme is ? I was about to work on an PR to implement Spatie's backup packages ;-)

We will be basically providing a UI on top of spatie backup package. We have already implemented this on 4.0 👍

**Comment by jpmurray** [comment]
I'll leave it be then ! :D

**Comment by mohitpanjwani** [comment]
Added this on V4.
