### ISSUE TITLE
Anyplan to move the business logic outside controller?

### ISSUE THREAD

**Issue by daison12006013** [bytefury/crater#169]
**Is your feature request related to a problem? Please describe.**
Upon checking the code, all of the the logic lives inside the controller. It will be hard for us to separate the methods per Single Responsibility.

**The benefits of moving out the logic:**
* We could apply unit testing per methods, feature/functional will be absolutely great but we don't cover every line of codes.
* Mockable methods for huge conditions that requires data from the database yet we could easily return fake values using mocking tools to bypass that condition for nested if-statements.
* Re-usable codes for outside project.
* Extendable codes with your own unique namespace, **e.g:** ByFury\Crater\Core

**Lacking in this Project:**
* Unit Testing
* Coverage
* Extendable/Inheritable Classes
* Support as a `vendor` package, where developers could `composer require` this package instead of downloading as a boilerplate.

**Comment by mohitpanjwani** [comment]
Hey @daison12006013!  Those are some very good suggestions but at the moment our focus is on releasing the pending features on the Roadmap. 

We've already added feature tests but we'll look into adding unit tests soon as time permits.

Other than that, we have no plans of supporting crater as a composer package as we prefer to keep Crater as a standalone application

**Comment by daison12006013** [comment]
Alright.
