### ISSUE TITLE
Invalid characters passed ^~ç á à 

### ISSUE THREAD

**Issue by coelhocarlos** [bytefury/crater#171]
**Describe the bug**

ErrorException
Invalid characters passed for attempted conversion, these have been ignored

**Expected behavior**

:2598
vendor/dompdf/dompdf/lib/Cpdf.php:2598
line  if ($c != hexdec($n)) {

**Screenshots**

**Please complete the following information:**
- Crater version: 3
- PHP version:  7.4
- Database type and version:  5.7

**Optional info**
- OS:  [e.g. Ubuntu] ubuntu 18
- Browser: server

**Comment by mohitpanjwani** [comment]
This should no longer be an issue on V4. 

Please re-open if you still encounter this.
