### ISSUE TITLE
Server error in Setup

### ISSUE THREAD

**Issue by gddy** [bytefury/crater#173]
Hi
I am following the manual installation guide in https://docs.craterapp.com/installation.html#manual-installation. Everything is alright until in step 3 of setup. It says me "Server error" when I try to connect my db. Any advise on possible reason of this error?
![image](https://user-images.githubusercontent.com/8643282/75508408-fd18c880-5a1e-11ea-9fd6-b16180ecd844.png)

**Comment by mohitpanjwani** [comment]
> Hi
> I am following the manual installation guide in https://docs.craterapp.com/installation.html#manual-installation. Everything is alright until in step 3 of setup. It says me "Server error" when I try to connect my db. Any advise on possible reason of this error?
> ![image](https://user-images.githubusercontent.com/8643282/75508408-fd18c880-5a1e-11ea-9fd6-b16180ecd844.png)

Hey! sorry for the delayed response.. we had an urgent project which needed immediate attention but we're back. 

Can you update your .env file and change APP_DEBUG=true? That should give you the proper response and help find out the cause of the error.

Also can you mention the other details like: 
server, Crater version, database type and version?
