### ISSUE TITLE
Cant show correct Chinese word in PDF

### ISSUE THREAD

**Issue by lamtszhin0528** [bytefury/crater#175]
We can type Chinese while create Item but it can't show on PDF even invoice or estimate 
Checked db is no problem and that's correct inside,

- Crater version:  3.0

<img width="424" alt="image" src="https://user-images.githubusercontent.com/58826592/75590223-c642c100-5ab7-11ea-83b0-fd5e77256d05.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/58826592/75590296-0013c780-5ab8-11ea-824b-fd2c9ff83407.png">

**Comment by howiengai** [comment]
You may follow this instruction to add chinese font into dompdf. it works for me.

[php – 使用 dompdf/dompdf 轉換繁體中文可支援的 PDF
](https://jsnwork.kiiuo.com/archives/2736/php-%E4%BD%BF%E7%94%A8-dompdf-dompdf-%E8%BD%89%E6%8F%9B%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87%E5%8F%AF%E6%94%AF%E6%8F%B4%E7%9A%84-pdf/)

**Comment by mohitpanjwani** [comment]
Any PRs regarding this are welcome.
