### ISSUE TITLE
Please add a footer to the invoice templates

### ISSUE THREAD

**Issue by Chalkin** [bytefury/crater#178]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to add a footer to any documents. Usually on every invoice we provide the bank details and the company details.

**Describe the solution you'd like**
Please add a footer section which makes it possible to add additional information to every document, like company address, business owner, tax info and bank information.

**Comment by ggiak** [comment]
@Chalkin You can always use the notes section for additional information
or even create a separated invoice template with whatever footer you need.

example like:
![image](https://user-images.githubusercontent.com/20743694/78513020-64a9fc80-77b1-11ea-842b-dcb08f119620.png)

**Comment by Chalkin** [comment]
The notes section is not enough - I need to format the information. Also traditionally all information regarding the company and bank information is placed on the bottom of the invoice.

How can I create a separate invoice template?

**Comment by ggiak** [comment]
You need to get your hands into the codebase for that.

you need to create two files, lets call it invoice4.blade.php:
./resources/views/app/pdf/invoice/invoice4.blade.php
./resources/views/app/pdf/estimate/invoice4.blade.php

using your own custom design and insert an additional row into the database table:
invoice_templates & estimate_templates

After you successfully done this, a Template 4 will appear like so:
![image](https://user-images.githubusercontent.com/20743694/78520819-88c90600-77d0-11ea-91a1-6be0bfe5b163.png)

**Comment by mohitpanjwani** [comment]
I don't think everyone needs a footer on Invoice. 

You can create a custom template in order to fix this.
