### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by omexlu** [bytefury/crater#179]
Hello,

I have a few questions about this development:
- Is there a forum or community where i can register for futher support?
- Is it possible to use the program locally e.g. in WAMP with a local domain e.g. 'test.loc'?
- Does the update function also work locally?

Thanks in advance.

**Comment by ggiak** [comment]
Hello @omexlu,

there is **yes** to all your questions.

you can check out the following documentation for manual installation of craterapp
right here where upload to the server means your local server.

https://docs.craterapp.com/installation.html#manual-installation

make sure you mean all the requirements and it sure work.
