### ISSUE TITLE
Installation - "The database hostname may not be greater than 50 characters."

### ISSUE THREAD

**Issue by leemcd56** [bytefury/crater#18]
When adding a hostname I receive this error. I am using a database cluster on DigitalOcean and cannot connect because of this limitation. Are there any workarounds?

**Comment by leemcd56** [comment]
**Update:** Did a little looking around and found out the request validator in `app/Requests/DatabaseEnvironmentRequest.php` catches this. I don't believe it should have a max length because someone could connect to an external database.

**Comment by mohitpanjwani** [comment]
> **Update:** Did a little looking around and found out the request validator in `app/Requests/DatabaseEnvironmentRequest.php` catches this. I don't believe it should have a max length because someone could connect to an external database.
> 
> In `app\Space\EnvironmentManager.php` there is a check on line 57 for database tables, but this command does not work in Postgres. When using `\Schema::hasTable('users')` instead (to check for preexisting migration) I was able to proceed with setup. It also successfully prevents setup if the database is already populated.

Thanks for reporting the issue. We've removed the hostname validation of 50 characters to allow larger values. 

Also, we've added a prefix to all the crater related tables and updated the DB Check to `\Schema::hasTable('cr_users')` so users can install crater in existing databases ( not forcing them to create a new DB specifically for crater).
