### ISSUE TITLE
When converting Estimate to Invoice dates should be null or today

### ISSUE THREAD

**Issue by ggiak** [bytefury/crater#182]
**Describe the bug**
Given that I have created one estimate and one invoice with the following dates:

1) EST-000001 01/01/2020
2) INV-000001 02/02/2020

When I convert the estimate into an invoice it produces the
INV-000002 with Created Date on 01/01/2020

Then I end up having:

INV-000001 (02/02/2020)
INV-000002 (01/01/2020)

at least in Europe (don't know about the rest of the world)
is wrong in accounting point of view.

**Comment by mohitpanjwani** [comment]
@ggiak You mean that it should take today’s date instead of estimate date right?

**Comment by ggiak** [comment]
> @ggiak You mean that it should take today’s date instead of estimate date right?

maybe yes. taking today's date would be valid in book keeping.

**Comment by mohitpanjwani** [comment]
Issue fixed on https://github.com/bytefury/crater/releases/tag/3.1.0
