### ISSUE TITLE
Item Total price is devided by 100 when negative.

### ISSUE THREAD

**Issue by ggiak** [bytefury/crater#185]
**Describe the bug**
Given I am trying to cancel an invoice (issue a credit memo)
When I enter the negative value of the amount it devices the item total by 100

**Expected behavior**
not to be devided by 100 :)

**Screenshots**
![image](https://user-images.githubusercontent.com/20743694/78513370-b9e70d80-77b3-11ea-9e5b-4247b3685c7e.png)

**Please complete the following information:**
- Crater version: 3.0
- PHP version: W/E Docker-compose has
- Database type and version: same

**Comment by mohitpanjwani** [comment]
@ggiak thanks for your feedback but negative invoices/estimates are not supported as of v3.0

**Comment by ggiak** [comment]
> @ggiak thanks for your feedback but negative invoices/estimates are not supported as of v3.0

Thanks for the answer.
I'll convert this into feature request. something like: "Cancel invoice" perhaps. :)
