### ISSUE TITLE
Chart pricing is not divided

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#186]
**Describe the bug**
Chart Y axis values are not divided for real visuals

**Expected behavior**
Should be divided

**Screenshots**
https://i.imgur.com/JfaTmbj.png

**Please complete the following information:**
- Crater version: 3.0.0
- PHP version: 7.4
- Database type and version: PostgreSQL v12

**Optional info**
- OS:  Ubuntu 18.04
- Browser: Firefox

**Comment by mohitpanjwani** [comment]
damn! how did we even miss this! 

Thanks for feedback.

**Comment by mohitpanjwani** [comment]
Issue fixed on https://github.com/bytefury/crater/releases/tag/3.1.0
