### ISSUE TITLE
Error on invoice preview

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#187]
**Describe the bug**
Error on all invoice preview pages/sections

**Expected behaviour**
Invoice generated

**Screenshots**
https://i.imgur.com/988W3Tg.png

**Please complete the following information:**
- Crater version: 3.0.0
- PHP version: 7.4
- Database type and version: PostgreSQL v12

**Optional info**
- OS:  Ubuntu 18.04
- Browser: Firefox

**Comment by lawzava** [comment]
It's an issue with the dependency which was already resolved in December: https://github.com/dompdf/dompdf/pull/2027/files

**Comment by lawzava** [comment]
`composer update` solves this issue. The "downloadable" should be updated as well.

**Comment by mohitpanjwani** [comment]
We didn't test it yet on PHP 7.4 

Thanks for the help 👍

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1
