### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by luizbills** [bytefury/crater#19]
I would like to translate to portuguese.

**Comment by mohitpanjwani** [comment]
Hey! I'm looking to set up a localization solution of some kind to allow language contributions.

I'm confused between Transifex and crowdin.

**Comment by mohitpanjwani** [comment]
Hey, I've set up the transifex project: https://www.transifex.com/bytefury/crater-invoice 

Now you can help us translate crater into Portuguese.

**Comment by lupuxyz** [comment]
@mohitpanjwani  I sent the request to translate to Chinese,please check my request.

**Comment by vesper8** [comment]
I would like it if you explained how we can add a custom translation without having to go through Transifex. What translation tool were you using before? Do all translation strings throughout the code follow Laravel standards?

**Comment by azaricstefan** [comment]
@mohitpanjwani can you add language Serbian (both Cyrillic and Latin versions) to the project in transifex?

I would like to translate whole application in the following days.

https://www.transifex.com/bytefury/crater-invoice/

Thanks!

**Comment by caiodigioia** [comment]
> I would like to translate to portuguese.

Olá, @luizbills ! Tudo bem?
Conseguiu traduzir a aplicação?
