### ISSUE TITLE
Warning message before removing customer

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#190]
**Is your feature request related to a problem? Please describe.**
While cleaning up you can mistakenly remove a wrong customer with all the data.

**Describe the solution you'd like**
A warning indicating that the customer has invoices assigned and removing it would remove the invoices as well

**Describe alternatives you've considered**
Removing customer but keeping all the invoices.

**Comment by mohitpanjwani** [comment]
Warning message added on https://github.com/bytefury/crater/releases/tag/3.1.0
