### ISSUE TITLE
Translation Help and Comment Placement

### ISSUE THREAD

**Issue by celevra** [bytefury/crater#193]
Hi,

i need to translate the Table Headers in the Invoice View, where do i have to Place the Translation?
In Germany if you don't invoice taxes, you have to place a Comment on the Invoice that you are a little man ;-) But i can't find an option to insert such comments, is there a way?

regards

**Comment by celevra** [comment]
ok i've seen the words are hardcoded in the Template so no central translation
But there is a partital notes template, so back to the second question, where can i configure such notes?

**Comment by rexlManu** [comment]
You mean that as a small business owner you don't have to issue a sales tax number because of the German regulations that exist there. But in detail this function is missing, so you can add your own text to the invoice below.

**Comment by mohitpanjwani** [comment]
PDFs are also translatable in V4 now. 

You can help us translate in your local language using this tool: https://crowdin.com/project/crater-invoice
