### ISSUE TITLE
Crater App installer won't run on ubuntu server 18.04

### ISSUE THREAD

**Issue by reactionstudio** [bytefury/crater#197]
**Describe the bug**
After uploading application, /on-boarding results in an apache 404 page, when changing to /index.php/on-boarding i get a 404 page returned by the application, clicking "go home" takes me to the main login page, but the initial setup process will not run so i cannot configure the application

**Expected behavior**
Application installer to run

**Screenshots**
![crater-app-2](https://user-images.githubusercontent.com/13775360/79689738-a4abbd80-824e-11ea-9e45-2c462da779ad.png)
![crater-app-1](https://user-images.githubusercontent.com/13775360/79689739-a6758100-824e-11ea-9655-1ff503e4233a.png)

**Please complete the following information:**
- Crater version: 3.0.0
- PHP version: 7.2.24
- Database type and version: n/a

**Optional info**
- OS:  Ubuntu Server 18.04

**Comment by reactionstudio** [comment]
My apache config is standard out of the box aside from the document root which was changed to point towards the crater public folder:

```
<VirtualHost *:80>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/public

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

**Comment by MakerLab-Dev** [comment]
Looks like the .htaccess isn't working on your installation, first of all check if you have "mod_rewrite" installed and enabled in your apache installation.

If it isn't enabled:
`sudo a2enmod rewrite`
`sudo systemctl restart apache2`

**Comment by reactionstudio** [comment]
Thank you for your help, that got it fixed everything is working now.
