### ISSUE TITLE
A long name in billing / shipping address is killing the invoice.

### ISSUE THREAD

**Issue by HamzaDevz** [bytefury/crater#198]
**Describe the bug**
A long name in billing / shipping address is killing the invoice.

**Expected behavior**
The invoice needs to be capable of handling long names

**Please complete the following information:**
- Crater version: 3.0.0
- PHP version: 7.2
- Database type and version: mariadb

**Optional info**
- OS: Ubuntu / Docker
- Browser: chrome

**Comment by HamzaDevz** [comment]
I create a Pull Request that fix this behavior.

**Comment by mohitpanjwani** [comment]
Issue fixed on https://github.com/bytefury/crater/releases/tag/3.1.0
