### ISSUE TITLE
Unable to install in different databases than mysql

### ISSUE THREAD

**Issue by rafaelmb** [bytefury/crater#20]
Hello.

In App\Space\EnvironmentManager function saveDatabaseVariables have a call to select "SHOW TABLES". This query makes the app installer mysql only. Didn't have time anymore to keep checking but got some calls to DB::raw too, that usually limits laravel to a single database only.

Found out about you guys on reddit, keep up the good job!

**Comment by mohitpanjwani** [comment]
Hey, thanks for trying out Crater and reporting the issue. 

We'll test with other database drivers and check it out.

**Comment by mohitpanjwani** [comment]
@rafaelmb hey! I forgot to mention this earlier but this issue has been fixed in the latest update. 
Also, we've tested on both MySQL & PostgreSQL. It seems to work as expected :)

**Comment by rafaelmb** [comment]
Thanks, I will give it a try.

**Comment by DelphiWorlds** [comment]
Using Sqlite does not work, at least it did not for me

**Comment by NicoHood** [comment]
Hey there! I came here by google and just wanted to try out crater. You can select the database driver, but is there a preferred driver, that you are mainly testing against? My wild guess would be mysql should be fine, but is that also correct?
