### ISSUE TITLE
Payment mode in double

### ISSUE THREAD

**Issue by Misdirectionmaster** [bytefury/crater#205]
In settings > Customization > Payments, when you add a payment mode like "Paypal" for example, it appears in **double** in the list just after clicking "_Add Payment Mode_".

Then if you refresh the page, there is only one.

**Comment by mohitpanjwani** [comment]
Thanks for reporting the issue. We're working on a fix

**Comment by mohitpanjwani** [comment]
Issue fixed on https://github.com/bytefury/crater/releases/tag/3.1.0
