### ISSUE TITLE
Order of items is reversed when I click on save

### ISSUE THREAD

**Issue by m0r3z** [bytefury/crater#206]
**Describe the bug**
Order of items is reversed when I click on save

**Expected behavior**
Hello,
when I save my estimate or my invoice the order of the items is reversed, if then I click Save again, the items are put back in order...

I discovered crater, very good job! Thanks for your help!

**Screenshots**
![Capture d’écran 2020-05-01 à 18 58 18](https://user-images.githubusercontent.com/56673407/80814940-d2451f00-8bdd-11ea-9b29-d10e9e5ecbf5.png)
![Capture d’écran 2020-05-01 à 18 58 33](https://user-images.githubusercontent.com/56673407/80814945-d4a77900-8bdd-11ea-9670-0bd31dbaad21.png)

**Please complete the following information:**
- Crater version: 3.0.0
- PHP version:  7.2
- Database type and version: MySQL

**Comment by mohitpanjwani** [comment]
Thanks for reporting! we'll check it out

**Comment by m0r3z** [comment]
Hello,
I am looking for a solution on my server, but maybe the problem is simply that I do not have the possibility to activate all the required PHP options.

I miss him :
Ctype PHP Extension
OpenSSL PHP Extension
Tokenizer PHP Extension

I'm at PlanetHoster with a cPanel here are my options in 7.2

![Capture d’écran 2020-05-08 à 10 41 25](https://user-images.githubusercontent.com/56673407/81379055-7583c000-9119-11ea-8003-f2cdb4870a92.png)

**Comment by mohitpanjwani** [comment]
I cannot reproduce this issue anymore in V4. 

Please reopen if you still encounter this.
