### ISSUE TITLE
PDF generation not working on php7.4

### ISSUE THREAD

**Issue by rushxs7** [bytefury/crater#207]
I cannot download a PDF from invoices I've made up. I've read that it is a php7.4 issue and something to do with the mpdf library.

The only thing displayed is a 500 server error when trying to display an invoice or mailing the invoice.

Also, I cannot downgrade to a lower PHP version because i already have laravel applications depending on php7.4

**Comment by mohitpanjwani** [comment]
Hey! 

We are working on refactoring all the invoice templates and also fixing issues with latest php version. 

This will be fixed in next week’s update.

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1
