### ISSUE TITLE
Get sharable link to PDV Invoice if already sent.

### ISSUE THREAD

**Issue by adampatterson** [bytefury/crater#208]
This is related to resending an invoice ref #100

I would like the ability to view the PDF invoice from the customer URL. Or have the option to copy it.

I was asked to resend an invoice and that ability does not exist #100 so I thought I would copy the PDF URL.

Short of going into the database, I don't see how or where to get it.

**Comment by mohitpanjwani** [comment]
Featue added on https://github.com/bytefury/crater/releases/tag/3.1.0

**Comment by adampatterson** [comment]
Amazing!
