### ISSUE TITLE
crater.users.name isn't in GROUP BY

### ISSUE THREAD

**Issue by bee-interactive** [bytefury/crater#21]
Hi!

I just installed locally a version of the package. But after I created my first client, I got this error on the clients listing page. Did I miss something?

```
"SQLSTATE[42000]: Syntax error or access violation:
1055 'crater.users.name' isn't in GROUP BY
(SQL: select 'users'.*, sum(invoices.due_amount) as due_amount from 'users'
left join 'invoices'
on 'users'.'id' = 'invoices'.'user_id' where 'role' = customer
and 'users'.'company_id' = 1
group by 'users'.'id' limit 10 offset 0)"
```

The error seems to happen here: "Crater\Http\Controllers\CustomersController".

Thanks for your time!

**Comment by mohitpanjwani** [comment]
Hey!  Thanks for reporting the issue.

Can you mention your OS, PHP Version, Database driver(mysql / postgres)?

**Comment by mshoaibdev** [comment]
When listings customers it shows same error.

**Comment by bee-interactive** [comment]
> Hey! Thanks for reporting the issue.
> 
> Can you mention your OS, PHP Version, Database driver(mysql / postgres)?

Hi ! 

I'm using a Mac with Mojave, php 7.3, laravel valet and the la test version of mysql. Does this informations help ?

**Comment by mohitpanjwani** [comment]
> > Hey! Thanks for reporting the issue.
> > Can you mention your OS, PHP Version, Database driver(mysql / postgres)?
> 
> Hi !
> 
> I'm using a Mac with Mojave, php 7.3, laravel valet and the la test version of mysql. Does this informations help ?

Thanks for the info. I think I've got an idea of what the issue might be. 

Can you mention your MySQL version? Its happening in order versions of mysql.

**Comment by mshoaibdev** [comment]
Fount the solution to this error. In the database config, if you change the strict value to false, It works.

**Comment by mohitpanjwani** [comment]
> I found a solution to this error. In the database config, if you change the strict value to false, It works.

You're right! that would fix it. You can disable the strict mode, for now, to get the job done :) 

but we're looking for an alternative solution ( modifying the query itself so it follows the rules).

More info here:
https://stackoverflow.com/questions/41571271/group-by-not-working-laravel

**Comment by mohitpanjwani** [comment]
Issue has been fixed on below commit: https://github.com/bytefury/crater/commit/f0107129fbea072488ef78f40456066c2f692104
