### ISSUE TITLE
Show partially paid invoices

### ISSUE THREAD

**Issue by adampatterson** [bytefury/crater#210]
I may have made a mistake, But I would like to have show partially paid invoices under Due rather than all under the invoice section.

* I took an invoice with let's say $2000 owing on it
* I entered a payment of $1000
* I then selected the invoice ( did not notice the payment just to the full amount of $2000 )
* Realized my mistake and changed the payment to $1000

I went to confirm that the payment owing was still $1000

The invoice shows an amount due of $1000 but it is listed under all, and in my case almost on the next page, so it would be hard to find.

**Comment by mohitpanjwani** [comment]
Thanks for reporting. 

I agree that partially paid invoices should appear on Due tab.  

It will be fixed in the next minor update next week.

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1

**Comment by adampatterson** [comment]
@mohitpanjwani I just updated to 3.1.1 and my partially paid invoice is still on the second page of the app tab. It is not showing up under Due.

If I view all invoices and then filter for Due I also do not see the partially paid invoices.

Possibly in my case, the Invoice status us Overdue, and the Payment Status is Partlaily Paid

**Comment by mohitpanjwani** [comment]
ah sorry! It looks like we merged this fix into 4.0.0 instead of this minor release. 

I'll reopen the issue and include the fix in the next release.

**Comment by azaricstefan** [comment]
This issue should be resolved then. 4.0.0 is out. 
@mohitpanjwani maybe close it now?

**Comment by adampatterson** [comment]
Awesome!

**Comment by mohitpanjwani** [comment]
Yes this is fixed in 4.0.0! 

Closing.
