### ISSUE TITLE
Notes/Details for company profile

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#212]
**Is your feature request related to a problem? Please describe.**
When issuing an invoice near the "issuer" usually payment details need to be specified on how to pay/resolve this invoice. 

**Describe the solution you'd like**
The Notes section would be a generic box after the address details to specify any details regarding payments/vat and etc.

**Describe alternatives you've considered**
For now I'm using Address 2 field for these details. It's ugly since the country is placed after that field

**Comment by mohitpanjwani** [comment]
I think this should be possible to do using Custom Fields now. 

If not, we're considering a different approach as given in https://github.com/bytefury/crater/issues/295
