### ISSUE TITLE
Additional fields for company for client/user

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#213]
**Is your feature request related to a problem? Please describe.**
Companies have additional details that are often required to be provided. e.g. Company Number, VAT number, license number and etc.

**Describe the solution you'd like**
I would like to see dedicated fields for both client and user companies for these additional parameters. Ideally key:value dynamic (add/remove) array. If not, at least 2 static fields for key:value information. If not, at least "company number: text".

**Describe alternatives you've considered**
For now, I'm putting these details under company name after the comma, e.g. "Screws LTD, Company Number: 215123123, VAT ID: 251231151"

**Comment by mohitpanjwani** [comment]
This has been the most requested feature. 

Custom fields are soon coming on 4.0.0

**Comment by camelscript** [comment]
@mohitpanjwani  When it is planned to release v4.0?

**Comment by yehanny** [comment]
I'm still waiting for this feature too to implement this application in my company, this would be a GREAT feature, please!

**Comment by eboye** [comment]
This is the feature that I cannot use the app without. I'm currently using invoice plane and would really like to switch, but can't.

I see that no work has been done on 4.0.0 Is it something we could expect in near future or?

Thanks again, this looks really promising to me.

**Comment by mohitpanjwani** [comment]
Hey guys! 

Sorry I haven’t mentioned it here but 4.0.0 will be released tomorrow. 

It contains following changes & more: 
- Recreated all frontend components & pages in TailwindCSS ( removed bootstrap)
- Create Backup (File & DB)
- File Disk Configuration ( Saves PDFs or Backups to Digital Ocean Spaces, AWS S3 & Dropbox)
- New Customer View page
- Custom Notes for Estimates, Payments & Invoices
- Unit & Feature Tests
- Cleaner & Performant Backend API
- API Documentation
- Edit Email Subject & Description with placeholders before sending out an Invoice or Estimate Email
- Custom Fields ( define your own fields on Invoices, Estimates, Payments & Expenses. ) 
- Customize your Address formats on PDFs ( use custom or basic fields according to your preference)
- Global Search
- Manage Admin Users (Add, Edit and remove Admins)

—————

Also, Please join the discord server - Beta channel if you are interested to help with testing beta releases and see what’s coming.

**Comment by yehanny** [comment]
Finally we got a really GOOD feature, thanks for this @mohitpanjwani I'm gonna start to move out my billing system to this, GREAT!

**Comment by eboye** [comment]
WOW, this is better then I expected. Thanks. I'll definitely check the discord server.

**Comment by azaricstefan** [comment]
Great features released with v4!

Shall we close this issue now?

**Comment by mohitpanjwani** [comment]
@azaricstefan Thanks yes! I'll close this now :)

**Comment by NicoHood** [comment]
Hey guys, I came here via google and I am quite lost.

What I need is to add a german tax note (Kleinunternehmer) and payment details to every invoice. How would I do this best? Are there templates available somewhere? Something to get started would be nice, or maybe there is even an upstream footer customization feature?

**Comment by samayo** [comment]
@NicoHood Have you checked the VAT section in the invoice? You can create custom tax field 
![image](https://user-images.githubusercontent.com/5304093/161106334-f47487d8-ab8b-49ca-8e93-4051ab787ea2.png)

**Comment by NicoHood** [comment]
Yes I know, but I need to declare a statement, saying that no taxes will be added. Like an additional note, but on all invoices.

**Comment by samayo** [comment]
There is more than one way to do this, I have only tried the first one and it's a bit manual process. 

- Go to **Settings** > **Custom Fields** and create a new Field like this: 
![image](https://user-images.githubusercontent.com/5304093/161120682-3c765096-8c3f-47ee-8ebf-4fda26b7d6a8.png)

Then when creating an invoice, in the **Notes** section click on **+Insert Fields** and select the Custom field. 

There should be a way to automatically make the text appear instead of clicking on Notes everytime but I don't know how ... I know it's possible but not right now

**Comment by SGr33n** [comment]
Hi!
I see now is possible to add custom fields! Unfortunately looks like is not possible to add custom fields for "My Company".
Is it a planned feature?
Thanks for your great work!

**Comment by RebelSoftware** [comment]
I'd like to add my voice to the request for custom company fields.

For example in Australia it is required that all invoices show an ABN or Company Number on invoices. The most logical place to include that is in the company information.

A workaround is to create a custom invoice field and pre-populate it with your ABN, however its not "technically" correct.

Adding custom fields to the company information is a more reasonable

**Comment by Ghosty01** [comment]
+1
