### ISSUE TITLE
Unable to install localhost:8000 url and sqlite database 

### ISSUE THREAD

**Issue by satheeshdomainindia** [bytefury/crater#215]
**Is your feature request related to a problem? Please describe.**
Yes while installing app in local system Unable to use localhost:8000 url and sqlite database 

**unable to install local system for learning** 
https://docs.craterapp.com/developer-guide.html#installation

i feel this Developer Guide for installation is incomplete because if i fellow this steps i am struck to setup url and db      thats why unable to complete setup

**Comment by mohitpanjwani** [comment]
Hello @satheeshdomainindia, 

This is definitely an issue and will be fixed on the next update but to proceed, for now you can just write any random URL. 

You can manually, update the `.env` file's APP_URL field after installation is complete and that will do the job: 
```
APP_URL=http://localhost:8080
```

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1
