### ISSUE TITLE
Could not find driver MySql

### ISSUE THREAD

**Issue by etEthiopia** [bytefury/crater#218]
**Describe the bug**
I have installed all the things the app needed and I created a mysql database but when I reach the database section It displays "Could not find driver".
Assume my IP is 0.0.0.0 in digital ocean.
I entered "http://0.0.0.0" as App URL (This might be the problem) 

**Expected behavior**
To pass to the next stage after connecting the database I created.

**Screenshots**
![Screenshot (123)](https://user-images.githubusercontent.com/39325611/83528764-29e2ed00-a4f2-11ea-98dd-9e231f965ad4.png)

**Please complete the following information:**
- Crater version: 3 and above
- PHP version: 7.2
- Database type and version: Mysql 5.*

**Optional info**
- OS:  Ubuntu 18.04
- Browser: [e.g. chrome, safari]

**Comment by mohitpanjwani** [comment]
Hi @etEthiopia, can you mention the specific version of Crater that you're using?

**Comment by etEthiopia** [comment]
It was because I was using digital ocean.
They now have released a patch for it.
