### ISSUE TITLE
Address issue - US states off by one

### ISSUE THREAD

**Issue by KevinBatdorf** [bytefury/crater#22]
I selected Florida but received cities for Georgia. This happens for each state selected.
<img width="1366" alt="Screen Shot 2019-11-29 at 1 46 10 AM" src="https://user-images.githubusercontent.com/1478421/69827796-98957400-124b-11ea-9d42-a095af36ee78.png">

Also, the UX is super clunky using LastPass. You could add ` data-lpignore='true'` or even better just let users enter the information in a text field.

**Comment by mohitpanjwani** [comment]
Hey! this has been fixed but we're waiting on 3 other features that we are assuming to complete by the end of this week.

We will release a new major update as soon as it's done. 

Just FYI, we've removed the states & city selectors as per discussion on this issue: https://github.com/bytefury/crater/issues/13

**Comment by mohitpanjwani** [comment]
Also, I actually made the mistake of closing 1 or 2 issues after fixing it locally but from now onwards I'll keep the issues open until the update has been released and tested.

**Comment by mohitpanjwani** [comment]
Closing this issue as it's fixed in 2.0 update. We've replaced the state & city selectors with text inputs.

More discussion on: #13
