### ISSUE TITLE
[Docker] Add Redis ?

### ISSUE THREAD

**Issue by jpmurray** [bytefury/crater#223]
Just checking, would you be interested it getting Redis into the Docker image too? I can send a PR for it, I made it work on my end, but if you feel it's unnecessary, I'll let it go :)

**Comment by jpmurray** [comment]
(Just a side note, if you want to chat about those changes I sent, and propose here, I jumped on the Discord server !)

**Comment by mohitpanjwani** [comment]
I think that would be very useful @jpmurray. 

That would save us some time in the future as we'll need it for Recurring Invoices etc. 

> (Just a side note, if you want to chat about those changes I sent, and propose here, I jumped on the Discord server !)

Awesome! I'll be sure to send a message if there's anything. Thanks for the help so far

**Comment by mohitpanjwani** [comment]
Closing this as we don't use Redis at the moment. 

We might consider this for a future release.
