### ISSUE TITLE
Add DNI number (string) to My company and customers data

### ISSUE THREAD

**Issue by diegojbs** [bytefury/crater#224]
Hello,

Is it just to request add a field in company table and customers table to save DNI, is is very important to print this data in PDF documents.

Thanks

**Comment by Loosie94** [comment]
As is the Chamber of Commerce number (in the Netherlands), so this could probably be the same field with a different translation.

**Comment by vdvcoder** [comment]
Yes, same for Belgium. Here it's called BTW number. And also a field for the bank account number both company as customer.

Thank you!

**Comment by mohitpanjwani** [comment]
You can now do this using Custom Fields in V4.
