### ISSUE TITLE
Invalid URL when onboarding in test environment

### ISSUE THREAD

**Issue by DelphiWorlds** [bytefury/crater#23]
Apparently the following URL is invalid:

http://127.0.0.1:8000

On the Site URL & Database page

Alternatively, can someone advise how to run Crater in a test environment?

**Comment by mohitpanjwani** [comment]
Hey! Thanks for reporting the issue. 

We'll need to fix the validation to support this address. 

We'll look into it but meanwhile, you can use a domain like `crater.test` which is pretty easy to do if you're using something like Laragon or Laravel valet ( for mac )

**Comment by mohitpanjwani** [comment]
it's fixed in 2.0 update

**Comment by calumshep** [comment]
I've just had this issue occur in v4.0.1, fresh repo clone. With the same URL.

**Comment by coachben** [comment]
Hello guys

I am using crater.test. and experiencing this issue.
Could you please advise?
