### ISSUE TITLE
Multiple admins support

### ISSUE THREAD

**Issue by azaricstefan** [bytefury/crater#231]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add more admins which can do all operations.

**Describe the solution you'd like**
Ability to create new admin in app. Create user, add details, create.

**Describe alternatives you've considered**
I tried adding admin manually inside the DB and it worked.
Problem was that when such admin logged in he saw details of the initial admin in top right corner and application is showing details for initial admin.
Also additional admin is not able to reset password through feature "forgot your password".

**Comment by loftwah** [comment]
Are you able to get a screen capture of this scenario? I can't quite understand exactly, but this sounds kind of like a user roles system, is that correct? What user did you use to add into the database?

**Comment by azaricstefan** [comment]
Admins which I created additionaly have role "admin", and company_id 1. Which is same as initial admin.

Initial admin is me, and in the image screenshot you can see other admin.

Problem with this is the hardcoded getting of Admin user in CompanyController line 29.

Snippet:
```
class CompanyController extends Controller
{
    /**
     * Retrive the Admin account.
     * @return \Crater\User
     */
    public function getAdmin()
    {
        return User::find(1);
    }
.....
}
```

@mohitpanjwani is there already a PR for this to fix or?

**Comment by azaricstefan** [comment]
This is supported in V4 so closing this item.
Thanks!
