### ISSUE TITLE
Following installation instructions gives import/require error

### ISSUE THREAD

**Issue by dhensen** [bytefury/crater#236]
**Describe the bug**
Browser tells me:
```
Warning: require(/var/www/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/public/index.php on line 24

Fatal error: require(): Failed opening required '/var/www/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/public/index.php on line 24
```

**Expected behavior**
I expected the app when I surf to localhost as stated in step 5 of the docker installation page (https://docs.craterapp.com/installation.html#docker-installation)

**Screenshots**
See bug description.

**Please complete the following information:**
Done via git clone of this repo using b7189595bd0a37a69e43f2b52fe5b5ba8a7bf50f (latest master at moment of typing this)
- Crater version: using your docker-compose file
- PHP version: using your docker-compose file
- Database type and version: using your docker-compose file

**Optional info**
- OS:  Arch Linux, but should not matter, running this via docker
- Browser: is a backend issue.

**Comment by BramDriesen** [comment]
Did you install all your packages with composer?

**Comment by loftwah** [comment]
I dhensen, I'd like to assist you with this if you're interested.

**Comment by tweikiang** [comment]
same issue when installing @ my ubuntu docker.

**Comment by oscar-g** [comment]
I had the same problem and traced it to a permissions error in the app container.

`docker-compose.yml specifies the build argument: `uid: 1000`. However, the files in the `app` container were assigned to user `1001`.

I didn't look into what may have caused this, but there's a workaround, if someone else has this problem:

Mody the `docker-compose/setup.sh` to include the `user` option in the exec command:

```
#!/bin/sh

CMD='docker-compose exec --user=1001 app'

$CMD composer install --no-interaction --prefer-dist --optimize-autoloader

$CMD php artisan storage:link || true
$CMD php artisan key:generate
$CMD php artisan passport:keys || true
```

**Comment by TheT0fu** [comment]
Have the same problem on Debian 10.
The "crater-user" does not have the required rights.
![](https://i.imgur.com/QmCNNUt.png)

Thanks @oscar-g for the workaround, but unfortunately it does not work for me.
![](https://i.imgur.com/9reZThM.png)

**Comment by flufftronix** [comment]
This is the error I saw when trying to open the install wizard via browser without running the last install step, which contains the composer scripting that @BramDriesen mentions.

> ./docker-compose/setup.sh

The only other changes I had to make were setting the URL in docker-compose, and changing the database address in the install wizard from localhost to db

**Comment by mohitpanjwani** [comment]
There shouldn't be an issue with V4 regarding this but if you still encounter this. 

Please feel free to re-open this.

**Comment by rezzorix** [comment]
Re-Opening. Issue still persists.

**Comment by AnnoyingTechnology** [comment]
Re-opening as an install using Docker on vanilla Debian 11 produces this very error.

**Comment by bmcgonag** [comment]
Same - also seeing this using the docker install instructions on Ubuntu.   Followed instructions found here https://docs.craterapp.com/installation.html#docker-installation

**Comment by exepowered** [comment]
Same here. Tried on Debian 11 and Ubuntu 20 both using docker.
There is definitely a problem.

/var/www/vendor does not exist and could not be created

**Comment by ItsRithick** [comment]
Im having the same issue too. Any else had success with this?

**Comment by RenaissanceEngineering** [comment]
Same issue on Fedora.

**Comment by Mylezz** [comment]
same issue here!

**Comment by gokulprathin8** [comment]
same issue here!

**Comment by heyiamsven** [comment]
Same issue here!

**Comment by xoniq** [comment]
I was able to solve this (at least for me).

I changed this in `docker-compose/setup.sh`, I added `-u 0` to all commands to even the permissions:

```bash
#!/bin/sh

docker-compose exec -u 0 app composer install --no-interaction --prefer-dist --optimize-autoloader

docker-compose exec -u 0 app php artisan storage:link || true
docker-compose exec -u 0 app php artisan key:generate
```

Then in `composer.json` I missed `allow-plugins` in the `config` section. This is how it should look:

```json
  "config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "sort-packages": true,
    "allow-plugins": true
  },
```

**Comment by mortolian** [comment]
Thank you @xoniq, this worked perfectly for me as well.

**Comment by Sandroggy** [comment]
Hi,

The fix of @xoniq allowed me to reach the database step of the instalation process. But i got this error after the database step : `SQLSTATE[HY000] [1045] Access denied for user 'crater'@'172.24.0.9' (using password: YES) (SQL: select * from information_schema.tables where table_schema = crater and table_name = abilities and table_type = 'BASE TABLE')`

I did not change password or name of the db. I re try with a fresh clone of the repo but same result.

**Comment by synapsedata** [comment]
I had the same issue, i followed 2 steps,

1-Edit the setup.sh file, instead docker-compose y switched to docker compose
2-Change permission to the whol folder crater like this: $> sudo chown -R 1000:1000 crater/
3-Then, run setup.sh and continue the process

If you need more details let me know, thanks to crater-invoice team
