### ISSUE TITLE
"Database should be empty" error while setting up crater

### ISSUE THREAD

**Issue by rajsanjib** [bytefury/crater#238]
I cloned the repo, installed dependencies and ran migration. When I setup database information on http://127.0.0.1:8000/on-boarding, I got the error saying database should be empty.

![Screenshot from 2020-06-30 15-48-07](https://user-images.githubusercontent.com/10085362/86113639-3eaea280-bae9-11ea-9991-b1491bc18cfd.png)

- Crater version: 3.1.1
- PHP version: 7.4.3
- Database type and version: mysql 8.0.20

**Optional info**
- OS:  Ubuntu
- Browser:  chrome

**Comment by mohitpanjwani** [comment]
Hey! Please follow the instructions given in documentation in order for this to work. 

The onboarding wizard will not work if you've already ran the migrations. 

https://docs.craterapp.com/developer-guide.html#installation

**Comment by mrlinnth** [comment]
I have done the following today and facing same issue.

1. `git clone` the repo
2. run `composer install`
3. run `yarn`
4. run `yarn dev`
5. created database in mysql
6. updated `.env` file with db details

- visited my vhost and got following error

![image](https://user-images.githubusercontent.com/4952597/102320862-41278a80-3fab-11eb-9711-e5ca25c33574.png)

---

- run `php artisan migrate` and visited my vhost
- can reach up to "Site URL & Database" step and got following error when continue

![image](https://user-images.githubusercontent.com/4952597/102321153-a7141200-3fab-11eb-9272-170bffe7c711.png)

- Crater version : 4 (I think it is 4, I just cloned master)
- PHP version : 7.4.13
- Mysql : 8.0.22-0ubuntu0.20.04.3
- OS : Linux Mint
- Browser : Brave

**Comment by mrlinnth** [comment]
In case anyone stumbled upon this. I fixed it by 
- dropping all tables in db
- deleted storage/app/database_created file
- visit url and try again

**Comment by ronaldpatino** [comment]
> Hey! Please follow the instructions given in documentation in order for this to work.
> 
> The onboarding wizard will not work if you've already ran the migrations.
> 
> https://docs.craterapp.com/developer-guide.html#installation

Sorry, I get the same message "Database should be empty" when following developer instructions to install

**Comment by sunstep** [comment]
For anyone who is here and is looking for a solution: I also ran into this issue just now, but the solution was easy. Just rename your existing database to anything else, and create a new database. Then finish the installation wizard with the newly created database and then when you get to the dashboard, simply drop the new database and rename the old database back to what it was before.

Example if your database name is crater:
1. Rename crater to something like crater old
2. Create new database called crater
3. Finish installation with the database name crater 
4. When you get to the dashboard, drop the database crater and rename crater old to crater
5. Refresh the page and it should be using your existing database again.

**Comment by neidiom** [comment]
This fixed it for me

````
php artisan reset:app --force
````

https://github.com/crater-invoice/crater/blob/f434c3e0d1faa7a70e563595ff3f8a02777772ed/app/Console/Commands/ResetApp.php#L18
