### ISSUE TITLE
PDF cannot be viewed in php 7.4 even after the latest update(3.1.1)

### ISSUE THREAD

**Issue by Nagender17** [bytefury/crater#240]
Cannot view PDF in the latest build 3.1.1
When trying to view the invoice, it displays 500 error. I use php version 7.4 I tried to verify if this is fixed in latest release (3.1.1) but the issue still exists. Please find the attached screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/34160359/87097332-8e683900-c262-11ea-9f51-42a4ac7b564d.png)

**Please complete the following information:**
- Crater version: 3.1.1
- PHP version: 7.4
- Database type and version: mysql

**Comment by davidg246819** [comment]
Make sure you have all required PHP extensions installed. I was missing several extensions and got the same error when viewing PDF. I use a custom PHP 7.4.5 build and specifically I was missing DOM, iconv, xml reader/writer and a few others.

**Comment by susoftch** [comment]
I have also the same Error, but only when I will display a Estimation, Invoice PDF display works OK?
Same envirement

**Comment by mohitpanjwani** [comment]
@susoftch can you enable debugging by updating your .env file as mentioned below and post the screenshot of the error?

APP_DEBUG=true

**Comment by susoftch** [comment]
Hello and thanks for your fast response, here are the print-screen (is this a self generated `problem?)
![28-07-_2020_17-25-16](https://user-images.githubusercontent.com/7894914/88686932-e377cc00-d0f7-11ea-992e-9a42ccf8c845.jpg)

**Comment by mohitpanjwani** [comment]
> Hello and thanks for your fast response, here are the print-screen (is this a self generated `problem?)
> ![28-07-_2020_17-25-16](https://user-images.githubusercontent.com/7894914/88686932-e377cc00-d0f7-11ea-992e-9a42ccf8c845.jpg)

Have you made any customizations? 

`company-address.blade.php` on the latest version does not have any $invoice variable.
