### ISSUE TITLE
Cannot write configuration to .env file.

### ISSUE THREAD

**Issue by Soowarez** [bytefury/crater#241]
Hello,
Wanting to try your project, during the installation everything goes well when I have to fill in the info of the MySQL database.
Here is a screenshot of the error message in question.

![image](https://user-images.githubusercontent.com/29873403/88181043-8fb83f00-cc2e-11ea-8730-0bc7f2c62be1.png)

Thanks in advance for your help: D

**Comment by mohitpanjwani** [comment]
Hey! 

Please check the file permissions of `.env` file. It needs to be writable in order for the installation wizard to work as expected.
