### ISSUE TITLE
[PDF] 500 - Server Error

### ISSUE THREAD

**Issue by Soowarez** [bytefury/crater#247]
**Describe the bug**
Hello; 
I installed the dashboard on my vps, and noticed that the PDFs do not work (report, estimate, invoice). 

Being in Php 7.4 I decided to go back and put version 7.2 and the PDFs work again but that for the report part, for the quotes and invoice the PDF does not work. 

What to do ?

**Screenshots**
![image](https://user-images.githubusercontent.com/29873403/89170484-fcf99780-d57f-11ea-91d2-c5d82e128988.png)

**Please complete the following information:**
- Crater version: 3.1.1
- PHP version: 7.2.32
- Database type and version: MariaDB

**Optional info**
- OS:  Debian 10
- Browser: Chrome, Safari

**Comment by shahvirag** [comment]
I faced same issue:
1. check if imagick extension is configured.
2. You might need to increase time limit in particular function.

**Comment by Soowarez** [comment]
Ok, I'll test in a few minutes and get back to you

**Comment by Soowarez** [comment]
Is there no need for imagick to generate invoices and quotes? I understand why the report function is not linked with the PDF invoice and quote?

**Comment by Soowarez** [comment]
@mohitpanjwani would you tell me where is this problem coming from? Thank you
