### ISSUE TITLE
[Invoice] Company logo not Displaying.

### ISSUE THREAD

**Issue by shahvirag** [bytefury/crater#248]
**Describe the bug**
Uploaded company logo at time of on boarding process. I can find file in storage and also i see image in company setting.
But not able load company logo in invoice PDF.

**Expected behavior**
Invoice pdf must display company logo if available.

**Screenshots**
Invoice:
![crater111](https://user-images.githubusercontent.com/24240840/89182305-1d8f1500-d5b3-11ea-9591-98ad51f219c0.PNG)

Company Profile
![crater111](https://user-images.githubusercontent.com/24240840/89182706-ce95af80-d5b3-11ea-80d4-cd54ba401cf4.PNG)

**Please complete the following information:**
- Crater version: 3.1.1
- PHP version: 7.4.7
- Database type and version: MYSQL 5.7

**Optional info**
- OS:  Windows 10
- Browser: chrome, brave

**Comment by tjimenez** [comment]
Seems like It happens when the image is uploading through the UI. If you browse and replace the image manually with the original one works again.

**Comment by shahvirag** [comment]
I already dig into it and its related tp laravel-pdf plugin.
If you deploy code on public domain then it will work.
On local its not working...

**Comment by tjimenez** [comment]
@shahvirag I did it in production. I had to overwrite the image in the storage folder without uploading it via web app. Somewhere in the uploading process, images get corrupted

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please reopen this issue if you still encounter this after updating.

**Comment by azaricstefan** [comment]
4.0.1 resolves issue for me.
