### ISSUE TITLE
New Jersey and "New Jersy" States are not working

### ISSUE THREAD

**Issue by phoopee3** [bytefury/crater#25]
When I select "New Jersey" the town list is empty. I noticed after updating to 1.1.0 that "New Jersy" is an option, but my town was not listed. Maybe related to the other open issue of the "off by one"

**Comment by mohitpanjwani** [comment]
Closing this issue as it's fixed in 2.0 update.  We've replaced the state & city selectors with text inputs. 

More discussion on: https://github.com/bytefury/crater/issues/13
