### ISSUE TITLE
Avatar Logo not display

### ISSUE THREAD

**Issue by khinsen1** [bytefury/crater#251]
**Describe the bug**
I using another computer to access Crater(hosted in another server). I upload my avatar in user profile and save it. I refresh the page. The avatar is not display. I check Chrome Console and found "Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:8080/storage/11/bizxe_logo.png with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details."
I tried on Edge and other explorer also hit the same problem.

**Expected behavior**
The avatar should display correctly in user profile page and on top right screen. Currently it didnt display in user profile and top right screen.

**Screenshots**

**Please complete the following information:**
I run from docker that I download/install base on steps found at https://docs.craterapp.com/installation.html#docker-installation
- Crater version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  Windows 10
- Browser: chrome, Microsoft Edge, Firefox.

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please update your app from Settings -> Update App to get the new changes.
