### ISSUE TITLE
Show record_payment after clicking mark_as_sent

### ISSUE THREAD

**Issue by RobinDev** [bytefury/crater#252]
When we click "Mark As Sent", the UI may show us the "Record Payment" button on invoice view.

I try a small hack in `/resources/assets/js/views/invoices/View.vue`
(but I never use vue).

by adding `this.loadInvoice()` in `onMarkAsSent`.

The job is done, but maybe there is a cleaner way to do it ?!

Thanks for your job.

**Comment by mohitpanjwani** [comment]
This is fixed in V4.
