### ISSUE TITLE
Decimals for quantities in invoices works... Only with numbers higher than 1.

### ISSUE THREAD

**Issue by jpmurray** [bytefury/crater#255]
**Describe the bug**
Currently, I can enter decimales for quantity in invoices. For example, I can easily bill for `1.75` hours. But the validation makes it impossible to submit changes / accept anything that's _less_ than 1, for example, I can't bill half and hour(`0.5` hours).

**Expected behavior**
Since decimals are accepted with numbers >= 1, I could expect it to accept >= 0.

**Please complete the following information:**
- Crater version: 3.1.1 
- PHP version: 7.4
- Database type and version: Not sure at the moment, using Docker's setup.

**Comment by mohitpanjwani** [comment]
Fixed in V4 (https://github.com/bytefury/crater/releases/tag/4.0.0)
