### ISSUE TITLE
What is the process for updating to the latest version?

### ISSUE THREAD

**Issue by roberto-co** [bytefury/crater#256]
**Describe the bug**
Hello how do you update to the latest version with out deleting your existing database? or overwriting the data in the database?

**Comment by mohitpanjwani** [comment]
The Self Updater does not overwrite or delete existing data. 

But its recommended to take a backup before updating. Just to be safe.

**Comment by roberto-co** [comment]
Where is the self updater? I didn't see it.

**Comment by mohitpanjwani** [comment]
You can find it in Settings page/
