### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by roberto-co** [bytefury/crater#257]
**Describe the bug**
When clicking the Update app via the settings options i get the error: "Error Migrating Step"
**Expected behavior**
When doing this it should update the application?
**Screenshots**
![image](https://user-images.githubusercontent.com/48658885/90337695-c2ddbc00-dfa9-11ea-938e-b1384ba0c4a0.png)

**Please complete the following information:**
- Crater version: 3.0.0
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu] Ubuntu
- Browser: [e.g. chrome, safari] chrome

**Comment by roberto-co** [comment]
Is there a way maybe i can clone the latest and import the database data?

**Comment by mohitpanjwani** [comment]
Hi @roberto-co, The migrate command failed on your server for some reason. 

Its hard to debug the cause of this issue, but if you take a backup of your db and try to update again after setting APP_DEBUG=true then we can find what’s causing it. 

Also I will be adding instructions to update the app manually in documentation.

**Comment by roberto-co** [comment]
Where is the APP_DEBUG variable set?

**Comment by mohitpanjwani** [comment]
In the .env file

**Comment by roberto-co** [comment]
Okay, I will set it now and see what it logs. I am seeing some strange behavirour after the failure of the update. Now the totals dont show up fully on the page:

![image](https://user-images.githubusercontent.com/48658885/91251444-175b0700-e721-11ea-9f85-02875b11723d.png)

**Comment by roberto-co** [comment]
I have an .env.example but no .env file

![image](https://user-images.githubusercontent.com/48658885/91251691-98b29980-e721-11ea-83d4-a8c89e93b1dd.png)

**Comment by mohitpanjwani** [comment]
I think it’s because your app files got replaced with new ones but the migrations didn’t run. 

What happens if you run “php artisan migrate” in the console?

**Comment by mohitpanjwani** [comment]
> I have an .env.example but no .env file
> 
> ![image](https://user-images.githubusercontent.com/48658885/91251691-98b29980-e721-11ea-83d4-a8c89e93b1dd.png)

It must be hidden. Try doing “nano .env”

**Comment by roberto-co** [comment]
No luck, the file is just not present. If i do nano .env it opens a new empty file.

**Comment by roberto-co** [comment]
What you said makes sense, it must've overwritten files:

![image](https://user-images.githubusercontent.com/48658885/91252295-f09dd000-e722-11ea-80a5-ec31cc744ee4.png)

**Comment by roberto-co** [comment]
I installed required packages:

Results of the command.

![image](https://user-images.githubusercontent.com/48658885/91252514-5b4f0b80-e723-11ea-94fe-7357e4d5b94d.png)

**Comment by roberto-co** [comment]
Could you provide the manual steps to update and I will test it out to make sure it works?

**Comment by mohitpanjwani** [comment]
@roberto-co Hey, I don't understand how your current setup works without an `.env` file because the database configuration and many things get set on `.env` file when you finish the onboarding wizard. 

How did you install crater? By downloading the zip file or by cloning this repository?

**Comment by roberto-co** [comment]
Hi I downloaded the docker image and used that to install.

On Aug 27, 2020 7:16 AM, Mohit Panjwani <notifications@github.com> wrote:

@roberto-co<https://github.com/roberto-co> Hey, I don't understand how your current setup works without an .env file because the database configuration and many things get set on .env file when you finish the onboarding wizard.

How did you install crater? By downloading the zip file or by cloning this repository?

**Comment by roberto-co** [comment]
Hi Mohit,

Is it a good idea to:

Take a backup of the existing image. 
Recover the backup i took before doing the update, and take the .env out 
Recover the messed up image, since i took a backup in step 1.
Drop the .env file into the messed up install the one where the pdf's are not showing up correctly anymore.?

Thanks,

**Comment by roberto-co** [comment]
I cannot even find the .env in an old snapshot of the machine.
I do see .env.example but nothing with just .env

**Comment by mohitpanjwani** [comment]
Hi @roberto-co The docker setup requires you to copy the `env.example` file to `.env` first otherwise it won't work as expected. 

To be honest, I'm not even sure how your app worked without an env :) 

I would suggest to take a backup of your current database and then do a fresh git clone of the latest repository and follow the steps properly as mentioned: https://docs.craterapp.com/installation.html#docker-installation

Once your new app is working, you can replace the database with your old one and then run the migrations: 
`php artisan migrate`

If you face any issues, please let me know here.

**Comment by roberto-co** [comment]
Hi Mohit,

Ive been doing what you said but im stuck…I cloned the repo but how is it hosted? Does it use Express using node? Or do I need to download apache? I didn’t see this part in the instructions.

Thanks,

**Comment by roberto-co** [comment]
Hi Mohi,

I installed apache and pointed the root to the /home/crater/crater/public folder and this is what i show when i visit the apache server:


![image](https://user-images.githubusercontent.com/48658885/92333162-0aa3b080-f049-11ea-8f07-61d6587c7512.png)


Did i do something wrong?

**Comment by roberto-co** [comment]
I just used docker to install again. I'll be on the look out for the manual way of updating. I'll just recreate the customers and invoices from the non working Crater.
We can close this out.
Thanks,

**Comment by mohitpanjwani** [comment]
Glad to know that you were able to install it again @roberto-co. 

The manual update is a bit complicated, we are looking into simplifying that process.
