### ISSUE TITLE
Company logo not Displaying in live server.

### ISSUE THREAD

**Issue by Vinya007** [bytefury/crater#258]
**Describe the bug**
Uploaded company logo than I can find file in storage and also i see image in company setting.
But not able load company logo on live server but in local it's fine.

**Expected behavior**
Invoice pdf must show company logo if available.

**Screenshots**
![with_image](https://user-images.githubusercontent.com/45792827/90371301-643d3e80-e08c-11ea-969a-c1bcf2513429.png)
![with_out_image](https://user-images.githubusercontent.com/45792827/90371302-656e6b80-e08c-11ea-98d1-ed24fc0bda10.png)

**Please complete the following information:**
- Crater version: 3.1.1 
- PHP version: 7.3.12
- Database type and version:  10.4.10-MariaDB

**Optional info**
- OS:  Windows 10
- Browser: chrome

**Comment by azaricstefan** [comment]
@mohitpanjwani do you know why is this happening?

I am having the same issue, I tried PNG, JPG it just shows this.
"Company Logo Image not found or type unknown"
![image](https://user-images.githubusercontent.com/9116773/101288356-6f140e80-37f6-11eb-83fa-154bf9e00e1f.png)

**Comment by sylvaindumont** [comment]
I had the same issue, fixed it by running `php artisan storage:link`

**Comment by azaricstefan** [comment]
That part is executed in the setup.sh script as I remember, just executed it again now. 
"The [/var/www/public/storage] link already exists.
The links have been created."
It still shows the same in my case.

**Comment by mohitpanjwani** [comment]
Hey @azaricstefan, Thanks for the feedback. 

We're reviewing this now.

**Comment by azaricstefan** [comment]
**Important note**:
In emails for Invoices, Estimates and Payments logo does show.

It doesn't show in actual Invoices, Estimates and Payments.

**Comment by azaricstefan** [comment]
This issue is related to this one #248 . Take investigation from there into account.

**Comment by azaricstefan** [comment]
4.0.1 resolves issue for me.

**Comment by mohitpanjwani** [comment]
This issue is fixed on 4.0.1
