### ISSUE TITLE
Timezone of settings doesn't work

### ISSUE THREAD

**Issue by nighon** [bytefury/crater#259]
Hello, I have found that the timezone of company's settings doesn't work.

The method `handle` (in app/Http/Middleware/ConfigMiddleware.php) loaded after Laravel's LoadConfiguration:

in vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\LoadConfiguration.php

    public function bootstrap(Application $app)
    {
        // ...
        date_default_timezone_set($config->get('app.timezone', 'UTC'));
    }

in app\Http\Middleware\ConfigMiddleware.php

    public function handle($request, Closure $next)
    {
        if (\Storage::disk('local')->has('installed')) {
            $setting = CompanySetting::getSetting('time_zone', $request->header('company'));
            $timezone = config('app.timezone');
            if ($setting && $setting != null && $setting != $timezone) {
                config(['app.timezone' => $setting]);
            }
        }

        return $next($request);
    }

So, there is no chance to run date_default_timezone_set after timezone config changed.

**Comment by mohitpanjwani** [comment]
@nighon I think you are right. 

I'm looking into it.

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1
