### ISSUE TITLE
Quantity has to be a whole number?

### ISSUE THREAD

**Issue by phoopee3** [bytefury/crater#26]
I was planning on using this for invoicing clients, but when I went to make a new invoice I noticed the quantity has to be a whole number. I bill in 15 minute increments, so 3.25 hours or something like that, and then would put my hourly rate in the price box to get the total.

Should I consider making the code adjustments myself or is this something you're aware of?

**Comment by vbezruchkin** [comment]
Hi,

The same request here. I'm using the software to bill services. It would be great have _hrs_ as unit, and allow to have decimal values.

**Comment by mohitpanjwani** [comment]
Hey guys, thanks for letting us know about the issue. 

This issue has been fixed! We're going to release an update today evening which will contain the fix for the above issue as well.

You can use the auto-update feature to update your web app as soon as it's released.

**Comment by vbezruchkin** [comment]
Thanks. We will be waiting for it. 

Not sure how auto update works though :) Will check the manual.

**Comment by vbezruchkin** [comment]
Applied 2.0 update. Thanks. This works fine for my installation.

**Comment by mohitpanjwani** [comment]
Closing this now as it's fixed in 2.0 update.

**Comment by jpmurray** [comment]
@mohitpanjwani 

Not reopening a new issue, but I just installed from the master branch and trying to create a new invoice, I enter a number who's not a whole number (ex: I want to charge for half an hour, so I enter 0.5)... Total is calculated correctly, but the form won't submit because the quantity validation seems to fail (field is red unless it's a number greater than zero.)

**Comment by digipifini** [comment]
I am using 6.0.6 and this issue seems to still be there. Not sure why it had been previously closed but big issue if you want people to use this software.
