### ISSUE TITLE
The character limit for the "Notes" field is too small

### ISSUE THREAD

**Issue by tobidwest** [bytefury/crater#264]
When creating an invoice, there is a limit of 255 characters for the "Notes" field. However, this is not enough, for example when you need to specify your bank account in it and mention you do not have to pay certain taxes.

Please raise the limit in the next update or tell me where in the code I can change this myself.

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please update your app from Settings -> Update App to get the new changes.
