### ISSUE TITLE
NL Translation not working

### ISSUE THREAD

**Issue by jrooijakkers** [bytefury/crater#265]
This is when i switch to Dutch translation
![Screenshot from 2020-09-09 00-38-22](https://user-images.githubusercontent.com/56171164/92534341-cb39b780-f234-11ea-8128-42a0a6ef59dd.png)

**Comment by mohitpanjwani** [comment]
This issue happens because the current public files are outdated. I've just committed new public files so others don't get the same issue. 

You can pull the changes or you can run the following 2 commands to generate build: 
- npm install
- npm run production
