### ISSUE TITLE
[Bug + step to fix] PDF Generation fails in PHP 7.4

### ISSUE THREAD

**Issue by jpmurray** [bytefury/crater#268]
**Describe the bug**
Trying to view / generate any PDF will fail under PHP 7.4, throwing a 500 error.

**Expected behavior**
I should be seeing / downloading a PDF.

**Here is the solution**
Bumping the `barryvdh/laravel-dompdf` package minimum required version to `^0.8.4` fixes the problem, as it was related to this package and the maintainer fixed the problem starting at this version.

I'm sorry I couldn't send a PR for this, I'm not around my work computer ;-)

**Comment by mohitpanjwani** [comment]
Closing this issue as I cannot reproduce this on the latest version. 

If this still happens, please re-open the issue :)

**Comment by jpmurray** [comment]
If you've updated dependencies in the latest version, that's definitely fixed! 👍
