### ISSUE TITLE
Receive 500 server error when trying to access public folder for initial setup.

### ISSUE THREAD

**Issue by tsosat** [bytefury/crater#269]
Receive 500 server error when trying to access public folder for initial setup.

**Expected behavior**
Show something more specific so I can handle any misconfiguration or missing components

**Please complete the following information:**
- Crater version: 3.1.1
- PHP version: 7.2, 7.3, 7.4
- Database type and version: N/A (didn't get that far)

**Optional info**
- OS: CENT OS 7.8
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Please install the latest version (v4) and let me know if you still encounter this issue.
