### ISSUE TITLE
PDF template does not consider discount type

### ISSUE THREAD

**Issue by vbezruchkin** [bytefury/crater#27]
Hi,

Thanks for the product. 

You can create fixed / percentage discount type. No matter what you choose, PDF template shows % there.

**Comment by jacurtis** [comment]
I came here to open the exact same issue.

Here is a picture of the invoice, to hopefully clarify the issue.

![image](https://user-images.githubusercontent.com/537329/70733999-a07ffa00-1cc8-11ea-8963-dccf4862c455.png)

I applied a discount on this invoice in the amount of $17.70. It calculates it correctly, but the PDF invoice shows that the discount is 17.7%. Again, it calculates correctly, so it is purely visual.

**Comment by vbezruchkin** [comment]
yeah, the calculations are ok but visuals are still confusing.

And another thing. 

Trying to get property 'name' of non-object in template #1. Looks like it's related to billing address being empty. In this case name should be required for billing, or just process it correctly, I guess.

Thanks

**Comment by mohitpanjwani** [comment]
This issue should be fixed in the latest update. You can download the update automatically from the settings page.

I'm closing this issue but you can re-open it if it still happens.
