### ISSUE TITLE
500 Server Error Upon Upload

### ISSUE THREAD

**Issue by nickpuglisi** [bytefury/crater#276]
Hello! I did a Manual Upload of the entire Crater folder to my server, including pointing the domain to the /public/ folder. As soon as I hit that step, I get a formatted 500 Server Error Message. 

Running Crater 3.1.1
PHP 7.2 (and all included extensions)
Running on Dreamhost Shared Hosting

Any ideas?

**Comment by mohitpanjwani** [comment]
Hello @nickpuglisi,

Please enable debugging by editing your `.env` file and change below variables in order to see the actual error: 
APP_DEBUG=true
