### ISSUE TITLE
PDF No Longer Loading - 504 Error

### ISSUE THREAD

**Issue by nickpuglisi** [bytefury/crater#277]
**Describe the bug**
Fresh download of Crater. It generated the PDF fine until I sent it via e-mail, once sent the system now shows a 504 error and times out when viewing the PDF from the e-mailed link and/or from the Admin Console.

**Expected behavior**
Be able to view an estimate/invoice PDF in the system.

**Screenshots**

**Please complete the following information:**
- Crater version: Latest 3.1.1
- PHP version: 7.4
- Database type and version: MySQL (idk version)

**Optional info**
- OS:  Ubuntu
- Browser: All
![Screen Shot 2020-10-11 at 4 18 19 PM](https://user-images.githubusercontent.com/41458625/95689253-68de2900-0bdd-11eb-83fb-543446b1eef1.png)

**Comment by mohitpanjwani** [comment]
This issue should be fixed on Crater v4. 

Please reopen if this still happens.
