### ISSUE TITLE
SKU for Item/Product ?

### ISSUE THREAD

**Issue by abhiburk** [bytefury/crater#279]
Can we add a new feature in Item or Product Page called Stock Keeping Unit to uniquely identify the product.

**Comment by mohitpanjwani** [comment]
Now you can use the Custom Fields feature on `v4` for this.

**Comment by imchivaa** [comment]
Hi, even in the v4, there is no way to add custom fields to item page.
![custom-field](https://user-images.githubusercontent.com/5532832/125422795-430f054d-9b15-41ea-be34-4a0488c4e0a2.png)
