### ISSUE TITLE
Target class [App\Http\Middleware\Authenticate] does not exist.

### ISSUE THREAD

**Issue by robbietorinit** [bytefury/crater#28]
When trying to login it gives me the following error:

{message: "Target class [App\Http\Middleware\Authenticate] does not exist.",…}
exception: "Illuminate\Contracts\Container\BindingResolutionException"
file: "/var/www/html/crater/vendor/laravel/framework/src/Illuminate/Container/Container.php"
line: 806
message: "Target class [App\Http\Middleware\Authenticate] does not exist

**Comment by mohitpanjwani** [comment]
Please mention your php version, OS & mysql version. It seems to work as expected here..
