### ISSUE TITLE
Cannot add payment methods "Credit Card" and "Bank Transfer"

### ISSUE THREAD

**Issue by bomboem** [bytefury/crater#280]
**Describe the bug**
I cannot add the payment methods "Bank Transfer" and "Credit Card". My Payments list is empty, I have no payments available and when I try to add a payment method called "Bank Transfer", it displays that this name is already taken and that such a payment method already exists. Same scenario when I try to create a Payment method for "Credit Card".

**Expected behavior**
To be able to add and use payment methods named "Bank Transfer" and "Credit Card" and for them to be visible in the Payments overview.

**Screenshots**

![PAYMENT METHOD;png](https://user-images.githubusercontent.com/23366362/96438456-c63e2f80-1206-11eb-90a9-52e4913aa830.PNG)

**Please complete the following information:**
- Crater version: Crater v. 3.1.1
- PHP version: 7.2.32
- Database type and version: 10.4.14-MariaDB

**Optional info**
- OS: Windows 10 Home running XAMPP
- Browser: FireFox, Chrome and Edge.

**Comment by mohitpanjwani** [comment]
This should no longer be an issue in V4. 

Please re-open if you still encounter this after updating.
