### ISSUE TITLE
Allow more than 255 characters for article description and invoice notes

### ISSUE THREAD

**Issue by q-bic** [bytefury/crater#287]
It would be really nice, if the article description and invoice notes allow more than 255 characters, because in my case the 255 characters are not enough sometimes.
If you want I can have a look at it myself and create a pull request for the changes ...

**Comment by nikkoentena** [comment]
you can increase the character limit by modifying the .vue files located in crater\resources\assets\js\views. for example, i modified the create.vue file for item  which is located at crater\resources\assets\js\views\items and change the validation part of the code..

  validations: {
    formData: {
      name: {
        required,
        minLength: minLength(3),
      },

      price: {
        required,
        numeric,
        maxLength: maxLength(20),
        minValue: minValue(0.1),
      },

      description: {
        **maxLength: maxLength(255),**  ----change it to -- >    **maxLength: maxLength(65535),**
      },
    },
  },


to reflect the changes. you need to recompile the app using  'yarn run production' command  (assuming you've already setup a working environment for crater before) 

then do  php artisan view:clear


there's no character limit for the notes. but the notes cuts off after 253 character when generating a pdf. still looking for a way to modified it

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please update your app from Settings -> Update App to get the new changes.
