### ISSUE TITLE
4.0.0 can't run npm run dev

### ISSUE THREAD

**Issue by azaricstefan** [bytefury/crater#290]
**Describe the bug**
I am trying to fix translation for one of the languages which are missing in the 4.0.0. (Serbian).
By trying to do that after upgrade to 4.0.0 this is not working anymore.
I tried both with existing project and totaly new (git cloned from here).

**Expected behavior**
There are no errors when running npm run dev.

**Please complete the following information:**
- Crater version: 4.0.0
- PHP version: 7.4.9
- Database type and version:  mariadb
- Docker default setup

Console output:

```
npm run dev

> @ dev /Users/Crater/Crater
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 17 errors

These dependencies were not found:

* /Users/Crater/Crater/resources/assets/sass/crater.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
* flatpickr/dist/flatpickr.css in ./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save /Users/Crater/Crater/resources/assets/sass/crater.scss flatpickr/dist/flatpickr.css


These relative modules were not found:

* ./WizardUserProfileStep.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/views/wizard/WizardUserProfileStep.vue
* ./Create.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/views/invoices/Create.vue, ./resources/assets/js/views/estimates/Create.vue
* ./Index.vue?vue&type=style&index=0&id=66c9f590&scoped=true&lang=css& in ./resources/assets/js/views/reports/layout/Index.vue
* ./TheSiteHeader.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/views/layouts/partials/TheSiteHeader.vue
* ./BaseLoader.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/BaseLoader.vue
* ./NoteModal.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/modal/NoteModal.vue
* ./LayoutLogin.vue?vue&type=style&index=0&id=6b516654&lang=scss&scoped=true& in ./resources/assets/js/views/layouts/LayoutLogin.vue
* ./LineChart.vue?vue&type=style&index=0&id=f00ab88a&scoped=true&lang=css& in ./resources/assets/js/components/chartjs/LineChart.vue
* ./DotIcon.vue?vue&type=style&index=0&lang=css& in ./resources/assets/js/components/icon/DotIcon.vue
* ./GlobalSearch.vue?vue&type=style&index=0&id=166b593c&scoped=true&lang=css& in ./resources/assets/js/components/GlobalSearch.vue
* ./BaseDatePicker.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/BaseDatePicker.vue
* ./CustomerSelectPopup.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/popup/CustomerSelectPopup.vue
* ./SweetModal.vue?vue&type=style&index=0&lang=scss& in ./node_modules/sweet-modal-vue/src/components/SweetModal.vue
* ./SwSelect.vue?vue&type=style&index=0&lang=scss& in ./node_modules/@bytefury/spacewind/src/components/sw-select/SwSelect.vue
                Asset      Size          Chunks                   Chunk Names
    /assets/js/app.js  10.6 MiB  /assets/js/app  [emitted]        /assets/js/app
/assets/js/app.js.map    11 MiB  /assets/js/app  [emitted] [dev]  /assets/js/app

ERROR in ./resources/assets/js/views/wizard/WizardUserProfileStep.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/views/wizard/WizardUserProfileStep.vue 4:0-82
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/wizard/Wizard.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/wizard/Wizard.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/wizard/Wizard.vue
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss /assets/js/app[1]

ERROR in ./resources/assets/js/views/invoices/Create.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/views/invoices/Create.vue 4:0-67
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/views/estimates/Create.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/views/estimates/Create.vue 4:0-67
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/views/reports/layout/Index.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/views/reports/layout/Index.vue 4:0-89
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/views/layouts/partials/TheSiteHeader.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/views/layouts/partials/TheSiteHeader.vue 4:0-74
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/layouts/LayoutBasic.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/layouts/LayoutBasic.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/layouts/LayoutBasic.vue
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/base/BaseLoader.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/base/BaseLoader.vue 4:0-71
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/settings/UserProfileSetting.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/settings/UserProfileSetting.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/settings/UserProfileSetting.vue
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/base/modal/NoteModal.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/base/modal/NoteModal.vue 4:0-70
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/components/base/modal/BaseModal.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/components/base/modal/BaseModal.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/components/base/modal/BaseModal.vue
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/views/layouts/LayoutLogin.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/views/layouts/LayoutLogin.vue 3:0-96
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/chartjs/LineChart.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/chartjs/LineChart.vue 4:0-93
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/DashboardChart.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/Dashboard.vue
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/icon/DotIcon.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/icon/DotIcon.vue 4:0-67
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/GlobalSearch.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/GlobalSearch.vue 4:0-96
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/base/BaseDatePicker.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/base/BaseDatePicker.vue 4:0-75
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./resources/assets/js/components/base/popup/CustomerSelectPopup.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./resources/assets/js/components/base/popup/CustomerSelectPopup.vue 4:0-80
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./node_modules/sweet-modal-vue/src/components/SweetModal.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./node_modules/sweet-modal-vue/src/components/SweetModal.vue 4:0-71
 @ ./node_modules/sweet-modal-vue/src/main.js
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/DashboardChart.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/views/dashboard/Dashboard.vue
 @ ./resources/assets/js/router.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&) 29:0-37
 @ ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&
 @ ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/components/base/BaseTimePicker.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/components/base/BaseTimePicker.vue?vue&type=script&lang=js&
 @ ./resources/assets/js/components/base/BaseTimePicker.vue
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss

ERROR in ./node_modules/@bytefury/spacewind/src/components/sw-select/SwSelect.vue
Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
 @ ./node_modules/@bytefury/spacewind/src/components/sw-select/SwSelect.vue 4:0-69
 @ ./node_modules/@bytefury/spacewind/src/components/sw-select/index.js
 @ ./resources/assets/js/components/base/index.js
 @ ./resources/assets/js/bootstrap.js
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by IvanAquino** [comment]
i had the same problem, use yarn install instead of npm install, and yarn production or yarn watch to compile

**Comment by mohitpanjwani** [comment]
> i had the same problem, use yarn install instead of npm install, and yarn production or yarn watch to compile

There are some weird issues with purgecss plus tailwind on Laravel mix.

Please use yarn as @IvanAquino suggested.

**Comment by mohitpanjwani** [comment]
> **Describe the bug**
> I am trying to fix translation for one of the languages which are missing in the 4.0.0. (Serbian).
> By trying to do that after upgrade to 4.0.0 this is not working anymore.
> I tried both with existing project and totaly new (git cloned from here).
> 
> **Expected behavior**
> There are no errors when running npm run dev.
> 
> **Please complete the following information:**
> 
> * Crater version: 4.0.0
> * PHP version: 7.4.9
> * Database type and version:  mariadb
> * Docker default setup
> 
> Console output:
> 
> ```
> npm run dev
> 
> > @ dev /Users/Crater/Crater
> > cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> 98% after emitting SizeLimitsPlugin
> 
>  ERROR  Failed to compile with 17 errors
> 
> These dependencies were not found:
> 
> * /Users/Crater/Crater/resources/assets/sass/crater.scss in multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> * flatpickr/dist/flatpickr.css in ./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&
> 
> To install them, you can run: npm install --save /Users/Crater/Crater/resources/assets/sass/crater.scss flatpickr/dist/flatpickr.css
> 
> 
> These relative modules were not found:
> 
> * ./WizardUserProfileStep.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/views/wizard/WizardUserProfileStep.vue
> * ./Create.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/views/invoices/Create.vue, ./resources/assets/js/views/estimates/Create.vue
> * ./Index.vue?vue&type=style&index=0&id=66c9f590&scoped=true&lang=css& in ./resources/assets/js/views/reports/layout/Index.vue
> * ./TheSiteHeader.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/views/layouts/partials/TheSiteHeader.vue
> * ./BaseLoader.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/BaseLoader.vue
> * ./NoteModal.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/modal/NoteModal.vue
> * ./LayoutLogin.vue?vue&type=style&index=0&id=6b516654&lang=scss&scoped=true& in ./resources/assets/js/views/layouts/LayoutLogin.vue
> * ./LineChart.vue?vue&type=style&index=0&id=f00ab88a&scoped=true&lang=css& in ./resources/assets/js/components/chartjs/LineChart.vue
> * ./DotIcon.vue?vue&type=style&index=0&lang=css& in ./resources/assets/js/components/icon/DotIcon.vue
> * ./GlobalSearch.vue?vue&type=style&index=0&id=166b593c&scoped=true&lang=css& in ./resources/assets/js/components/GlobalSearch.vue
> * ./BaseDatePicker.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/BaseDatePicker.vue
> * ./CustomerSelectPopup.vue?vue&type=style&index=0&lang=scss& in ./resources/assets/js/components/base/popup/CustomerSelectPopup.vue
> * ./SweetModal.vue?vue&type=style&index=0&lang=scss& in ./node_modules/sweet-modal-vue/src/components/SweetModal.vue
> * ./SwSelect.vue?vue&type=style&index=0&lang=scss& in ./node_modules/@bytefury/spacewind/src/components/sw-select/SwSelect.vue
>                 Asset      Size          Chunks                   Chunk Names
>     /assets/js/app.js  10.6 MiB  /assets/js/app  [emitted]        /assets/js/app
> /assets/js/app.js.map    11 MiB  /assets/js/app  [emitted] [dev]  /assets/js/app
> 
> ERROR in ./resources/assets/js/views/wizard/WizardUserProfileStep.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/views/wizard/WizardUserProfileStep.vue 4:0-82
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/wizard/Wizard.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/wizard/Wizard.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/wizard/Wizard.vue
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss /assets/js/app[1]
> 
> ERROR in ./resources/assets/js/views/invoices/Create.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/views/invoices/Create.vue 4:0-67
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/views/estimates/Create.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/views/estimates/Create.vue 4:0-67
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/views/reports/layout/Index.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/views/reports/layout/Index.vue 4:0-89
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/views/layouts/partials/TheSiteHeader.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/views/layouts/partials/TheSiteHeader.vue 4:0-74
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/layouts/LayoutBasic.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/layouts/LayoutBasic.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/layouts/LayoutBasic.vue
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/base/BaseLoader.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/base/BaseLoader.vue 4:0-71
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/settings/UserProfileSetting.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/settings/UserProfileSetting.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/settings/UserProfileSetting.vue
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/base/modal/NoteModal.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/base/modal/NoteModal.vue 4:0-70
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/components/base/modal/BaseModal.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/components/base/modal/BaseModal.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/components/base/modal/BaseModal.vue
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/views/layouts/LayoutLogin.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/views/layouts/LayoutLogin.vue 3:0-96
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/chartjs/LineChart.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/chartjs/LineChart.vue 4:0-93
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/DashboardChart.vue
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/Dashboard.vue
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/icon/DotIcon.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/icon/DotIcon.vue 4:0-67
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/GlobalSearch.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/GlobalSearch.vue 4:0-96
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/base/BaseDatePicker.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/base/BaseDatePicker.vue 4:0-75
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./resources/assets/js/components/base/popup/CustomerSelectPopup.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./resources/assets/js/components/base/popup/CustomerSelectPopup.vue 4:0-80
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./node_modules/sweet-modal-vue/src/components/SweetModal.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./node_modules/sweet-modal-vue/src/components/SweetModal.vue 4:0-71
>  @ ./node_modules/sweet-modal-vue/src/main.js
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/DashboardChart.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/DashboardChart.vue
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/views/dashboard/Dashboard.vue
>  @ ./resources/assets/js/router.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&)
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&) 29:0-37
>  @ ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue?vue&type=script&lang=js&
>  @ ./node_modules/@bytefury/spacewind/src/components/SwDatePicker.vue
>  @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/components/base/BaseTimePicker.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/components/base/BaseTimePicker.vue?vue&type=script&lang=js&
>  @ ./resources/assets/js/components/base/BaseTimePicker.vue
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> 
> ERROR in ./node_modules/@bytefury/spacewind/src/components/sw-select/SwSelect.vue
> Module not found: Error: Can't resolve 'css-loader' in '/Users/Crater/Crater'
>  @ ./node_modules/@bytefury/spacewind/src/components/sw-select/SwSelect.vue 4:0-69
>  @ ./node_modules/@bytefury/spacewind/src/components/sw-select/index.js
>  @ ./resources/assets/js/components/base/index.js
>  @ ./resources/assets/js/bootstrap.js
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/crater.scss
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the @ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ```

Btw I completely missed the Serbian language.

Can you please add a PR for it when you get the time? 

Thank you for letting us know btw 👍

**Comment by azaricstefan** [comment]
Thanks for swift reply, much appreciated! @IvanAquino 
I will add a PR to add it again soon. 👍 @mohitpanjwani

**Comment by azaricstefan** [comment]
@mohitpanjwani Shall we have this issue open for awareness regarding npm being broken at the time being?

**Comment by mohitpanjwani** [comment]
> @mohitpanjwani Shall we have this issue open for awareness regarding npm being broken at the time being?

Sure thing! Let's keep this open until its fixed 👌

**Comment by betinhosampler** [comment]
Eu aqui novamente srsrsr, o erro do login resolvi assim, veja https://github.com/bytefury/crater/issues/300

**Comment by mohitpanjwani** [comment]
Closing this as its no longer an issue 👍
