### ISSUE TITLE
Unable to reset password after upgrading to 4.0

### ISSUE THREAD

**Issue by LarryBarker** [bytefury/crater#291]
**Describe the bug**
Receiving an error that the POST method is not supported for the forgot password route. Looks like it is posting to the `is-registered` endpoint.

**Expected behavior**
Should be able to reset password via email.

**Screenshots**
![image](https://user-images.githubusercontent.com/28734844/101234559-1aea1c80-3686-11eb-8fd0-d89fa5c34f0f.png)

**Please complete the following information:**
- Crater version: 4.0
- PHP version: 7.4.8
- Database type and version: Mysql 5.7

**Optional info**
I'm almost certain I'm using the correct password when logging in (I'm running this locally so I don't use a complex password). When I try to login, I get this:
![image](https://user-images.githubusercontent.com/28734844/101234638-af547f00-3686-11eb-9c79-0dc455daaee4.png)

And when I use a completely random password I know is not possibly correct, I get this:
![image](https://user-images.githubusercontent.com/28734844/101234670-f93d6500-3686-11eb-9595-36a5d2944365.png)

**Comment by LarryBarker** [comment]
Ok, so I was just able to sign in. I compared the `.env.example` to the updates I made based on the upgrade guide, and noticed the `SESSION_LIFETIME` is set to `120` in the upgrade guide.

The `.env.example` shows `1440` so I changed that and it let me in. I believe there may be a typo in the upgrade guide? But why does 120 not work?

**Comment by MakerLab-Dev** [comment]
Regarding the password reset issue, have a look at #288

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please update your app from Settings -> Update App to get the new changes.
