### ISSUE TITLE
v4 - Reports/Sales select This Quarter 500 - Server Error

### ISSUE THREAD

**Issue by azaricstefan** [bytefury/crater#293]
**Describe the bug**

Go to: Reports
Choose: Sales (it applies to any report)
Select: This Quarter
You will get: 500 - Server Error

**Workaround**

Set dates manually.

**Expected behavior**
It generates a report.

**Please complete the following information:**
- Crater version: 4.0.0
- PHP version: 7.4.6
- Database type and version: MariaDB (from docker)

**Optional info**
- OS:  [e.g. Ubuntu] MacOS
- Browser: [e.g. chrome, safari] Edge and Chrome

**Comment by mohitpanjwani** [comment]
This issue has been fixed. I'll create a minor update to fix this tomorrow together with other bug-fixes.

**Comment by azaricstefan** [comment]
Awesome, great to hear that! 😊

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please update your app from Settings -> Update App to get the new changes.
