### ISSUE TITLE
mix the assets

### ISSUE THREAD

**Issue by jameel-fullstackdeveloper** [bytefury/crater#296]
unable to run the following commands to mix the laravel assets

npm run watch
npm run dev

I run the following command on the root ( it was working perfect on the last version but not working on 4.x)
npm i
npm run watch

**Comment by mohitpanjwani** [comment]
Please check: https://github.com/bytefury/crater/issues/290

**Comment by jameel-fullstackdeveloper** [comment]
it worked

Thanks a lot
