### ISSUE TITLE
Updating from 3.1.1 to 3.2.0 makes crater crash.

### ISSUE THREAD

**Issue by ggiak** [bytefury/crater#297]
**Describe the bug**

When I try to update the app from 3.1.1 to 3.2.0
I am getting a success message like shown in first screenshot
and then I am getting an error.

Then the whole app goes down, in order to fix I have to manually composer update.
then my setup is still saying that I have 3.1.1 version.

**Expected behavior**
Upgrade without an issue.
or fail in the process.

**Screenshots**
1.![image](https://user-images.githubusercontent.com/20743694/101357370-02eee480-38a2-11eb-8f94-d6713ca2f79b.png)
2.![image](https://user-images.githubusercontent.com/20743694/101357657-6bd65c80-38a2-11eb-8756-485357f5dbf0.png)

**Please complete the following information:**
- Crater version:  3.1.1
- PHP version: 7.4
- Database type and version: MySQL 5.7

**Comment by mohitpanjwani** [comment]
Did you follow this guide: https://docs.craterapp.com/upgrade-guide.html

**Comment by ggiak** [comment]
Hey @mohitpanjwani yes, I did follow those steps as well.

it ended on a different error though.

this happened on the second time I tried to run artisan update.

![image](https://user-images.githubusercontent.com/20743694/101379877-77834c80-38bd-11eb-8d0e-17905dd1ffff.png)

**Comment by mohitpanjwani** [comment]
That’s weird. 

Can you try doing a fresh install on a different subdomain or domain using latest crater and complete the wizard. 

After that just update your .env to use old database and run ‘php artisan migrate’.

We have tried to make it easy to manually update on this update because of uncertain issues like this.

**Comment by mohitpanjwani** [comment]
Or else you can follow the manual path mentioned in Upgrade guide

**Comment by ggiak** [comment]
> Or else you can follow the manual path mentioned in Upgrade guide

hmm, can't around it either, first time the setup wizard spawns an error:
![image](https://user-images.githubusercontent.com/20743694/101394150-c71f4380-38d0-11eb-84c7-efd1f4cc7ae1.png)

the second time it says the database is not empty.

**Comment by mohitpanjwani** [comment]
> > Or else you can follow the manual path mentioned in Upgrade guide
> 
> hmm, can't around it either, first time the setup wizard spawns an error:
> ![image](https://user-images.githubusercontent.com/20743694/101394150-c71f4380-38d0-11eb-84c7-efd1f4cc7ae1.png)
> 
> the second time it says the database is not empty.

Don’t use the same old DB in the Installation. Create a temporary empty DB & finish the wizard.

After that change the db to your old oke from env file and run the migration command.

**Comment by mohitpanjwani** [comment]
> > > Or else you can follow the manual path mentioned in Upgrade guide
> > 
> > 
> > hmm, can't around it either, first time the setup wizard spawns an error:
> > ![image](https://user-images.githubusercontent.com/20743694/101394150-c71f4380-38d0-11eb-84c7-efd1f4cc7ae1.png)
> > the second time it says the database is not empty.
> 
> Don’t use the same old DB in the Installation. Create a temporary empty DB & finish the wizard.
> 
> After that change the db to your old oke from env file and run the migration command.

Also don’t forget to add the env variables given in the upgrade guide otherwise you won’t be able to login. 

If you get unauthenticated error, it means that its an issue with env variables.
