### ISSUE TITLE
generated pdf's for estimate & invoices don't have file extension when downloaded

### ISSUE THREAD

**Issue by nikkoentena** [bytefury/crater#298]
**Describe the bug**
Generated pdf's for estimate & invoices don't have file file extension when downloaded. Downloading pdf's for reports have no problem

**Expected behavior**
estimate & invoice pdf's should have a .pdf file extension when downloaded

**Please complete the following information:**
- Crater version:  4.0
- PHP version:  7.4
- Database type and version:  mysql

**Optional info**
- OS:  Windows
- Browser:  Chromium

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.0.1

Please update your app from Settings -> Update App to get the new changes.
