### ISSUE TITLE
Custom payment number

### ISSUE THREAD

**Issue by vbezruchkin** [bytefury/crater#30]
Hi,

Could you please add an option to allow custom payment numbers? I don't want any prefixes there, as I would use custom values for different customers. I might also need another field if we keep current structure where I can refer to a real payment ID via payment system.

**Comment by mohitpanjwani** [comment]
@vbezruchkin on the next major version, you will be able to edit the payment numbers as well as disable auto-generation.

**Comment by mohitpanjwani** [comment]
This feature has been added in the latest release: 
https://github.com/bytefury/crater/releases/tag/2.1.0
