### ISSUE TITLE
Cannot login after upgrade to 4.0.0

### ISSUE THREAD

**Issue by jpmurray** [bytefury/crater#300]
**Describe the bug**
A seemingly successfull update to 4.0.0, following the upgrade guide (including adding the environment variables), has me locked out of Crater. I'm redirected back to the login page, with the alerts you can see in the screenshots section. There is also nothing in the log.

**Expected behavior**
Entering login and password should redirect me to the interface. 

**Screenshots**
<img width="346" alt="Screen Shot 2020-12-08 at 11 42 07 AM" src="https://user-images.githubusercontent.com/1550428/101514682-89133580-394b-11eb-80c3-9c15415559f1.png">

**Please complete the following information:**
- Crater version: 4.0.0
- PHP version: 7.4.9
- Database type and version: MySQL 8.0.9

**Optional info**
- OS:  Os X
- Browser: Firefox

**Comment by jpmurray** [comment]
Trying to debug this, so I discovered that with Chrome I could login, but I get an "server error" alert, and the dashboard isn't loading.

Server log shows this:

```
[2020-12-08 17:11:28] local.ERROR: Undefined index: language {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: language at /app/Http/Controllers/V1/General/BootstrapController.php:25)
```

**Comment by jpmurray** [comment]
Tried another clean install, and I got this one between 3.1.0 and 4.0.0:

```
PHP Fatal error:  Trait 'Laravel\Sanctum\HasApiTokens' not found in /Users/jpmurray/Repositories/Tools/crater.atomescroch.us/app/Models/User.php on line 26
```

Decided  to do another install. Started from 3.2.0, updating to 4.0.0:

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'personal_access_tokens' already exists (SQL: create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')
```

At this point, I'm getting error that are different from time to time, it's hard to help and debug... :(

**Comment by mohitpanjwani** [comment]
Hey @jpmurray.

Please ignore the error and continue with composer dump autoload command after you upgrade from 3.2 to 4. 

The login error is because of the sanctum env variables. 

Please check the upgrade guide and make sure to add correct env variables based on your domain. 

Also clear your browser cache once before trying to login again after changing the .env file.

**Comment by mohitpanjwani** [comment]
If this all fails, you can follow the manual path in the guide. 

That should do it as well. Please let me know if there’s any other issue. 

Because of so many changes, there was no easy way to do this unfortunately. However, The future updates should be as easily doable from the UI itself.

**Comment by mohitpanjwani** [comment]
> Tried another clean install, and I got this one between 3.1.0 and 4.0.0:
> 
> ```
> PHP Fatal error:  Trait 'Laravel\Sanctum\HasApiTokens' not found in /Users/jpmurray/Repositories/Tools/crater.atomescroch.us/app/Models/User.php on line 26
> ```
> 
> Decided to do another install. Started from 3.2.0, updating to 4.0.0:
> 
> ```
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'personal_access_tokens' already exists (SQL: create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')
> ```
> 
> At this point, I'm getting error that are different from time to time, it's hard to help and debug... :(

You will always receive this hasApiTokens Error. 

Ignore that error and continue with next command.

**Comment by jpmurray** [comment]
Excellent, I'll be testing this before next week, I'll be updating with results as soon as it's done ! :)

**Comment by jpmurray** [comment]
All right, so far, here's where I am:

- Did the upgrade steps as listed in the upgrade guide, and ignored errors as you suggested in this issue;
- Tried to login with Firefox, and got the first error I was posting, so I went on and used Chrome (because I'm lazy and did not want to dig in and clear cache :P). With Chrome, it seems I can login, but I'm getting a blank page with a loading icon and a toast alert saying server error, and here's what's appearing in the error logs:

```
local.ERROR: Undefined index: language {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: language at /app/Http/Controllers/V1/General/BootstrapController.php:25)
```

Manual installation does the same. At this point, I'm cosidering a fresh install to be honest. Do you think the following 3 steps would work, @mohitpanjwani  ?

- Having a clean 4.0.0 install;
- Restoring current database;
- Copying back the storage folder.

**Comment by mohitpanjwani** [comment]
@jpmurray Hey, Have you created any other user manually? 

Please set the language for the user or change BootstrapController's following line: 

```
$default_language = $user->getSettings(['language'])['language'];
```

Change to:
```
$default_language = 'en';
```

**Comment by mohitpanjwani** [comment]
It should be fixed after you make the above changes, but let me know if you still encounter any other issue.

**Comment by betinhosampler** [comment]
Consegui resolver assim aqui, em C:\Windows\System32\drivers\etc\hosts   criei   127.0.0.1       local.crm.com

e em C:\xampp\apache\conf\extra\httpd-vhosts.conf  criei o server virtual
<VirtualHost *:80>
    ServerAdmin webmaster@local.crm.com
    DocumentRoot "C:/xampp/htdocs/crm-ac"
    ServerName local.crm.com
    ErrorLog "logs/local.crm.com-error.log"
    CustomLog "logs/local.crm.com--access.log" common
</VirtualHost>

e no meu .env setei

APP_URL=http://local.crm.com:8000
SANCTUM_STATEFUL_DOMAINS=local.crm.com:8000
SESSION_DOMAIN=local.crm.com

então rodei php artisan config:cache  e depois php artisan run serve e acessei no navegador com  http://local.crm.com:8000/

funcionou pra mim wowowowow

**Comment by jpmurray** [comment]
> $default_language = 'en';

All right, so after changing this, I am able to log in. But I think something in the update to 4.0.0 went wrong:

- The `user_setting` has absolutely no rows in it. Should there be some by default ?
- Also, I'm logged in, but I'm still getting this server error alert on every pages:

```
local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addresses.company_id' in 'where clause' (SQL: select * from `addresses` where `addresses`.`company_id` in (1)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'addresses.company_id' in 'where clause' (SQL: select * from `addresses` where `addresses`.`company_id` in (1)) at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
```

It's usable, but I'm really wondering where things have gone bad. I did upgrade from 3.0.0 to 3.1.0, then to 3.2.0 and then to 4.0.0. There a lot that could have gone wrong, and I still have copies of files / databases of every iteration, so I can go back in time if you want to trace something ;-)

**Comment by mohitpanjwani** [comment]
I think the migration didn’t run while updating coz of the error. 

Can you run this command: php artisan migrate 

That should fix everything.

**Comment by jpmurray** [comment]
And I'm back at:

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'personal_access_tokens' already exists (SQL: create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')
```

while migrating `2019_12_14_000001_create_personal_access_tokens_table` :(

**Comment by mohitpanjwani** [comment]
@jpmurray Let's try to fix this together on discord. 

It looks like some migrations ran but it didn't create an entry on the `migrations` table. 

Also can you share a screenshot of your migrations table & the list of tables in your DB?

**Comment by jpmurray** [comment]
Sure can do ! I'll hop on Discord at some point today so we can continue there :)

**Comment by jpmurray** [comment]
I'll close the issue. This has been resolved over discord, and there's a high chance that I was a unique case with some broken tables :)

**Comment by yourfavoritenerd** [comment]
@jpmurray  can you assist me? I have the same error, can't login
