### ISSUE TITLE
Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by NoverNobida** [bytefury/crater#301]
**Describe the bug**
Syntax error or access violation: 1064

**Screenshots**
![image](https://user-images.githubusercontent.com/46912250/101524613-21013580-39c5-11eb-8734-62598a7bfeeb.png)

**Please complete the following information:**
- Crater version: 4.0.0
- PHP version: 7.4
- Database type and version: mysql 5.6.44

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `label` varchar(255) not null, `model_type` varchar(255) not null, `type` varchar(255) not null, `placeholder` varchar(255) null, `options` json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answer` time null, `string_answer` text null, `number_answer` bigint unsigned null, `date_time_answer` datetime null, `is_required` tinyint(1) not null default '0', `order` bigint unsigned not null default '1', `company_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')

**Comment by quangbahoa** [comment]
Try this https://github.com/bytefury/crater/issues/140#issuecomment-731504315
