### ISSUE TITLE
Error in Migrating: 2020_02_01_063235_create_custom_fields_table

### ISSUE THREAD

**Issue by spoutnikfr** [bytefury/crater#302]
**Describe the bug**
Migrate fail with SQLSTATE[42000]: Syntax error or access violation: 1064

> `options` json null 

`$table->json('options')->nullable();`
**Expected behavior**
Migration success, no SQL error
**Screenshots**

![Capture d’écran 2020-12-08 à 19 53 55](https://user-images.githubusercontent.com/11408086/101528097-217ed980-398f-11eb-9a40-905f2561d974.png)
**Please complete the following information:**
- Crater version: 4.0.0
- PHP version: 7.4
- Database type and version: Mysql 5.6.50

**Optional info**
- OS:  Debian

**Comment by mohitpanjwani** [comment]
@spoutnikfr I think you need to update your MySQL version.
