### ISSUE TITLE
Android App: Create/edit invoice loads forever

### ISSUE THREAD

**Issue by oliversum-ch** [bytefury/crater#304]
**Describe the bug**
I'm currently using Crater 3.1.1 and didn't update to 4.0 yet as I have some issues with my SSH access. Everything works very well on Desktop but since Sunday, certain actions on the android app take forever to load.

1. Start Crater on Android (I tested 3 phones on several networks and was able to reproduce the issue)

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Crater version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by mohitpanjwani** [comment]
Hey @oliversum-ch, 

If you updated your android app, it will only work with the latest 4.0.0 version because there's been a lot of breaking changes. 

Please upgrade your web version to 4.0.0 to fix it.

**Comment by oliversum-ch** [comment]
Thanks for your fast reply, @mohitpanjwani!
You're right, I updated the app to 4.0, but not the web version yet, as the internal updater doesn't seem to work, and I have issues with SSH access to my server. Thank you very much!
