### ISSUE TITLE
v4.0.0 - docker - ONBOARDING stuck at mail step (401 unauthorized)

### ISSUE THREAD

**Issue by joxcat** [bytefury/crater#305]
**Describe the bug**
During the setup I cannot go past the mail setup, the page never finish loading. And I get a notification "Unauthhenticated".

**Expected behavior**
I expected to be able to configure the mail server to be used by crater.

**Screenshots**
![Screenshot from 2020-12-09 17-02-01](https://user-images.githubusercontent.com/11839373/101655264-b215f200-3a41-11eb-95d0-65d762e6a1f5.png)

**Please complete the following information:**
- Crater version: 4.0.0 (2bd01c401452125eeeec9fe2802e41805267c193)
- PHP version: crater-php:latest
- Database type and version: sqlite3
- Docker-compose version: 1.27.4, build 40524192
- Docker version: 19.03.13, build 4484c46d9d

Crater is running in docker behind a traefik reverse proxy (I've tried without it too).

**Optional info**
- OS: Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
- Browser: Chrome + Firefox

**Comment by mohitpanjwani** [comment]
Hey @joxcat, 

I think it's an issue with Laravel Sanctum. 

On what URL are you trying to install Crater? 

Also, can you show me a screenshot your of your .env file? (I don't need to see your DB credentials but need to confirm that Sanctum variables are added properly)

**Comment by joxcat** [comment]
Hello @mohitpanjwani here's my `.env` file 
```
APP_ENV=production
APP_KEY=base64:someBase64String
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=https://invoices.mydomain.xyz

DB_CONNECTION=sqlite
DB_DATABASE=/var/www/database/database.sqlite

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_DRIVER=sync
SESSION_DRIVER=cookie
SESSION_LIFETIME=1440

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=

SANCTUM_STATEFUL_DOMAINS=invoices.mydomain.xyz
SESSION_DOMAIN=invoices.mydomain.xyz
```

**Comment by mohitpanjwani** [comment]
Hi @joxcat, 

For some reason the Sanctum cookie authentication seems to fail on your system. 

Please verify that SANCTUM_STATEFUL_DOMAINS & SESSION_DOMAIN env variables are added in the correct format: 
```
https://staging-docs.craterapp.com/upgrade-guide.html#step-4-add-required-environment-variables
```

**Comment by joxcat** [comment]
I've retried while mapping docker directly to port 8080 and it work, but behind a reverse proxy (with https) I'm stuck to the mail step. 
But I think you're wright about Sanctum cookie authentication failing.

**Comment by BIIINO** [comment]
Hello please any updates ?

Did you fix that issue ?

**Comment by joxcat** [comment]
> Hello please any updates ?
> 
> Did you fix that issue ?

Sorry I didn't found a fix for my issue and I'm no longer a freelancer, I don't need Crater anymore for the moment so I'll close this issue. 
@BIIINO feel free to open a new issue with the details of your problem and quoting this one if needed.

**Comment by lillishaj** [comment]
I got exacly same issue.
