### ISSUE TITLE
The email has already been taken.

### ISSUE THREAD

**Issue by thanhbinh-primelabo** [bytefury/crater#309]
From: admin/settings/user-profile
When the email update exists another record in the user's table.
=> not return this.isLoading = false
=> cannot continue without refreshing the page

Error: PUT /api/v1/me 422 (Unprocessable Entity)
Please check again.

**Comment by mohitpanjwani** [comment]
This issue should be fixed on 4.0.2 

Please update from Settings -> Update App screen and let me know if you still encounter this.
