### ISSUE TITLE
Incorrect due amount when creating payments

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#313]
**Describe the bug**
I've created an invoice and recorded a payment against it. Saving the payment was successful, however, when I was taken back to the list of invoices it stated that the invoice was partially paid, the due amount was £0.01.

**Expected behavior**
There shouldn't have been any outstanding amount after the invoice was fully paid.

**Screenshots**
There is a check in the Payment model at line 144. I've dumped the values: the invoice's due amount and the amount sent in the request, see the results in the bottom-right corner of the screenshot:

![crater_rounding_issue](https://user-images.githubusercontent.com/2471046/101987655-75d6d180-3c8d-11eb-9dea-0c070a24bcc7.jpg)

It seems that the amount sent in the request is invalid and casting the type to integer results in this weird behaviour.

**Please complete the following information:**
- Crater version: 4.0.1
- PHP version: 7.4.13
- Database type and version: MySQL 5.7

**Optional info**
- OS:  Elementary OS
- Browser: firefox, brave

**Comment by barf** [comment]
Here is the problem:
```$ grep -RHni float app/
app/Models/Estimate.php:53:        'discount' => 'float',
app/Models/EstimateItem.php:31:        'discount' => 'float',
app/Models/EstimateItem.php:32:        'quantity' => 'float',
app/Models/Invoice.php:51:        'discount' => 'float',
app/Models/InvoiceItem.php:34:        'discount' => 'float',
app/Models/InvoiceItem.php:35:        'quantity' => 'float',
app/Models/Tax.php:32:        'percent' => 'float'
app/Models/TaxType.php:22:        'percent' => 'float'```

Floats are not suitable for currency mathematics. A decimal type with rounding should be used instead.

**Comment by mohitpanjwani** [comment]
I'm looking into this 👀

**Comment by mohitpanjwani** [comment]
This issue has been fixed on https://github.com/bytefury/crater/releases/tag/4.0.2.

Please update from Settings -> Update App Screen.
