### ISSUE TITLE
Browser crash at https://demo.craterapp.com/

### ISSUE THREAD

**Issue by davidg246819** [bytefury/crater#316]
**Describe the bug**
I thought I had backend issue but it seems like it's something else. I did a self hosted manual install of 4.0.0 and 4.0.1 and after success I login and attempt to create an invoice and Chrome 87.0.4280.88 just hangs. I also tried Firefox 83.0 and no success, browser hangs.

I then tried the same at https://demo.craterapp.com/ and it exhibits the same behavior. FF and Chrome hang. I've tried this on a clean Win 10 VM, a Win 10 laptop, desktop and a Macbook Pro with Catalina.

Am I doing something wrong or did I miss a FAQ or other issue?

To reproduce: Visit https://demo.craterapp.com/ and login, go to Invoices and hit New Invoice.

**Please complete the following information:**
- Crater version: 4.0.1
- PHP version: 7.4.11
- Database type and version: MySQL 5.x

**Optional info**
- OS:  MBP Catalina and Windows 10
- Browser: Chrome 87.0.4280.88 and Firefox 83.0

**Comment by mohitpanjwani** [comment]
Hello @davidg246819, 

We're not able to reproduce this issue personally, however, several other users have reported the same issue.

Do you get any errors on the browser console? If not, do you have `yarn` installed on your computer? We'll need to update  a particular file and compile the files in order to find the cause. 

Thanks

**Comment by davidg246819** [comment]
I just installed Crater from GH repo instead of doing a manual install. I followed Developer Guide to set up with yarn/composer and dropped it behind nginx. I followed the on-boarding steps and can login successfully, and I used both an incognito window and normal. I went to Invoices and New Invoice and it exhibits the same behavior, browser crash.

I watched the Chrome console and network tools and I see no messages in either, doesn't look like XHR is firing at all when I hit New Invoice, and I don't see a hit to nginx either.

I have source tree set up and yarn and node 12. The date format is set to 12/21/2020 and timezone is Los Angeles (UTC-08:00)

Thanks!

**Comment by mohitpanjwani** [comment]
Thanks a lot for all the information @davidg246819 

We've applied a fix on the demo site based on the feedback.. can you try creating an invoice and let me know it still crashes for you? 

https://demo.craterapp.com/

**Comment by davidg246819** [comment]
I've tested demo site with Chrome and FF and it works as expected, no browser hang. I tested most all pages including New and Edit/View and I don't see any issues.

**Comment by mohitpanjwani** [comment]
Thank you very much for testing @davidg246819. 

We've released a new update that includes this fix.

Please update from Settings -> Update App Screen.

Release: https://github.com/bytefury/crater/releases/tag/4.0.2
