### ISSUE TITLE
Can't update to 3.2.0

### ISSUE THREAD

**Issue by tobidwest** [bytefury/crater#319]
I'm trying to update from 3.1.1 to 3.2.0 at /admin/settings/update-app. 

When starting the update process, I see a confirmation message after some time:
![image](https://user-images.githubusercontent.com/61382793/102790129-4dde2100-43a5-11eb-9224-284bbe70313f.png)

But once the page has refreshed, I can see that I'm still on 3.1.1 and the update is still available.

**Comment by mohitpanjwani** [comment]
Hey @tobidwest, it's not possible to update to version 4 from the UI coz of too many major changes and complete refactor of the whole code-base. 

Please follow this guide in order to update: https://docs.craterapp.com/upgrade-guide.html

**Comment by tobidwest** [comment]
Thanks for reaching back, @mohitpanjwani :)
