### ISSUE TITLE
Unable to view some pdfs

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#32]
Might be something to do with #14, but I think it's a slightly different issue.

I have 12 invoices and from the "Invoices" / ... / "View" menu I can view all of them except the first two I created - the rest (10 other invoices) are fine.

If I click the "... / Edit" action button and then the "View PDF" then all the pdfs are fine.

**Steps to reproduce:**
- have at least 11 invoices
- go to "Invoices"
- (optional) go to the "All" tab if the invoices have been paid
- at the bottom of the page go to the second page
- click one of the "... (actions) / View" links

**Results:**
an empty page (see screenshot)

**Expected result:**
the list of invoices and the pdf invoice shown next to the list (as for the other 10 invoices).

I'm just guessing here without looking at the code, but could it be something to do with the `/invoices` endpoint returning only the first 10 invoices (ordered by the created date) and the first two that I'm unable to access aren't in that list?
![Screenshot from 2019-12-08 10-57-53](https://user-images.githubusercontent.com/2471046/70388465-fc394300-19a9-11ea-8a16-aad1cd15c844.png)

**Comment by mohitpanjwani** [comment]
@pszucs Thanks for reporting the issue and the detailed explanation! 

This issue has been fixed on https://github.com/bytefury/crater/commit/1cd654b0ccf8a3a43860cc2ca1ec082bc263a2f1

Please auto-update from the settings page and let me know if there's anything else :)

**Comment by pszucs** [comment]
No worries, it works now.
