### ISSUE TITLE
Translating the actual invoices

### ISSUE THREAD

**Issue by tobidwest** [bytefury/crater#320]
It's very essential that not only the UI but also the actual invoices are translated. 

You could
- add textboxes to do so to the settings page
- share information on how to do this in the code to the translation
- crowdsource translations, I'd be happy to help out with German

**Comment by mohitpanjwani** [comment]
Hey @tobidwest, the invoices/estimates are already translated based on your currently selected language on Preferences -> Default language. 

Please note that it only translates the labels and not the actual data. Also, some languages are missing a few translation keys, so we need contribution from the community regarding those. 

Lastly, If you wish to contribute on translations then you can do that using Crowdin: https://crowdin.com/project/crater-invoice
