### ISSUE TITLE
Show discount on invoices only if not 0

### ISSUE THREAD

**Issue by darim92** [bytefury/crater#322]
Discount should only be on the invoice if not 0. 

Looks a little bit weird if I get an invoice with zero discount (speaking from customer side).

**Comment by Meldiron** [comment]
So far, I think I saw a discount on all invoices I received so maybe there are laws that force you to do it in some countries.
Anyway, if you really want to disable it, you can do it in `resources/views/app/pdf/invoice/partials/table.blade.php` lines 79 to 122. Remove it to get rid of discount summary or edit and add your if statement.

**Comment by tobax99** [comment]
@darim92  you get this function by adding `@if ($invoice->discount_val != 0)`

**Comment by mohitpanjwani** [comment]
This should no longer be an issue in the latest update.. 

We now only show the discount if it's above 0. Let me know if you still encounter an issue.
