### ISSUE TITLE
Estimate PDF text overlapping 

### ISSUE THREAD

**Issue by laxmariappan** [bytefury/crater#325]
I am using the latest 4.0.2 version 

PDF text overlaps like this 

![download (2)](https://user-images.githubusercontent.com/22427070/103164510-2b398580-4847-11eb-90ee-0552634e148c.png)

Am I missing something?

**Comment by mohitpanjwani** [comment]
Do you get the same issue in the demo.craterapp.com? 

If not, please mention your OS, MYSQL Version and other details mentioned in the Issue template.

**Comment by laxmariappan** [comment]
demo.craterapp.com is working fine, no overlapping

Web server | Apache

Linux web78.ptl.stackcp.net 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64

**Please complete the following information:**
- Crater version: 4.0.2
- PHP version: 8.0.0
- Database type and version: mysqlnd 8.0.0 -- phpMyAdmin 5.0.2

**Optional info**
- OS:  [e.g. Ubuntu] Linux 20.04
- Browser: [e.g. chrome, safari] chromium

**Comment by mohitpanjwani** [comment]
> demo.craterapp.com is working fine, no overlapping
> 
> Web server | Apache
> 
> Linux web78.ptl.stackcp.net 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64
> 
> **Please complete the following information:**
> 
> * Crater version: 4.0.2
> * PHP version: 8.0.0
> * Database type and version: mysqlnd 8.0.0 -- phpMyAdmin 5.0.2
> 
> **Optional info**
> 
> * OS:  [e.g. Ubuntu] Linux 20.04
> * Browser: [e.g. chrome, safari] chromium

I think it’s overlapping because of PHP 8. The package that we use for PDF doesn’t support PHP 8 properly. 

It should work perfectly on PHP 7.4
