### ISSUE TITLE
Payment marked as "partially paid", altough full amount entered

### ISSUE THREAD

**Issue by oliversum-ch** [bytefury/crater#326]
**Describe the bug**
I added a payment (full amount) to an invoice (INV-000002) using an own payment mode (added via settings - payment modes). Nonetheless, the invoice is marked as "partially paid". It works if I don't select a payment mode and just save the payment.

**Expected behavior**
Invoice marked as paid.

**Screenshots**
![crater](https://user-images.githubusercontent.com/75724465/103169326-dbed5800-483a-11eb-86ad-41fb7eb3296a.png)

**Please complete the following information:**
- Crater version: 4.0.2
- PHP version: 7.4
- Database type and version: MySQL

**Comment by mohitpanjwani** [comment]
This issue should be fixed in `4.0.3`
Please update your app from `Settings -> Update App` page.

Let me know if you still encounter this issue.

**Comment by oliversum-ch** [comment]
Thanks!
Hmm, I can still reproduce the bug...

**Comment by mohitpanjwani** [comment]
@oliversum-ch Are you able to reproduce the same bug on demo.craterapp.com? 

Please create an invoice from your end and let me know if you can reproduce it. 

It seems to work perfectly on my end.

**Comment by oliversum-ch** [comment]
Hey @mohitpanjwani 
You're right, it works for new invoices, but how can I mark an existing invoice as paid? I already sent it out to the recipient, so I can't delete it and create a new one... 
Can I directly mark it as paid in the database?
Thanks a lot, and happy new year!
