### ISSUE TITLE
Updating Issues

### ISSUE THREAD

**Issue by ddlidded** [bytefury/crater#327]
**Describe the bug**
When attempting to update through the admin panel, it says is successful and the browser re-loads but still shows the same 3.11 version. Even after logging in and out multiple times.

**Expected behavior**
The update to be completed successfully!

**Screenshots**
N/A

**Please complete the following information:**
- Crater version: 3.11
- PHP version: 7.4
- Database type and version: MySqk

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by mohitpanjwani** [comment]
Please check: https://github.com/bytefury/crater/issues/319
