### ISSUE TITLE
Incorrect figures on the Dashboard

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#33]
When I log into the app, the figures on the Dashboard all show `0.00` amounts, 0 customers, 0 invoices. Then I go to any other page and back to the Dashboard, the figures change - showing the amount of the last invoice, the correct number of customers, etc.

**Steps to reproduce:**
- clear cache / open an incognito window
- log into the app - note the figures and the chart
- click "Customers" or any other link
- click "Dashboard" again

**Result:**
The figures on the Dashboard change so that they are showing the amount of the last invoice (or any other, positive amount - I guess depending on what expenses / incomes you have)

**Expected result:**
The figures should be the same as when logging in.

**Screenshots:**

*After logging in:*
![Screenshot_2019-12-09 Crater - Self Hosted Invoicing Platform](https://user-images.githubusercontent.com/2471046/70426432-f22b4900-1a6a-11ea-9757-7ccf39e5c448.png)

*After clicking the "Dashboard" menu again:*

![Screenshot_2019-12-09 2 Crater - Self Hosted Invoicing Platform](https://user-images.githubusercontent.com/2471046/70426495-0a02cd00-1a6b-11ea-9063-d51c44971b6b.png)

**Comment by mohitpanjwani** [comment]
Hey @pszucs! 

Once again thanks for reporting the issue! This has been fixed. 

We'll deploy an update together with ability to update invoice/estimate/payment numbers after testing.

**Comment by pszucs** [comment]
That's great. Happy to help, keep up the good work! ;)

**Comment by mohitpanjwani** [comment]
Deployed the fix in the latest release: 
https://github.com/bytefury/crater/releases/tag/2.1.0
