### ISSUE TITLE
SQL Invalid text representation at Invoice/Estimate Item-Price

### ISSUE THREAD

**Issue by tobax99** [bytefury/crater#330]
When editing the Item-Price of Invoice or Estimation its not possible to save it.

Error-Message:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "3500.00" (SQL: insert into "invoice_items" ("invoice_ide", "item_id", "name", .... ) values (4.1 

**Screenshots**
![image](https://user-images.githubusercontent.com/40302647/103395451-9a0c2c80-4b2e-11eb-94db-994a0d7baca7.png)

**Please complete the following information:**
- Crater version: 4.02
- PHP version: 7.4.13
- Database type and version: postgresql 10.15
--

*Optional info**
- OS:  VPS Ubuntu 18.04 LTS 64bit + Plesk Obsidian
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Hey @tobax99, There was an issue with rounding. 

We've released a new update for this. Please update your app from `Settings -> Update App` page.

**Comment by tobax99** [comment]
Wow, thanks for the super fast fix! 👍 :)
