### ISSUE TITLE
"Insert Note" link not working

### ISSUE THREAD

**Issue by pszucs** [bytefury/crater#334]
**Describe the bug**
Nothing happens when clicking on the "Insert Note" link (on pages: Create invoice, Create payment, Create estimate).

**Expected behavior**
Clicking on the "Insert Note" link should bring up the pre-defined notes.

**Screenshots**
![Screenshot from 2021-01-02 09 43 19](https://user-images.githubusercontent.com/2471046/103454766-21000700-4cdf-11eb-860c-0182611f5c73.png)

**Please complete the following information:**
- Crater version: 4.03
- PHP version: 7.4
- Database type and version: MySQL 8

**Optional info**
- Browser: Firefox, Chrome

This issue was introduced by either v4.02 or v4.03 - it used to work prior these versions.

**Comment by habibhaidari1** [comment]
resources/assets/js/components/theme/SwPopup.js

Replace 
    activator: 'relative w-full cursor-pointer',
with
    activator: 'relative z-10 cursor-pointer',

**Comment by mohitpanjwani** [comment]
I've fixed this issue and deployed a new release: https://github.com/bytefury/crater/releases/tag/4.0.4

Make sure to update your crater app from Settings -> Update app to Version 4.0.0
