### ISSUE TITLE
400 Bad Request Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by jabaa** [bytefury/crater#338]
**Describe the bug**
I followed https://docs.craterapp.com/installation.html#docker-installation step by step and finished all steps without problems. I opened the browser on localhost:80 and the installation wizard doesn't start. I get

```
400 Bad Request
Request Header Or Cookie Too Large
nginx/1.17.10
```
instead. 3 containers are running. I can't see any errors with `docker logs`.

**Expected behavior**
Working installation wizard

**Please complete the following information:**
- Crater version: 4.0.3

**Optional info**
- OS:  Arch Linux
- Browser: Firefox

**Comment by patricklucas** [comment]
While iterating on my initial setup, I went through the onboarding process a few times, and either Crater or Laravel creates cookies with a randomized key, meaning I accrued multiple large cookies, eventually causing this issue.

@jabaa deleting my cookies helped for me. Even though the cookies are quite large, now that my setup is complete they're around 2 KB total, well short of Nginx's 8 KB limit.
