### ISSUE TITLE
Can't login behind Nginx reverse proxy

### ISSUE THREAD

**Issue by restos-99** [bytefury/crater#340]
I'm running the latest version of Carter App behind a Nginx reverse proxy.

In the .env file I have the correct SACTUM_STATEFULL_DOMAINS and SESSION_DOMAIN settings according to the domain name.

When I try to login, I always get the following error.

<img width="265" alt="Captura de pantalla 2021-01-09 a las 14 47 38" src="https://user-images.githubusercontent.com/74348220/104093262-a9efe300-5289-11eb-924f-2de2c07df34f.png">

There is an active internet connection on server. Also, If I reload the page, user redirects to dashboard.

Any help or idea?

thank you.

**Comment by restos-99** [comment]
This is the Nginx proxy configuration:

`server {
        server_name craterapp.domain.com;

        location / {

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
         proxy_pass http://craterapp_ip;
}



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/craterapp.domain.com/fullchain.p$
    ssl_certificate_key /etc/letsencrypt/live/craterapp.domain.com/privkey$
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}




server {
    if ($host = craterapp.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80;
        server_name craterapp.domain.com;
    return 404; # managed by Certbot


}`

**Comment by SteveEdson** [comment]
I've just updated from 3.1 and I'm getting the same issue. Because it's running without SSL inside the container (and the proxy is providing the SSL), it's trying to redirect to a HTTP url, rather than HTTPS. Is there a way to force it to think its running on HTTPS?

Thanks

**Comment by SteveEdson** [comment]
I can fix the redirect issue by editing `app/Http/Middleware/TrustProxies.php` and adding `protected $proxies = '*';`. However I'm still getting a 401 on the bootstrap request.

**Comment by mohitpanjwani** [comment]
@SteveEdson 

On app/Providers/RouteServiceProvider.php

Can you update this line to following: 

FROM THIS
`public const HOME = '/admin/dashboard';`


TO THIS: 
`public const HOME = 'https://your-domain/admin/dashboard';`

**Comment by SteveEdson** [comment]
@mohitpanjwani unfortunately, that isn't the issue. I can fix the redirect by editing the trusted proxies mentioned above. The issue is now that although I can successfully log in, subsequent calls are failing telling me that I'm unauthenticated.

**Comment by mohitpanjwani** [comment]
In that case its an issue with sanctum. Can you share the values in .env file for:  session_domain and sanctum_stateful_domains variables?

**Comment by SteveEdson** [comment]
Ah thats fixed it, thanks. I was upgrading from an older version that didn't have these in the `.env.example` file. Is it worth adding an exception if these variables aren't set?

Thanks for the help

**Comment by mohitpanjwani** [comment]
I have mentioned the same on the upgrade guide but you’re right. 

We should add an exception/error message that explains it better 👌

**Comment by KevoM** [comment]
> I have mentioned the same on the upgrade guide but you’re right.
> 
> We should add an exception/error message that explains it better 👌

It works, thanks !
Link to user guide : https://docs.craterapp.com/upgrade-guide.html#step-4-add-required-environment-variables
