### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by aorvay** [bytefury/crater#341]
Hi everyone,

I'm trying to install over docker, followed the steps and all works fine until first configuration.
Once I put the data for the db and move forward the installation show the login screen, all next configuration step get passed and not configured.
So, I can access to the app!!

Any help!

So sorry for my english, if need more info, tell me what!

**Comment by mohitpanjwani** [comment]
Hi @aorvay, Please provide all the information given in issue format. 

We cannot help without those details.

**Comment by aorvay** [comment]
Hi Mr. Mohit,

Installation fails during initial configuration, no error on the navigator.

The initial configuration after the docker-compose installation is compose of 7 steps, but when I continue from third to fourth step configuration "fails" and navigator jumps directly to the login page. As there is no user configured it's impossible to access to the app.

I attach a video during my initial configuration and the issue:

https://user-images.githubusercontent.com/17532118/104196648-51088200-5424-11eb-87cd-93e40f6f7b80.mp4

- Docker version 20.10.2, build 2291f61
- Docker-compose version 1.27.4
- PHP 7.4.13 (cli) (built: Nov 30 2020 20:40:09) 
- npm version 6.14.10
- Composer 1.8.4 2019-02-11 

The only change made in the docker-compose file is the nginx host port to 8880.

OS release: Debian GNU/Linux 10 (buster)
On a Raspberry Pi 4

I hope this information is sufficient to reproduce the issue.

Regards,

**Comment by mohitpanjwani** [comment]
Hey @aorvay, Thanks for the details.

Your App Domain needs to match the URL that you're accessing the website from otherwise it will not work. Crater uses Laravel Sanctum for authentication and the field APP_DOMAIN is needed in order to authenticate all the requests.

Also, I'd suggest creating a virtual host or access your website from a URL like `http://crater.test` or just `http://localhost:8880` instead of the IP Address.

**Comment by mohitpanjwani** [comment]
Also @aorvay, please note that APP_DOMAIN should not contain http:// or https:// in front of the URL.

If you're browsing on a different port like localhost:8880, then the APP_DOMAIN should include the port: `localhost:8880`

**Comment by aorvay** [comment]
Thanks a lot Mohit, works!!

It's possible to define negative VAT's? in some cases in Spain, VAT could be negative and the app didn't allow!

Regards,

**Comment by mohitpanjwani** [comment]
Glad to know that it worked out @aorvay 👍

Regarding Negative tax,  currently thats not possible. 

There’s already an issue regarding this: https://github.com/bytefury/crater/issues/315

**Comment by fredericpfisterer** [comment]
hello,

where do you change APP_DOMAIN ? is it in .env ?

Thanks.
