### ISSUE TITLE
Error message in settings pages blocking interaction

### ISSUE THREAD

**Issue by antonio-manuel** [bytefury/crater#342]
**Describe the bug**
After a successful installation, when I try to enter to some settings pages I get the same error show and I cannot interact with the page itself: "**The settings field is required**"

<img width="1688" alt="Screenshot 2021-01-11 at 08 02 26" src="https://user-images.githubusercontent.com/11867984/104153938-e3d4fc80-53e3-11eb-80cc-6c57d259b3ee.png">

The same error is being shown in other screens but looks like is not blocking anything there, like this one:

<img width="1335" alt="Screenshot 2021-01-11 at 08 02 50" src="https://user-images.githubusercontent.com/11867984/104153973-f7806300-53e3-11eb-8484-82bf99ace1cb.png">
This error was shown in English no matter the language preference you have, I tried to do a clean installation in Spanish and yet this message was shown in English.

**Version info**
- Crater version: 4.0.3
- PHP version: 7.4.13
- Database type and version: MySQL 5.7.32

**Optional info**
- OS:  Ubuntu 16.04.6
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Hey, Sorry I was away on a vacation so couldn't reply earlier. 

Btw I'm not able to reproduce this issue. 

Did you install manually using the zip file or docker setup?

**Comment by antonio-manuel** [comment]
I did it manually in my own server.

I re-installed the last version 4.0.4 right now. This is the access data in case you want to check (it's empty and I'll remove it afterwards):

- https://facturacio.albacomallonga.com
- a@a.com
- password

**Comment by mohitpanjwani** [comment]
Hey, Can you try updating to latest version and see if that fixes the issue? 

Reopen the issue if you still encounter this.
