### ISSUE TITLE
Also add the possibility to add invoices and estimates as attachments in emails

### ISSUE THREAD

**Issue by sebastiancretu** [bytefury/crater#343]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be useful to have the option to add the invoice/estimate as an attachment instead of a link to generate them in the emails. If we want to have crater on an internal network only, customers won't have access to the links and they cannot generate their invoices/estimates. This would mean that we need to manual generate them, save them, and attach and send the email manually.
Also, I am not 100% sure, but the existing method might not be GDPR compliant since anyone with the link can have access to the invoice.

**Describe alternatives you've considered**
I think in the settings page, under Customization -> Invoices / Estimates there should be an option that allows us to select if we want to send a link or the actual invoice/estimate as an attachment.

**Comment by sebastiancretu** [comment]
Created a pull request for this here: https://github.com/bytefury/crater/pull/407

**Comment by tobidwest** [comment]
It is released, I think you can close this issue

**Comment by mwlandolsi** [comment]
I have no choice here, can't set to 'link' in configuration.  even I choose send as a link I got the mail sent as an attachment.
