### ISSUE TITLE
After updating Invoice the date changes

### ISSUE THREAD

**Issue by zvezdicaana** [bytefury/crater#345]
If I want to edit Invoice or Payment (probably the same issue with Estimate and Expense), the app automatically changes all Dates to one previous date. If it was before 5.1.2021, it changes it to 4.1.2021, and the next time I open it to 3.1.2021 and so on ...

**Comment by ggiak** [comment]
@zvezdicaana first of all try to change the timezone settings on your account to see if this issue persists.

@mohitpanjwaniI I managed to reproduced the issue, the date is correct at the database, but the date picker is giving a previous date

**Comment by zvezdicaana** [comment]
Thanks, it is a problem with timezone. I have changed it now from UTC +01:00 to UTC +00:00 and it doesn't change anymore.
