### ISSUE TITLE
Installation Stuck - Database should be empty and Server Error

### ISSUE THREAD

**Issue by szubairmaqsood** [bytefury/crater#358]
**Describe the bug**

1) When there is no table in Database, on clicking **"Save & Continue"**, I get error **"Network Error".** At the same time 5 tables gets created in Database.

![screen shot 1](https://user-images.githubusercontent.com/40631971/106164637-04ef6880-61ac-11eb-852b-9f46554100ea.PNG)

![screen 2](https://user-images.githubusercontent.com/40631971/106164697-189acf00-61ac-11eb-96c5-e0c8f6bec57c.PNG)

2) When I clicked **"Save & Continue"**,  I get error **"Database should be empty".**

![Screen shot 3](https://user-images.githubusercontent.com/40631971/106164833-3c5e1500-61ac-11eb-94cd-692dcbe1d4c6.PNG)

3) If I delete all tables in Database, which were created in step 1. I am again on point 1 and loop continues.

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 8.0.1
- Database type and version: phpmyadmin   libmysql - mysqlnd 8.0.1

**Optional info**
- OS: Windows
- Browser: Chrome

**Comment by v6-cblais** [comment]
Experienced the same issue when using the non-persisted DB. Switched to persisted DB while on the setup page and rebuilt the DB container which allowed me to proceed.

**Comment by szubairmaqsood** [comment]
@v6-cblais - Thanks for your reply. I don't see anything in the documentation mentioning this and I am using persisted DB (mysql). If you could guide me in this regard, that would be very helpful.

**Comment by v6-cblais** [comment]
In the docker-compose.yml file I just made the change mentioned in the comments for the DB container. 

 db:
    image: mariadb
    restart: always
    volumes:
      #- db:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      - ./docker-compose/db/data:/var/lib/mysql:rw,delegated

**Comment by szubairmaqsood** [comment]
@v6-cblais - I am not using docker but let me see if I can change the setting of XAMP server on windows.

**Comment by szubairmaqsood** [comment]
@v6-cblais thanks for your help.Now I am also trying to set up this software on ubuntu ,but when I click on **save and continue**. My laravel server gets restarted and I get the same internet error. The image is attached below.



![scree shot 4](https://user-images.githubusercontent.com/40631971/106364720-f98a7180-6352-11eb-8463-45d75a178e72.PNG)

Kindly see this image and help me to solve this problem.

**Comment by mohitpanjwani** [comment]
> @v6-cblais thanks for your help.Now I am also trying to set up this software on ubuntu ,but when I click on **save and continue**. My laravel server gets restarted and I get the same internet error. The image is attached below.
> 
> ![scree shot 4](https://user-images.githubusercontent.com/40631971/106364720-f98a7180-6352-11eb-8463-45d75a178e72.PNG)
> 
> Kindly see this image and help me to solve this problem.

There are many issues with builtin Php server. Use Nginx, Apache or just go with the docker installation. 

Crater does not work with default built-in server.

**Comment by v6-cblais** [comment]
@szubairmaqsood Unfortunately I don't have very much to offer here as I'm pretty new to working in Linux myself; I was just providing information as to the workaround I was able to find for the original problem, and hoping that the developers would find use in that information.
