### ISSUE TITLE
Company logo very small

### ISSUE THREAD

**Issue by v6-cblais** [bytefury/crater#361]
**Describe the bug**
-Logo is very small (about the size of a dime when printed). I don't see any way of changing that nor does a larger image size get reflected

**Expected behavior**
-I'd expect to either change the size of the logo either by using a larger image format or set using the crop tool.

**Screenshots**

**Please complete the following information:**
- Crater version: 4.0.4 
- PHP version: not sure
- Database type and version: mariadb 10.5.8
  -Used the latest docker-compose cloned 1/28/2021

**Optional info**
- OS:  [e.g. Ubuntu] Ubuntu/Docker
- Browser: [e.g. chrome, safari] Edge/Brave/Firefox

**Comment by makakken** [comment]
@v6-cblais which invoice template are you using?

**Comment by makakken** [comment]
invoice1: height of header logo is set to 50px... so if you use a square logo its really small...

**Comment by makakken** [comment]
invoice 2 and 3, it's the same.... ;)

**Comment by v6-cblais** [comment]
I was just about to confirm I've tried all 3 lol. I'd prefer to use Template 3 though.

**Comment by makakken** [comment]
landscape-format should fix that.... otherwise you can edit the templates: https://github.com/bytefury/crater/tree/master/resources/views/app/pdf/invoice simply watch out for .header-logo css class and edit the css....

**Comment by v6-cblais** [comment]
Would I mirror that path in my config or is there something else that I would have to do with that?

That isn't going to make the invoice print in landscape is it?

**Comment by makakken** [comment]
okay sorry, one by one:
- first try: make a landscape-format logo (eg. 200x50 px) so the outcome should look more "big"
- second: you can change the file (in your case invoice3.blade.php) and have a look for this line: https://github.com/bytefury/crater/blob/f47029ca78e74386c56777df3e779d47aede9337/resources/views/app/pdf/invoice/invoice3.blade.php#L38 if you change the height in px, the height and width of your logo gets increased proportinal...

**Comment by v6-cblais** [comment]
So editing the invoice file did the trick. Thanks!!

**Comment by v6-cblais** [comment]
@makakken on a similar note; is it possible to add a footer to the invoice? I don't really know html (I'm an infrastructure guy).

**Comment by makakken** [comment]
seems to be possible.... but it's difficult.
when you add a div-container to the footer, and give it a position: fixed css property, it should appear on every page... but hey.. maybe your invoice-positions-table will overflow it, or something... else is destroying the layout... there you have a reference: https://ourcodeworld.com/articles/read/687/how-to-configure-a-header-and-footer-in-dompdf
