### ISSUE TITLE
Manual installation gives just a white browser window

### ISSUE THREAD

**Issue by aristosv** [bytefury/crater#368]
**Describe the bug**
Followed the exact **Manual** installation instructions, but it seems crater is not working

**Expected behavior**
expected to see a setup window in the browse, but there's only white

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: PHP 7.4.14 (cli) (built: Jan 12 2021 13:59:46) ( NTS )
- Database type and version: Not relevant at this point

**Optional info**
- OS:  Debian 10 Buster
- Browser: Safari

**Screenshots**

1. As per the **Manual** installation instructions found [here](https://docs.craterapp.com/installation.html#manual-installation) I have installed apache2 and php7.4. with all the listed, required modules.

<img width="476" alt="0" src="https://user-images.githubusercontent.com/528302/106848667-1065f680-66ba-11eb-9815-4d057a37d456.png">

![1](https://user-images.githubusercontent.com/528302/106848680-14921400-66ba-11eb-903d-1bd1c91be825.png)

2. I then uploaded crater in /var/www/html and extracted it there.

3. And configured apache default site (/etc/apache2/sites-available# nano 000-default.conf) to point DocumentRoot to /var/www/html/public

4. I then run "chmod -R 775 ./" inside /var/www/html

When I browse to http://192.168.1.37 I just see a white browser window, nothing else.

So either I did something wrong with the instructions, or there's something missing.

What could be going wrong?

**Comment by makakken** [comment]
are there any php errors? /var/www/log/php? or can you turn on error reporting?

**Comment by makakken** [comment]
you can turn on error-reporting like this: https://stackoverflow.com/questions/6127980/enabling-error-display-in-php-via-htaccess-only

**Comment by aristosv** [comment]
Sorry, I spend most of the day yesterday trying to install this software on Debian. Eventually I went with something else. I hope [this script](https://github.com/bytefury/crater/issues/370#issuecomment-773168292) helps someone in the future to avoid most of the problems installing on Debian.

**Comment by ortegaxc** [comment]
@aristosv Hi aristosv, did you solve it? I have the same problem.

**Comment by aristosv** [comment]
no, I just used invoice ninja

**Comment by mohitpanjwani** [comment]
> @aristosv Hi aristosv, did you solve it? I have the same problem.

Hey, Can you check this one? 
https://stackoverflow.com/questions/22757749/laravel-redirects-to-a-route-but-then-apache-gives-404-error/23349603

I personally don't use Apache but you could try this one to see if it works out.

**Comment by ortegaxc** [comment]
Hello, I still can't solve the installation, how much do you charge me for performing the installation?

Thank you.
