### ISSUE TITLE
Docker installation gives error during setup

### ISSUE THREAD

**Issue by aristosv** [bytefury/crater#369]
**Describe the bug**
Error message during setup: 

**Expected behavior**
For the script to continue the installation

**Please complete the following information:**
- Crater version: Docker installation
- PHP version: Docker installation
- Database type and version: Docker installation

**Optional info**
- OS:  Debian 10 Buster
- Browser: Safari

**Screenshots**

These are the exact commands I use to install crater using Docker, as per the Docker installation instructions found [here](https://docs.craterapp.com/installation.html#manual-installation)

```
#!/bin/bash

# run as root
# install dependencies
apt install -y curl git

# create user
adduser --disabled-password --gecos '' accounting
echo accounting:accounting | chpasswd

# install docker
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
usermod -aG docker accounting

# install compose
curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
docker-compose --version

# run as user
# clone repository
git clone https://github.com/bytefury/crater

# run app
cd crater
cp .env.example .env
docker-compose up -d
./docker-compose/setup.sh
```

Running the last command (./docker-compose/setup.sh) gives me the following error.

<img width="1044" alt="3" src="https://user-images.githubusercontent.com/528302/106850754-c717a600-66bd-11eb-8ef0-b8f971e7b9d5.png">

**Comment by bhavesh53** [comment]
I am also getting same error any solution of it ???

**Comment by 4ndrewHarri5** [comment]
Same here, did anyone find a solution?

**Comment by AlexanderSch90** [comment]
Same Problem here
