### ISSUE TITLE
Developer (yarn) installation gives error

### ISSUE THREAD

**Issue by aristosv** [bytefury/crater#370]
**Describe the bug**
Developer installation gives error

**Expected behavior**
for the script to run and install crater

**Please complete the following information:**
- Crater version: Dev (yarn) installation
- PHP version: Dev (yarn) installation
- Database type and version: Dev (yarn) installation

**Optional info**
- OS:  Debian 10 Buster
- Browser: Safari

**Screenshots**

These are the command I used to perform the Developer (yarn) installation, as per the guide [here](https://docs.craterapp.com/developer-guide.html#installation)

```
# install dependencies
apt install -y nodejs npm git
npm install --global yarn

# clone repository
git clone https://github.com/bytefury/crater
cd crater

# run yarn
yarn
```

<img width="845" alt="4" src="https://user-images.githubusercontent.com/528302/106852146-40b09380-66c0-11eb-9c8d-eaf11124a260.png">

I am assuming there's a versioning issue I must fix, but which is the "node" and which is the "module"?

**Comment by mohitpanjwani** [comment]
You can ignore the warning by running this command:
`yarn install --ignore-engine`

OR upgrade your node version.

**Comment by aristosv** [comment]
give me the same error.

<img width="845" alt="5" src="https://user-images.githubusercontent.com/528302/106852655-14e1dd80-66c1-11eb-933b-75dd7b874f6e.png">

Which is the "node" though? What must I upgrade?

**Comment by mohitpanjwani** [comment]
Node is for NodeJS. 

You can see here if you are on Debian 10 or check on google on how to install `node` if you're on some other OS
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-10

**Comment by aristosv** [comment]
So I managed to move to the next step of the installation where you run "composer install" and now I have these errors.

<img width="932" alt="6" src="https://user-images.githubusercontent.com/528302/106854044-57a4b500-66c3-11eb-9e1e-605674588e36.png">

It's telling me that there are missing dependencies, but I was under the impression that running "composer install" would resolve them.

**Comment by mohitpanjwani** [comment]
You need to install PHP 7.4.  The errors you get right now are because of that.

**Comment by aristosv** [comment]
Thanks for all the help, I will be sure to post a working script after everything wroks. It seem I've reached the end of the installation, after I run "php artisan key:generate"

But when I visit http://192.168.1.37 I get the default Apache page. I suppose crater it's in a subfolder somewhere, I just don't know which one.

**Comment by aristosv** [comment]
This is a working script for Debian 10 Buster. I just don't know how to get to the web interface.

```
#!/bin/bash

# install system dependencies
apt install -y npm git curl gnupg2 wget composer

# add php7.4 repository
wget https://packages.sury.org/php/apt.gpg
apt-key add apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php7.list
apt update

# install php7.4 and dependencies
apt install -y php7.4 php7.4-dom php7.4-mbstring

# install nodejs
curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh -o install_nvm.sh
bash install_nvm.sh
source ~/.profile
nvm install 12.14.0
nvm use 12.14.0

# install yarn
npm install --global yarn

# clone and enter repository
git clone https://github.com/bytefury/crater
cd crater

# install dependencies
yarn

# create public files
yarn production

# install laravel and php dependencies
composer install

# create configuration file
cp .env.example .env

# create unique application key
printf 'y\n' | php artisan key:generate
```

**Comment by makakken** [comment]
can you move it to document root? as stated out here: https://docs.craterapp.com/installation.html#step-3-point-the-domain-to-the-uploaded-folder crater is not working in subdirectorys...

**Comment by aristosv** [comment]
Sorry, I spend most of the day yesterday trying to install this software on Debian. Eventually I went with something else. I hope the script above helps someone in the future to avoid most of the problems installing on Debian.
