### ISSUE TITLE
Feedback on the application and some questions

### ISSUE THREAD

**Issue by mabasic** [bytefury/crater#38]
First of, nice work on the application! It looks and feels excellent. I haven't tried the mobile application yet, but I am sure that it is of the same quality.

1. It seems like you have spent a significant amount of work developing it, how come you are giving it open source?
2. I am thinking of replacing my current solution and this seems like a natural fit since I work with Laravel almost all the time. Are you willing to accept PRs for features?
3. Currently what is preventing me from switching is a field on the customer which would hold the VAT number of the customer. In my country that number is called OIB (PIN in english or personal identification number) and it is required for each customer to be displayed on the invoice and estimates. I don't know how it is in other countries. Is this something that you are willing to accept a PR or should I make my own fork and implement this feature?
4. Another thing that I should have the control over are invoice and estimate numbers. I have seen few issues here on github about those saying that this will be implemented in the next major release. Do you have any time frame for that?
5. When fetching city names and counties in Croatia, I get "Shibenik" and "Drnish". That should be "Šibenik" and "Drniš". Maybe the collation on the database you are using for the demo is wrong or is that intentional?

Sorry for the long text, but I wanted to take the time to provide some feedback. I hope that you will find it to be constructive. Again, great work on the application. Congratulations!

**Comment by mohitpanjwani** [comment]
@mabasic Thanks a lot for the detailed feedback :)

1. How come you are giving it open source?
We're basically a Web & Mobile development agency and we wanted to build something for ourselves to manage invoices and track expenses etc. and then the idea grew and we decided to make it open-source to reach a much wider audience. We make money from client projects and this product would look pretty good on our portfolio and place us above the competition. Also, it would help us get more involved with the open-source/developer community. Also, We're looking to provide customization services for companies/individuals who would like to use Crater but with a few more features specific to them. As of now, we have definitely invested a lot of time and money into it but we don't have too many expectations from it in terms of money.

2. Are you willing to accept PRs for features?

We're definitely accepting PRs and any contribution is appreciated but I would suggest creating an issue or send me a personal message before working on something serious as it's possible that we might be working on the same thing. 

Also if someone can help us improve documentation, that would be a great start.

3. I think custom fields would be best for this kind of thing which is not needed for every user and the fields might differ for everyone, If you have that kind of time to help us build a custom-field feature then it would really great, if not then you can just fork it and customize it yourself but there's a big downside to this, as your application might break when you auto-update your app as we're constantly adding new versions with bug-fixes and features as we get more feedback. 

4. Custom invoice and estimate numbers are almost done but we were looking to release the update together with other features but those are incomplete so I think we'll just release a minor update if possible (hopefully at the end of this week, as we work on this part-time). 

5. Actually that has been fixed long ago but I haven't updated the demo yet as I am waiting for IOS Review to complete but it's taking forever. 
City and State are text fields now ( see issue #13 for more details) 

Please feel free to share any other feedback you have. 
Thanks
