### ISSUE TITLE
PDF Naming is broken when downloading 

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#381]
**Describe the bug**
When clicking the download pdf button (from PDF preview), the name gets additional `.pdf` suffix so it becomes a `INV-0001.pdf.pdf` by default.

**Expected behavior**
Only one .pdf should be used

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: Postgres 13

**Optional info**
- OS:  Ubuntu 20.04
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
This should no longer be an issue on latest update. 

Thanks for the feedback .

**Comment by lawzava** [comment]
This has not been fixed @mohitpanjwani 
![image](https://user-images.githubusercontent.com/19802246/147564447-3ad8dca7-c319-4ef1-813c-d09d2fc05b3a.png)

**Comment by mohitpanjwani** [comment]
> 

I'm still not able to reproduce this. 

Where exactly do you get this issue? Can you post the screenshot of the button / page which you're using to download the pdf?

**Comment by lawzava** [comment]
After creating an invoice I open the "view invoice mode" and click on the download button in the embedded PDF reader.
![image](https://user-images.githubusercontent.com/19802246/147744092-cc66e1e1-b8df-4968-9729-0569ccc20323.png)
