### ISSUE TITLE
Control generated number size for invoice name

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#382]
**Is your feature request related to a problem? Please describe.**
At the moment there are 6 digits for invoice numbers and they are not controllable. Although it is not impossible, it is not likely for freelancers to reach 1M invoices. And these 0s are quite confusing when doing accounting. 

**Describe the solution you'd like**
Control the size of the generated number length in some form, e.g. specifying a fixed amount of digits to use
Another option is to not show 0s. Only the real value so `INV-1, INV-2, ... INV-5655`

**Comment by TheZoker** [comment]
+1 for this request

I would prefer to set total amount of numbers. So when the option is set to 4, the number will be INV-0001, INV-0023 etc.
