### ISSUE TITLE
Add support for date-type invoice names

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#383]
**Is your feature request related to a problem? Please describe.**
Although incremental invoices are simple, often it's not the best solution due to privacy concerns.

**Describe the solution you'd like**
Add support for date-based invoice names. E.g. if I'd do 3 invoices today, it'd be `INV-2021-02-12-1, INV-2021-02-12-2, INV-2021-02-12-3` and then the next day the date changes and it starts from 1 again.

**Comment by muhammetasan** [comment]
what is prvacy concerns here ?

**Comment by sebastiancretu** [comment]
@lawzava you could follow https://github.com/bytefury/crater/issues/553. This should be fixed when that feature will be released. So i guess this could be closed.
