### ISSUE TITLE
Backups for PostgreSQL are not working

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#384]
**Describe the bug**
When trying to create a backup from PostgreSQL database it throws an error of `mysqldump: not found`

**Expected behavior**
Backup created successfully

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: Postgres 13

**Optional info**
- OS:  Ubuntu 20.04
- Browser: Chrome

Note: Spatie supports PostgreSQL backups natively, it's just missing in https://github.com/bytefury/crater/blob/master/config/backup.php#L77

**Comment by barf** [comment]
FWIW this looks like an issue with your hosting environment (not crater or laravel etc).

**Comment by barf** [comment]
Unable to reproduce this, backups work fine on PostgreSQL here.

Sounds more like a hosting/environment issue (trying to execute mysqldump when in fact the correct command on PostgreSQL is 'pg_dump')

**Comment by barf** [comment]
+1
I can reproduce this also

**Comment by azaricstefan** [comment]
+1 I can reproduce this also.

Maybe @mohitpanjwani update the docker configuration to include mysql-client?

**Comment by barf** [comment]
It's unrelated to docker and including a mysql client won't help when the DB is PostgreSQL...

but crater on PostgreSQL has bigger issues like #351 which prevent creating/updating invoices with this DB back-end, although that one may be a Laravel framework issue rather than one with crater.

**Comment by mohitpanjwani** [comment]
> +1 I can reproduce this also.
> 
> Maybe @mohitpanjwani update the docker configuration to include mysql-client?

That's right, we're missing the client on docker config. 

I'll push a commit + update to fix this. 

Thanks for the heads up.

**Comment by mohitpanjwani** [comment]
Fixed https://github.com/bytefury/crater/commit/6ecd9728d4f1f72d8f1c6b5bd60c1764d895a1b4

**Comment by mohitpanjwani** [comment]
For existing users, please pull the latest changes and run the below commands to fix this: 
1. run command docker-compose down
3. run command docker-compose build app
4. run command docker-compose up

-----
Basically I just added mariadb-client to Dockerfile:

![unknown](https://user-images.githubusercontent.com/8002555/121186800-14cb3780-c885-11eb-9ebf-d82d236ba891.png)
