### ISSUE TITLE
windows xamp 

### ISSUE THREAD

**Issue by ChiKaLiO** [bytefury/crater#387]
app.js?id=2fe48b55fc5693cab09f:2 TypeError: Cannot read property 'data' of undefined
    at app.js?id=2fe48b55fc5693cab09f:2
    at u (app.js?id=2fe48b55fc5693cab09f:2)
    at Generator._invoke (app.js?id=2fe48b55fc5693cab09f:2)
    at Generator.throw (app.js?id=2fe48b55fc5693cab09f:2)
    at xu (app.js?id=2fe48b55fc5693cab09f:2)
    at s (app.js?id=2fe48b55fc5693cab09f:2)

and in phpmyadmin between 22-31 tables are created

**Screenshots**
![image](https://user-images.githubusercontent.com/12167528/107834968-32393a80-6d98-11eb-9478-98100ac2af52.png)

**Please complete the following information:**
- Crater version: master 
- PHP version: 7.4
- Database type and version: mysql

**Optional info**
- OS:  windows
- Browser: chrome

**Comment by OumaDennisOmondi** [comment]
Am facing the same problem

**Comment by OumaDennisOmondi** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/34108493/108074450-415f0780-707a-11eb-8222-a5ed8c871a9e.png)

**Comment by ChiKaLiO** [comment]
i guess this happens with php 7.3..
