### ISSUE TITLE
VAT cannot be zeroed

### ISSUE THREAD

**Issue by ggiak** [bytefury/crater#39]
Hello there..

There are some cases where VAT is 0% zero between European countries while the Add New VAT won't let me add zero VAT.

I know I can skip the VAT part, although occasionally you might need to specifically write down its 0% VAT due to VIES invoices.

Screenshot:
![image](https://user-images.githubusercontent.com/20743694/70614417-322d3000-1c13-11ea-8164-09555ca524e9.png)

**Comment by ggiak** [comment]
Btw, Amazing Job :)

**Comment by mohitpanjwani** [comment]
@ggiak Thanks :) 

This issue has been fixed in the latest release:
https://github.com/bytefury/crater/releases/tag/2.1.0

You can update your app automatically from the settings page.
