### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by paverneuil** [bytefury/crater#395]
Hello,

**Describe the bug**
During the installation I get an error when creating the database. I could see previous issues of the same type but it didn't change anything.

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `label` varchar(255) not null, `model_type` varchar(255) not null, `type` varchar(255) not null, `placeholder` varchar(255) null, `options` json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answer` time null, `string_answer` text null, `number_answer` bigint unsigned null, `date_time_answer` datetime null, `is_required` tinyint(1) not null default '0', `order` bigint unsigned not null default '1', `company_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')`

**Expected behavior**
Installation of the environment 

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: Mysql 5.6
- Hosting OVH

**Optional info**
- OS:  WINDOWS
- Browser: EDGE

Thanks to you

**Comment by ggiak** [comment]
@paverneuil  customfield functionality (hence json fields on database) require MySQL 5.7+ or MariaDB 10.2.
