### ISSUE TITLE
Not Working Correctly

### ISSUE THREAD

**Issue by MuhammadUsmanAli0372** [bytefury/crater#396]
![Capture](https://user-images.githubusercontent.com/67306797/108596591-d11cf280-73a7-11eb-8bfe-375ec196df11.PNG)
**Describe the bug**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Crater version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by itsaboutcode** [comment]
@usman123Ali - Please try to install using docker.
