### ISSUE TITLE
The Mac is invalid

### ISSUE THREAD

**Issue by raulm090** [bytefury/crater#400]
Hi, when I am already in the onboarding to do the setup, I get the following error message.

<img width="534" alt="Captura de pantalla 2021-02-27 a las 17 58 26" src="https://user-images.githubusercontent.com/56694202/109395708-b0afe380-7925-11eb-9dc1-1cb987f8d788.png">

I have tried to enter the following command and the API Key it shows me, insert it in the .env, but without success. any solution?

`docker-compose exec app php artisan key:generate --show`

Thanks in advance.

**Comment by justRau** [comment]
Have you by any chance had another laravel installation in the folder with same name before?
If that installation set a laravel_session or maybe other cookie, this new installation is trying to decrypt it with a different APP key than before, therefore throws an error.

**Comment by yusuf** [comment]
Just clear browser cache or open in an incognito window and see if you can continue the installation process.
