### ISSUE TITLE
VAT is missing from billing address & Invoice Issuer.

### ISSUE THREAD

**Issue by ggiak** [bytefury/crater#41]
Many countries require that the VAT numbers to be written in the invoice.
both the issuer and the client.

![image](https://user-images.githubusercontent.com/20743694/70652743-d044e880-1c5b-11ea-903d-7c467b931b0f.png)

**Comment by eboye** [comment]
I was just about to ask for this feature.

VAT Number and Company registration number are needed in my country to be on invoice.

**Comment by mohitpanjwani** [comment]
We're working on a custom-fields feature that will allow you to add any extra fields you need on an Invoice.

**Comment by hypnodev** [comment]
+1

Any progress about this issues?

**Comment by thistehneisen** [comment]
Also very much looking forward to this resolved, I've just installed Crated — love it, but unfortunately without VAT — cannot use it.
