### ISSUE TITLE
Unable to complete setup

### ISSUE THREAD

**Issue by shayant98** [bytefury/crater#412]
**Describe the bug**
i get the 'Unauhtenticated message everytime i reach the mail setup part'
i checked the env many times but nothing worked

i've tried adding localhost,127.0.0.1,127.20.0.5 as the sactum  ip but nothing worked.

```
APP_ENV=production
APP_KEY=base64:XT6bIsrbXwtNdv1LUct29kwoAXy81CTR7MtvMPFI24E=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://crater.test

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=crater
DB_USERNAME=crater
DB_PASSWORD=crater

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=

SESSION_DRIVER=cookie
SESSION_LIFETIME=120

SANCTUM_STATEFUL_DOMAINS=192.168.19.12:85
SESSION_DOMAIN=192.168.19.12
```

**Expected behavior**
to be able to complete the setup

**Screenshots**
![image](https://user-images.githubusercontent.com/27793497/110837960-ac1df000-8280-11eb-96b8-1f443344c61f.png)

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: Mariadb 10

**Optional info**
- OS:  Raspberry Pi OS running inside a docker stack
- Browser: Safari

**Comment by BIIINO** [comment]
Hi,

exactly same sitation on my side i testeted everyting but no succes, is there any progress?

What i have done:
Ubuntu 18 and 20.04 tested with manual install and docker - same situation
Centos 7 tested with manual install and docker - same situation
Debian 10 tested with manual install and docker - same situation

Please, if you know how to fix that, let me know. thanks in advance.

BR

**Comment by BIIINO** [comment]
bro change settings to correct domain, you have to access to intsaller for example http://crater.local  .. in your case IP adress in browser window is problem

**Comment by shayant98** [comment]
What if i access it through the IP?

**Comment by MrFoxxington** [comment]
Having the same issue even when accessing via the correct URL.
Receive the unauthenticated message and can't actually proceed with the install.
![crater_install_error](https://user-images.githubusercontent.com/7933370/111220772-83279300-85d1-11eb-804d-8ecc74fb07bc.PNG)

Crater version: 4.0.4
PHP version: 7.4 (docker, 7.4-apache)
Database type and version: MySQL 8

**Comment by BIIINO** [comment]
@shayant98 if you want directly by IP i think its not possible. If you want to use it only localy, you can crate dns record on your router..
@MrFoxxington paste here please your .env  and show us your url in browser.

**Comment by mohitpanjwani** [comment]
This should no longer be an issue on 4.2.0. Please reopen if you encounter this again. 

We've added Domain Verification step on Installation Wizard to help verify the domain instead of redirecting to login if you enter a false URL / IP Address.
