### ISSUE TITLE
Mobile application language

### ISSUE THREAD

**Issue by BIIINO** [bytefury/crater#413]
My question is, how can i use default language (in my case Slovak language) in mobile application ? I use IOS platform and there is no option to use language, i set my language as default, but everythink in applicaiton is in english language. But in PDF also invoice generated by mobile, there is slovak - my default language.

Its possible to set whole aplication in default language - slovak ?

**Comment by mohitpanjwani** [comment]
@BIIINO Hey, Unfortunately the mobile app actually has different strings and translations. 

Because of that, we only support English on that right now. 

However, I can setup a Crowdin project same as we do for Crater web in order for other contributors to help us with that one.

**Comment by BIIINO** [comment]
Hi @mohitpanjwani yes sure, i am almost done with slovak language and i can share it. Its there any brute force way how to translate it now ? Which file has to be edited please ? Thanks in advance

**Comment by mohitpanjwani** [comment]
@BIIINO Here's the repository for mobile & the language files for it: https://github.com/bytefury/crater-mobile/tree/master/src/lang

**Comment by mohitpanjwani** [comment]
We don't have a guide but it should be pretty straightforward to do it if you're comfortable with js. 

you'll just have to import the language json file on https://github.com/bytefury/crater-mobile/blob/master/src/lang/i18n.js

**Comment by mohitpanjwani** [comment]
No the mobile app has separate translation files stored locally. We might look into fixing that in future but right now it does not download the files from server.

You can submit a PR to the above mentioned mobile repository, if you need any other language on mobile app, and we can release a new build on the current apps so it'll work as expected after its updated.

**Comment by BIIINO** [comment]
Hi @mohitpanjwani  please can you take a look at:
https://github.com/bytefury/crater-mobile/pull/14

Thank you in advancee and sorry for bothering, thats last step for me to deploy crater into production :)

**Comment by mohitpanjwani** [comment]
Closing this as your PR is now merged :)
