### ISSUE TITLE
Uploaded company logo disappears 

### ISSUE THREAD

**Issue by TheZoker** [bytefury/crater#416]
**Describe the bug**
When I upload a company logo (png) and refresh the page, the logo is gone

Edit: After inspecting the element with the browser dev tools, it seems, that the path used in the absolute path on the wbespace rather than the relative path to the logo. 

**Expected behavior**
Show the logo correctly. 

**Screenshots**
![Screenshot_2021 03 20_02h47m21s_003_](https://user-images.githubusercontent.com/1368405/111855768-bf872600-8926-11eb-83f9-4c4b89ac9919.png)

![Screenshot_2021 03 20_18h47m53s_009_](https://user-images.githubusercontent.com/1368405/111880621-cf494d80-89ac-11eb-83cf-faf7b38a7de4.png)

**Please complete the following information:**
- Crater version:  4.0.4
- PHP version: 7.4
- Database type and version: mysql 5.7.33

**Optional info**
- OS:  Windows 
- Browser: Chrome Edge

**Comment by TheZoker** [comment]
Fixed in: https://github.com/bytefury/crater/commit/7b95ccb5fc72eb696d9f16f1c90ab1aef9a8fc53

**Comment by ChiKaLiO** [comment]
Same thing on ubuntu, it is working on local machine windows , when i copied [7b95ccb](https://github.com/bytefury/crater/commit/7b95ccb5fc72eb696d9f16f1c90ab1aef9a8fc53) changes i got model not found ! i'm on an old build.. any thoughts ?
