### ISSUE TITLE
Uploading picture to Business Info

### ISSUE THREAD

**Issue by jessedewild** [bytefury/crater#422]
**Describe the bug**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generated_conversions' in 'field list' (SQL: insert into `media` (`name`, `file_name`, `disk`, `conversions_disk`, `collection_name`, `mime_type`, `size`, `custom_properties`, `generated_conversions`, `responsive_images`, `manipulations`, `model_id`, `model_type`, `uuid`, `order_column`, `updated_at`, `created_at`) values (media-libraryXwRQmc, 58544_Nerrbase_logo_H_08.png, public, public, logo, image/png, 89488, [], [], [], [], 1, Crater\Models\Company, 4fa92de9-f4ef-4ccf-a405-ee2c29f9c413, 1, 2021-03-20 20:11:15, 2021-03-20 20:11:15))

**Expected behavior**
Upload picture to Business

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 8.0
- Database type and version: MySQL

**Comment by mohitpanjwani** [comment]
Did you update the laravel-media-library package by any chance? We cannot reproduce this.
