### ISSUE TITLE
Install wizard stuck on Account Information

### ISSUE THREAD

**Issue by danielkaufman12** [bytefury/crater#429]
**Describe the bug**
Install wizard is stuck on the Account information stage after filling all the fields.

**Expected behavior**
I except to finish the installation wizard and start using the software.

**Screenshots**
![image](https://user-images.githubusercontent.com/67007278/112228252-b0132000-8c39-11eb-8320-b693121a7299.png)

**Please complete the following information:**
- Crater version: 4.04
- PHP version: 7.13
- Database type and version: I'm installing in **Digital Ocean**. I followed the instructions on the site.

**Optional info**
The email in the screenshot isn't a real email. I tried putting in my Gmail and got the same error as well.
- OS:   Ubuntu 20.4
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Hey, @danielkaufman12 did you get any error or does the button keep loading silently? 

You'll have to enable debugging by updating `.env` file: 
```
APP_DEBUG=true
```

After that try this again and see if you get any error. It would be better if you can keep your developer tools and see if you get any errors in console or network tab.

**Comment by danielkaufman12** [comment]
It keeps loading... No errors and I get an empty 200 code. I'll change to app debug. Is there anything else that come to mind? Maybe in the previous step I didn't configure the email correct?

**Comment by danielkaufman12** [comment]
Hi @mohitpanjwani I see that the app debug is True. But I don't see much in the network tab...

**Comment by mohitpanjwani** [comment]
I just saw your PHP Version now, the minimum PHP Version is `7.4`. Please update your PHP Version and try again.
