### ISSUE TITLE
 round(): Argument #1 ($num) must be of type int|float, string given 

### ISSUE THREAD

**Issue by Appendit** [bytefury/crater#430]
**Describe the bug**
When saving an invoice an error is thrown but its saved. if you want to view the pdf it gives the following error :  round(): Argument #1 ($num) must be of type int|float, string given 

**Expected behavior**
No error and a viewable pdf

**Screenshots**

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 8.0.1
- Database type and version: mysql

**Optional info**
- OS:  Shared Webhosting
- Browser: Firefox

Error log: https://flareapp.io/share/17xJVeam#F57

**Comment by mohitpanjwani** [comment]
Hey, this is an issue with PHP 8 with DOMPDF. 

Did you install Crater using Manual Zip file or did you clone the repository? 

If you cloned it, can you pull the changes and run `composer install`

That should fix the issues as I've updated the `barryvdh/laravel-dompdf` on composer.json yesterday.

**Comment by mohitpanjwani** [comment]
If you're using manual installation, just go to composer.json file and update this: 
`"barryvdh/laravel-dompdf": "^0.9.0",`

and run `composer update barryvdh/laravel-dompdf`

**Comment by Appendit** [comment]
i installed it by unzipping on a shared webspace. dont know if i can run "composer update barryvdh/laravel-dompdf". i fixed it by switching to php 7.4.14. thx for the quick repsonse!
