### ISSUE TITLE
round(): Argument #1 ($num) must be of type int|float, string given 

### ISSUE THREAD

**Issue by shanisingh03** [bytefury/crater#432]
Any PDF Invoice, Estimate,
<img width="785" alt="Screenshot 2021-03-24 at 4 44 40 PM" src="https://user-images.githubusercontent.com/22881049/112301917-75a09600-8cc0-11eb-955f-3fb2aac396df.png">
 or Reports Not Working Giving Error.

**Comment by DRogueRonin** [comment]
That's a [dompdf](https://github.com/dompdf/dompdf) issue with PHP 8. Seems like they fixed in in this PR though https://github.com/dompdf/dompdf/pull/2313

**Comment by mohitpanjwani** [comment]
This issue should be fixed on latest update. Please reopen if you still encounter this.
