### ISSUE TITLE
Unable to run setup.sh - WSL2

### ISSUE THREAD

**Issue by Dulanic** [bytefury/crater#435]
**Describe the bug**
When following the install guide at https://docs.craterapp.com/installation.html#docker-installation but I am getting the following error:
Composer could not find a composer.json

I also attempted to run on my ubuntu server and received the same error.

**Expected behavior**
The instructions complete as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/2948206/112709033-e8a63a00-8e83-11eb-8056-04b6490ad464.png)

**Please complete the following information:**
- Crater version:  N/A
- PHP version:  N/A
- Database type and version:  N/A

**Optional info**
- OS:  WSL2 also tried Ubuntu 20.04

**Comment by Astrek2000** [comment]
I know this is closed but still leaving a comment, if someone stumbles across this.

Basically this is because you might have mounted the wrong file path in the docker-compose.yml file. Make sure that the whole crater folder is mounted to  "/var/www" path.
