### ISSUE TITLE
Make SMTP username & password not mandatory

### ISSUE THREAD

**Issue by fritzmg** [bytefury/crater#438]
**Is your feature request related to a problem? Please describe.**
During the setup wizard / on-boarding process, the step **Mail Configuration** asks you for the SMTP credentials, if you select `smtp`. However, the username & password fields are mandatory, which makes it inconvenient to set up an SMTP server that does not require any credentials (e.g. an SMTP relay from Google G Suite or Microsoft Office 365).

**Describe the solution you'd like**
The username and password for SMTP credentials should not be mandatory.

**Describe alternatives you've considered**
As a workaround I just have to enter random credentials and then remove them later from the `.env` file.

**Comment by mohitpanjwani** [comment]
Right! Thanks for the feedback :)

We'll make these fields optional.
