### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by tobidwest** [bytefury/crater#442]
**Describe the bug**
When setting a custom field to not be required and hitting the save button, it still is required and displayed as required when opening the edit dialoge again.

**Expected behavior**
It shouldn't be required.

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: Not applicable
- Database type and version: Not applicable

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/bytefury/crater/releases/tag/4.1.0
