### ISSUE TITLE
Error on installation. Not showing literally nothing on screen.

### ISSUE THREAD

**Issue by realrodri** [bytefury/crater#457]
Tried to install Crater on my Synology. Didn't work because I don't know the f*** why. Tried to install it on my local Apache server and neither. When I enter the installation on "public" folder, nothing shows up. A blank screen and a title saying "Crater" and greeting me, but nothing on screen.

**Comment by realrodri** [comment]
Ended up dropping it on my hosting provider with all the PHP modules installed by default. More easy. Thanks to the developer, I could try it in real time. Such a wonderful job. Congratulations! 🎉

**Comment by netspear** [comment]
is there an update to is?
I also tried the manual. didn't work
