### ISSUE TITLE
reCAPTCHA / Captcha for login area to prevent bruteforce attacks

### ISSUE THREAD

**Issue by realrodri** [bytefury/crater#459]
**Is your feature request related to a problem? Please describe.**
If there's no captcha, people can bruteforce passwords until they want.

**Describe the solution you'd like**
If a captcha is implemented or an option can be placed, this type of attack can be stopped.

**Describe alternatives you've considered**
Maybe considering other Open Source Captchas or the official one from Google? 👀

**Comment by realrodri** [comment]
Does it work with the Crater iPhone/Android app with that enabled? 👀

**Comment by fazalfarhan01** [comment]
I haven't tested with the __under attack mode__ 'enabled', so can't comment anything about that.

But with the regular DDOS Protection in 'Cloudflare Proxy' mode with 'https' rewrite enabled works flawlessly.

**Comment by realrodri** [comment]
I tried to register on Cloudfare to try that out, but it seems you need to do several configurations to the DNS in order to get that feature. That exceeds my current knowledge. Isn't there more simple? :'(

**Comment by fazalfarhan01** [comment]
Sorry. I don't recall any other alternative to that. 
Incase you decide to use cloudflare, here are the basic configuration steps.

But a domain name if you do not have it already, or get 1 for free from freenom. I don't recommend it, but hey.. it's free and could be used for testing.

# Add your domain to cloudflare
For this all you need to do is point your existing name servers on your domain provider to that of cloudflare's.
- They are usually like `abcdxyzt.cloudflare.com`

# Point the domain to your IP
To do this, add a DNS `A record` for your root domain or subdomain and point it to o your IP.
## Note: This will work only with a static IP. If you have a dynamic IP, you could use Cloudflare's client software to automatically update the IP address.

No other changes or configuration are needed. Optionally you can turn on an option to redirect all http traffic to https.

This is all that's needed on cloudflare.

You could always mail me if you need more assistance. Happy to help 😃.

**Comment by mohitpanjwani** [comment]
Laravel protects against this by default using Login Throttling: https://laravel.com/docs/8.x/authentication#login-throttling

You can see this here: https://github.com/bytefury/crater/blob/512983deee95db339466e48102d982806e1d6d18/app/Http/Kernel.php#L46
