### ISSUE TITLE
Crater Android: Why is this happening?

### ISSUE THREAD

**Issue by secrethash** [bytefury/crater#46]
I recently updated my Crater Application to `v2.0.2` and then the android app stopped working. So I uninstalled and reinstalled the android app, it started working again. So after a day now, again my android app stopped working.

# Screenshots
![](https://i.imgur.com/kBPUu5k.png)
![](https://i.imgur.com/ssXBJkA.jpg)

**Comment by mohitpanjwani** [comment]
Hey @secrethash. 

There's an issue with forcing versions on major updates thus It currently does not work with the latest 2.0+. 

We're releasing an update in the next few hours for android which will fix this issue.

**Comment by secrethash** [comment]
Thanks @mohitpanjwani , that explains it pretty well.

**Comment by mohitpanjwani** [comment]
Just published the android build! Please check and let me know if it fixes your issue after updating your app.

**Comment by secrethash** [comment]
Yes, it's fixed after updating the application. Thanks a lott. Probably should close the issue
