### ISSUE TITLE
Cant install Crater - No Error Message

### ISSUE THREAD

**Issue by DanielK1511** [bytefury/crater#461]
**Describe the bug**
Hello, I can't install Crater, When I put my DB Data into the respective field and click on Save and Continue nothing happens. It just loads for a second and nothing happens.

**Expected behavior**
continuing the Setup process

**Screenshots**
Its the normal db installation screen, nothing out of the ordinary

**Please complete the following information:**
- Crater version: 4.1.0
- PHP version: 7.4.3
- Database type and version: mysql

**Optional info**
- OS:  Windows 10
- Browser: Opera GX

**Comment by anaryk** [comment]
Same problem with docker instance.

**Comment by DanielK1511** [comment]
Just tried an older Version, wich said i had a few blocked php functions. Enabled these and it works now.

**Comment by paishin** [comment]
Having the same issue, could you please share some what details on what needs to be done?

**Comment by DanielK1511** [comment]
> Having the same issue, could you please share some what details on what needs to be done?

I activated some php functions that my control panel has blocked, i dont know what specifically but you should be fine with installing an old version of crater. You also might need to contact your hosting provider to enable these functions, if you are not using your own Server.

**Comment by mohitpanjwani** [comment]
There’s an issue with notifications not showing up on installation wizard. 

It will be fixed in next week’s update.

**Comment by paishin** [comment]
Followed your advice and installed an earlier version of the application which indeed shows the error messages. 
The error I am getting is the following:

`"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `label` varchar(255) not null, `model_type` varchar(255) not null, `type` varchar(255) not null, `placeholder` varchar(255) null, `options` json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answer` time null, `string_answer` text null, `number_answer` bigint unsigned null,"`

Not quite sure how I can fix this, any help or pointers appreciated.

**Comment by DanielK1511** [comment]
> Followed your advice and installed an earlier version of the application which indeed shows the error messages. 
> 
> The error I am getting is the following:
> 
> 
> 
> `"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `label` varchar(255) not null, `model_type` varchar(255) not null, `type` varchar(255) not null, `placeholder` varchar(255) null, `options` json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answer` time null, `string_answer` text null, `number_answer` bigint unsigned null,"`
> 
> 
> 
> Not quite sure how I can fix this, any help or pointers appreciated.

I think your MySQL needs an update

**Comment by DanielK1511** [comment]
> Followed your advice and installed an earlier version of the application which indeed shows the error messages. 
> 
> The error I am getting is the following:
> 
> 
> 
> `"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `label` varchar(255) not null, `model_type` varchar(255) not null, `type` varchar(255) not null, `placeholder` varchar(255) null, `options` json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answer` time null, `string_answer` text null, `number_answer` bigint unsigned null,"`
> 
> 
> 
> Not quite sure how I can fix this, any help or pointers appreciated.

Its best if you create a new issue for this.

**Comment by paishin** [comment]
Most probably it requires mysql 7+, I am currently running 5.6. 
I will test and let you know

**Comment by paishin** [comment]
Updated to 5.7 and all worked perfectly. Thanks for your support
