### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by cbunnag** [bytefury/crater#468]
**Describe the bug**
Cannot login with ip address http://192.168.1.129/login
When I login, the page show message logout successfully and back to login page (as attached screenshot)
But http://localhost/login works fine.
login with the same computer and browser
Install creater with Docker

**Screenshots**
![crater](https://user-images.githubusercontent.com/81414379/118232494-d8413180-b4ba-11eb-932a-8298a62f4a81.jpg)

**Please complete the following information:**
- Crater version: 4.1.0
- PHP version: PHP 7.4.3
- Database type and version: mariadb

**Optional info**
- OS:  ubuntu-20.04.2.0-desktop-amd64
- Browser: chrome, firefox

**Comment by ByWaleed** [comment]
Hi @cbunnag. Did you manage to get the login working after this issue?
