### ISSUE TITLE
cannot pass the 3rd part of setup

### ISSUE THREAD

**Issue by ikb205** [bytefury/crater#470]
hi guys,
please can you help me terminate the setup
thank you in advance

![image](https://user-images.githubusercontent.com/35666889/118398658-79fa8700-b651-11eb-8c3b-75e5b6c5a159.png)

**Comment by mwikala** [comment]
Hi @ikb205, at first glance it looks like you're doing a **Manual** installation but in the App Domain field, you're entering an invalid domain name. It should be `127.0.0.1:8000` or `localhost:8000`
