### ISSUE TITLE
Trusted proxies should be configurable

### ISSUE THREAD

**Issue by patricklucas** [bytefury/crater#473]
**Is your feature request related to a problem? Please describe.**
In order to run behind a reverse proxy, you seem to need to modify a source file, [TrustProxies.php](https://github.com/bytefury/crater/blob/4.1.0/app/Http/Middleware/TrustProxies.php#L14), as hinted at by @SteveEdson on https://github.com/bytefury/crater/issues/340#issuecomment-764573170.

**Describe the solution you'd like**
An environment configuration option, such as `TRUSTED_PROXIES`, that populates this variable. (Invoice Ninja, a similar project also based on Laravel, [has such an option](https://github.com/invoiceninja/invoiceninja/blob/cbac71435e1bf37322e2568e07fc81fbc8831128/docs/configure.rst#using-a-reverse-proxy))

**Describe alternatives you've considered**
Currently, I'm using `sed` in my Dockerfile to effectively patch this in, but that's clearly far from ideal. Having this option would mean the entire application is configurable for my needs for running in production with only `.env` and environment variables.

-----

I haven't had a chance to really try things out yet, but I'm looking forward to it. Thanks for developing and maintaining this project!

**Comment by mohitpanjwani** [comment]
Hey, Thanks for the feedback. Trusted proxies can now be configured from the .env file. 

```
TRUSTED_PROXIES="*"
```
