### ISSUE TITLE
Cloned invoice loses chosen template

### ISSUE THREAD

**Issue by patricklucas** [bytefury/crater#474]
**Describe the bug**
When cloning an invoice that does not use Template 1, the cloned invoice has been reset to Template 1.

**Expected behavior**
The choice of template should be kept when cloning.

**Screenshots**

Invoice to be cloned:

![image](https://user-images.githubusercontent.com/95053/118800144-df43b780-b89f-11eb-8288-c34fdd2e6705.png)

Cloned invoice:

![image](https://user-images.githubusercontent.com/95053/118800182-eb2f7980-b89f-11eb-8e89-91a2465b99ad.png)

**Please complete the following information:**
- Crater version: 4.1.0 (git)
- PHP version: from docker-compose setup
- Database type and version: from docker-compose setup

**Comment by mohitpanjwani** [comment]
Fixed on https://github.com/bytefury/crater/commit/3f0008ec958ec5b10862861ea3d3e86bdb9c9236
