### ISSUE TITLE
Feature Suggestion: On premises backup

### ISSUE THREAD

**Issue by secrethash** [bytefury/crater#48]
This would be a feature that could be implemented later but I seriously think it should be implemented first as Crater is being used by many already in production.

# Implementation
This can be achieved by using a wonderful library provided by Spatie [spatie/laravel-backup](https://github.com/spatie/laravel-backup).

# Features
- [ ] Schedule Runners for auto-backup
- [ ] One click backup from Settings page
- [ ] Downloading functionality for the latest backup
- [ ] Cleanup Utility to clean previous backups and auto-cleaning
- [ ] Auto-backup before updating

P.S.: Please also add a contribution guide to the repo. I would really like to contribute.

**Comment by jpmurray** [comment]
I've just started to move my own half-backed in house solution for billing to Crater, and this is the only thing that's missing for me.

If we could get a contribution guide, or at least pointers of what we should do or not if we submit PRs, I'd very much like to also see spatie's packages. It should be a breeze to implement!

**Comment by mohitpanjwani** [comment]
Backups are added to V4. 

We're thinking about Cleanup utility & scheduled back next.
