### ISSUE TITLE
Unable to pass Site URL & Database

### ISSUE THREAD

**Issue by bakfiets2** [bytefury/crater#481]
Hi all.

So i am trying to install Crater on my webserver. But it is stuck at Site URL & Database.
After filling in all the settings. I hit save. Then nothing happens. I can see in the .env that the settings are there. ALso the database is filled with info.

Does anyone have a clue?

**Comment by bakfiets2** [comment]
Will try!

**Comment by bakfiets2** [comment]
Getting the error. Database should be empty. If i start with a empty DB. It adds al the records. And gives the error."


error | "database_should_be_empty"
-- | --

**Comment by bakfiets2** [comment]
Problem solved. Mariadb was running on version 10.1. Took a while to get it figured out.

**Comment by flamekiller22** [comment]
> Problem solved. Mariadb was running on version 10.1. Took a while to get it figured out.

Which version does it need to be?

**Comment by jumban** [comment]
Hi, facing the same issue here, getting stuck at the "Site URL & Database" page. What version of MariaDB should I use? 

I have tried setting up with MariaDB version 5.5.64 instead but still facing the same issue. Any help will be greatly appreciated, thanks!

**Comment by flamekiller22** [comment]
Sorry but I stopped using crater so don't quite remember what I used.
