### ISSUE TITLE
Euro sign wrong

### ISSUE THREAD

**Issue by julian08100** [bytefury/crater#484]
The Euro sign is placed after the price, instead of the correct Dutch way. How can I edit that ?

**Comment by mohitpanjwani** [comment]
> The Euro sign is placed after the price, instead of the correct Dutch way. How can I edit that ?

Hey! You can change that from currencies table -> `swap_currency_symbol` column.

**Comment by julian08100** [comment]
How can I access the DB Table on Mac ?

**Comment by mohitpanjwani** [comment]
> How can I access the DB Table on Mac ?

You can use TablePlus app to access your db on mac.
