### ISSUE TITLE
Invalid number parsed.

### ISSUE THREAD

**Issue by swiffer** [bytefury/crater#487]
**Describe the bug**
When trying to save an Invoice i'm getting an "Invalid number parsed." - error.

**Expected behavior**
The Invoice should be saved just fine.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2990373/120343862-5b56ea00-c2f9-11eb-9cce-abe67ceb799c.png)

**Please complete the following information:**
- Crater version: 4.1.0
- PHP version: 8.0.6
- Database type and version: MariaDB 10.5

**Optional info**
- OS:  Ubuntu
- Browser: firefox 90

**Comment by mohitpanjwani** [comment]
This should work in the latest version. Please update your Crater version to see if it fixes it. 

Otherwise you can reopen the issue.
