### ISSUE TITLE
Crater goes to on-boarding after few hours when deployed on Heroku

### ISSUE THREAD

**Issue by ByWaleed** [bytefury/crater#489]
After having deployed a fresh copy of Crater to Heroku, which includes going through the initial on-boarding process, the application is setup and works fine. However, when visiting the site after few hours, the app goes back to on-boarding. Nothing is changed during this period, including the source files, permissions and database. 

I have deployed the application 7 times in past 2 days trying various things but nothing seemed to work. When running locally, app worked fine, even after testing with hours of time gaps. I think it could be something with how Heroku run the application. Is there something I'm missing or need to be aware of?

- Crater version: 4.1
- PHP version:  8
- Database type and version: PostgreSQL

**Comment by mohitpanjwani** [comment]
> After having deployed a fresh copy of Crater to Heroku, which includes going through the initial on-boarding process, the application is setup and works fine. However, when visiting the site after few hours, the app goes back to on-boarding. Nothing is changed during this period, including the source files, permissions and database.
> 
> I have deployed the application 7 times in past 2 days trying various things but nothing seemed to work. When running locally, app worked fine, even after testing with hours of time gaps. I think it could be something with how Heroku run the application. Is there something I'm missing or need to be aware of?
> 
> * Crater version: 4.1
> * PHP version:  8
> * Database type and version: PostgreSQL

Hey, I personally never used Heroku but does your `storage/app` directory get deleted somehow? 

Crater stores `database_created` file on this path when you complete onboarding to indicate that you've completed the installation and no longer need to be redirected to onboarding wizard. 

I suppose that this file is getting deleted somehow which might be causing this issue.

**Comment by ByWaleed** [comment]
Issue here was that Heroku uses ephemeral filesystem, which is only suitable for temporary storage.

> The Heroku filesystem is ephemeral - that means that any changes to the filesystem whilst the dyno is running only last until that dyno is shut down or restarted. Each dyno boots with a clean copy of the filesystem from the most recent deploy. This is similar to how many container based systems, such as Docker, operate.

Source: https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

  Alternatives are to either update the Crater source code to not check files on local storage or use [cloud storage](https://elements.heroku.com/addons) such as [AWS S3](https://devcenter.heroku.com/articles/s3-upload-php), if using the Heroku platform.

@mohitpanjwani thanks for the finding and sharing the above article.
