### ISSUE TITLE
[Docker] setup.sh throws error on PHP 7.4 and subsequently onboarding fails on SQL init

### ISSUE THREAD

**Issue by DeeprajPandey** [bytefury/crater#496]
**Describe the bug**
`./docker-compose/setup.sh` throws warnings about PHP versions on 7.4.20.
The exact warning is in the screenshot below. It says: `Your lock file does not contain a compatible set of packages. Please run composer update.`
Running `composer update --lock` does not fix the warning.

If I continue with the server, it fails on the Site URL & Database step, and throws the following error: `"Call to undefined function Crater\\Space\\mysqli_get_client_info()"`.

**Expected behavior**
The database is created and onboarding resumes.

**Screenshots**
I am attaching a [link with the HTTP error response](https://gist.github.com/DeeprajPandey/abe2eaf33be1d57041ede32cc37a1ee2) which has the call stack. It says the error is in `line 150` in `app/Space/RequirementsChecker.php`.

Before the server was up, when I ran `./docker-compose/setup.sh`, it complained that `php8.0` was not installed and `php v7.4.20` does not satisfy the requirement for `psr/cache`. Here's a screenshot of that error.
<img width="990" alt="Screenshot 2021-06-25 at 14 49 06" src="https://user-images.githubusercontent.com/15888623/123401503-806f0d80-d5c4-11eb-8887-025c4348926c.png">

I have also tried changing the Docker PHP base image from `7.4-fpm` on line 1 of the Dockerfile to `php:fpm` as well as `php:8.1.0alpha1-fpm-buster`. Followed by a `composer update --lock` and a container rebuild however the same error persists and 

**Please complete the following information:**
- Crater version: 4.2.0 (switched to the tagged release on master before running docker-compose)
- PHP version: 7.4.20 (Dockerized 7.4-fpm)
- Database type and version: sql

**Optional info**
- OS:  Ubuntu 20.04
- Browser: Firefox 89.0.1

**Comment by mohitpanjwani** [comment]
> **Describe the bug**
> `./docker-compose/setup.sh` throws warnings about PHP versions on 7.4.20.
> The exact warning is in the screenshot below. It says: `Your lock file does not contain a compatible set of packages. Please run composer update.`
> Running `composer update --lock` does not fix the warning.
> 
> If I continue with the server, it fails on the Site URL & Database step, and throws the following error: `"Call to undefined function Crater\\Space\\mysqli_get_client_info()"`.
> 
> **Expected behavior**
> The database is created and onboarding resumes.
> 
> **Screenshots**
> I am attaching a [link with the HTTP error response](https://gist.github.com/DeeprajPandey/abe2eaf33be1d57041ede32cc37a1ee2) which has the call stack. It says the error is in `line 150` in `app/Space/RequirementsChecker.php`.
> 
> Before the server was up, when I ran `./docker-compose/setup.sh`, it complained that `php8.0` was not installed and `php v7.4.20` does not satisfy the requirement for `psr/cache`. Here's a screenshot of that error.
> <img alt="Screenshot 2021-06-25 at 14 49 06" width="990" src="https://user-images.githubusercontent.com/15888623/123401503-806f0d80-d5c4-11eb-8887-025c4348926c.png">
> 
> I have also tried changing the Docker PHP base image from `7.4-fpm` on line 1 of the Dockerfile to `php:fpm` as well as `php:8.1.0alpha1-fpm-buster`. Followed by a `composer update --lock` and a container rebuild however the same error persists and
> 
> **Please complete the following information:**
> 
> * Crater version: 4.2.0 (switched to the tagged release on master before running docker-compose)
> * PHP version: 7.4.20
> * Database type and version: sql
> 
> **Optional info**
> 
> * OS:  Ubuntu 20.04
> * Browser: Firefox 89.0.1

The composer issue was fixed yesterday, so if you pull again it should work. 

I can reproduce the mysqli_get_client_info() error though! we should be using $pdo->getAttribute(PDO::ATTR_SERVER_VERSION); or something instead of that. 

We're working on fixing this today. Thanks for the feedback.

**Comment by mohitpanjwani** [comment]
Meanwhile if you wish to fix it to install Crater, just update the function (getMysqlVersionInfo) on the file: `app/Space/RequirementsChecker.php` to below: 

```
    /**
     * Get current Mysql version information.
     *
     * @return string
     */
    private static function getMysqlVersionInfo()
    {
        return '5.8.0';
    }
```

**Comment by DeeprajPandey** [comment]
> > **Describe the bug**
> > `./docker-compose/setup.sh` throws warnings about PHP versions on 7.4.20.
> > The exact warning is in the screenshot below. It says: `Your lock file does not contain a compatible set of packages. Please run composer update.`
> > Running `composer update --lock` does not fix the warning.
> > If I continue with the server, it fails on the Site URL & Database step, and throws the following error: `"Call to undefined function Crater\\Space\\mysqli_get_client_info()"`.
> > **Expected behavior**
> > The database is created and onboarding resumes.
> > **Screenshots**
> > I am attaching a [link with the HTTP error response](https://gist.github.com/DeeprajPandey/abe2eaf33be1d57041ede32cc37a1ee2) which has the call stack. It says the error is in `line 150` in `app/Space/RequirementsChecker.php`.
> > Before the server was up, when I ran `./docker-compose/setup.sh`, it complained that `php8.0` was not installed and `php v7.4.20` does not satisfy the requirement for `psr/cache`. Here's a screenshot of that error.
> > <img alt="Screenshot 2021-06-25 at 14 49 06" width="990" src="https://user-images.githubusercontent.com/15888623/123401503-806f0d80-d5c4-11eb-8887-025c4348926c.png">
> > I have also tried changing the Docker PHP base image from `7.4-fpm` on line 1 of the Dockerfile to `php:fpm` as well as `php:8.1.0alpha1-fpm-buster`. Followed by a `composer update --lock` and a container rebuild however the same error persists and
> > **Please complete the following information:**
> > 
> > * Crater version: 4.2.0 (switched to the tagged release on master before running docker-compose)
> > * PHP version: 7.4.20
> > * Database type and version: sql
> > 
> > **Optional info**
> > 
> > * OS:  Ubuntu 20.04
> > * Browser: Firefox 89.0.1
> 
> The composer issue was fixed yesterday, so if you pull again it should work.
> 
> I can reproduce the mysqli_get_client_info() error though! we should be using $pdo->getAttribute(PDO::ATTR_SERVER_VERSION); or something mysqli function as that extension is not included on dockerfile.
> 
> We're working on fixing this today. Thanks for the feedback.

Hi, thank you for this. I was working on a repo that I pulled yesterday.
Started from a fresh copy again and the `setup.sh` error did not show up. However, there's a new error. Here's a screenshot:
![Screenshot 2021-06-25 at 15 39 04](https://user-images.githubusercontent.com/15888623/123409137-7a305f80-d5cb-11eb-8773-13d931a5b7f5.png)

I will try changing the RequirementChecker file and see if that works with the tagged Crater 4.2.0 release.

**Comment by mohitpanjwani** [comment]
https://docs.craterapp.com/installation.html#docker-installation

As given in the documentation, did you copy the .env file? 
```
cp .env.example .env
```

**Comment by DeeprajPandey** [comment]
Ah, my bad.

Works now. For people who come here later, I am on commit 512983d on `master` which has the updated composer lock file.

Thanks!

**Comment by salazarp** [comment]
> Meanwhile if you wish to ignore this and install Crater, just update the function `getMysqlVersionInfo` on the file: `app/Space/RequirementsChecker.php` to below:

Thank you, this just worked for me --the installer carried on. Had almost given up upgrading :-0

**Comment by mohitpanjwani** [comment]
Great! 

This should no longer be an issue. We've fixed this by adding an extra check for mariadb: https://github.com/bytefury/crater/commit/2ec87baa6fcf59513f997eb82186962e31d5f13e

**Comment by virgil9306** [comment]
Hi @mohitpanjwani , I am still seeing this issue on v`4.2.0` -- is 2ec87baa6fcf59513f997eb82186962e31d5f13e not available yet? 

In the meantime I had to do the workaround as follows:

1) Your above comment at https://github.com/bytefury/crater/issues/496#issuecomment-868384816
2) Set directory permissions manually for everything (I wasn't able to resolve `1001` vs `1000` UID issues)
