### ISSUE TITLE
Error on a Hostinger account, Symlink() has been disabled for security reasons

### ISSUE THREAD

**Issue by andergmartins** [bytefury/crater#498]
**Describe the bug**
I can't install on a Hostinger account. I received an error message after I try to confirm the database settings:

```
Symlink() has been disabled for security reasons
```

 I added the files to a folder which is not using symlink.

**Expected behavior**
I would like to be able to install it.

**Screenshots**
<img width="1428" alt="Screen Shot 2021-07-04 at 14 46 09" src="https://user-images.githubusercontent.com/407131/124394634-aa1be900-dcd6-11eb-8b89-7c48d9b4d909.png">

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4.11
- Database type and version: MariaDB 10.4.14

**Optional info**
- OS:  MacOS
- Browser: brave

**Comment by mohitpanjwani** [comment]
> **Describe the bug**
> I can't install on a Hostinger account. I received an error message after I try to confirm the database settings:
> 
> ```
> Symlink() has been disabled for security reasons
> ```
> 
> I added the files to a folder which is not using symlink.
> 
> **Expected behavior**
> I would like to be able to install it.
> 
> **Screenshots**
> <img alt="Screen Shot 2021-07-04 at 14 46 09" width="1428" src="https://user-images.githubusercontent.com/407131/124394634-aa1be900-dcd6-11eb-8b89-7c48d9b4d909.png">
> 
> **Please complete the following information:**
> 
> * Crater version: 4.2.0
> * PHP version: 7.4.11
> * Database type and version: MariaDB 10.4.14
> 
> **Optional info**
> 
> * OS:  MacOS
> * Browser: brave

Symlink is required to point the storage/app folder to public directory. Otherwise your images won’t work.

**Comment by mohitpanjwani** [comment]
I am not completely sure but can you try to comment this line: https://github.com/bytefury/crater/blob/2ec87baa6fcf59513f997eb82186962e31d5f13e/app/Http/Controllers/V1/Onboarding/DatabaseConfigurationController.php#L42


Run the installer again and see if it fixes the issue. You will get through the wizard but the local disk images might not work. 

You can try to use a different disk driver under Settings - Disks page.

**Comment by andergmartins** [comment]
Thanks @mohitpanjwani. Commenting that line worked allowing to go to the next step in the installation. But I was blocked again due to another issue:

<img width="1146" alt="Screen Shot 2021-07-04 at 21 33 35" src="https://user-images.githubusercontent.com/407131/124404066-aa84a600-dd0f-11eb-8d39-d04b6aa0e472.png">

I'm not sure it is related to something else, or if it is a side effect of the workaround we tried.

I'm using a subdomain for my installation, added it to the field on that page.

**Comment by andergmartins** [comment]
Btw, I have enabled the function "symlink" and it "fixed" the first error message I reported. Considering this happened on the default configuration for Hostinger, I'm assuming it might happens on another servers. Maybe you could add a check in the installation steps checking if the "symlink" function is enabled?

**Comment by mohitpanjwani** [comment]
> Btw, I have enabled the function "symlink" and it "fixed" the first error message I reported. Considering this happened on the default configuration for Hostinger, I'm assuming it might happens on another servers. Maybe you could add a check in the installation steps checking if the "symlink" function is enabled?
> 
> But I'm still stuck in the domain verification error.
> 
> <img alt="Screen Shot 2021-07-04 at 21 56 49" width="1126" src="https://user-images.githubusercontent.com/407131/124404804-d81f1e80-dd12-11eb-96e7-6b90210f34c5.png">

Are you accessing the Crater's installation wizard from this URL itself?

**Comment by mohitpanjwani** [comment]
> Btw, I have enabled the function "symlink" and it "fixed" the first error message I reported. Considering this happened on the default configuration for Hostinger, I'm assuming it might happens on another servers. Maybe you could add a check in the installation steps checking if the "symlink" function is enabled?
> 
> But I'm still stuck in the domain verification error.
> 
> <img alt="Screen Shot 2021-07-04 at 21 56 49" width="1126" src="https://user-images.githubusercontent.com/407131/124404804-d81f1e80-dd12-11eb-96e7-6b90210f34c5.png">

That's a good point. We'll add that check.

**Comment by andergmartins** [comment]
> > Btw, I have enabled the function "symlink" and it "fixed" the first error message I reported. Considering this happened on the default configuration for Hostinger, I'm assuming it might happens on another servers. Maybe you could add a check in the installation steps checking if the "symlink" function is enabled?
> > But I'm still stuck in the domain verification error.
> > <img alt="Screen Shot 2021-07-04 at 21 56 49" width="1126" src="https://user-images.githubusercontent.com/407131/124404804-d81f1e80-dd12-11eb-96e7-6b90210f34c5.png">
> 
> Are you accessing the Crater's installation wizard from this URL itself?

Yes, I was. But just tried again, and it worked this time.

**Comment by andergmartins** [comment]
> > Btw, I have enabled the function "symlink" and it "fixed" the first error message I reported. Considering this happened on the default configuration for Hostinger, I'm assuming it might happens on another servers. Maybe you could add a check in the installation steps checking if the "symlink" function is enabled?
> > But I'm still stuck in the domain verification error.
> 
> That's a good point. We'll add that check.

@mohitpanjwani  Cool, thanks. All seems fine now. I'm able to use the software.

**Comment by muhammedaksam** [comment]
> I am not completely sure but can you try to comment this line:
> 
> https://github.com/bytefury/crater/blob/2ec87baa6fcf59513f997eb82186962e31d5f13e/app/Http/Controllers/V1/Onboarding/DatabaseConfigurationController.php#L42
> 
> Run the installer again and see if it fixes the issue. You will get through the wizard but the local disk images might not work.
> 
> You can try to use a different disk driver under Settings - Disks page.

Commenting that line like @mohitpanjwani said worked for passing that symlink error but just like @andergmartins I am stuck at domain verification step too.

**Comment by andergmartins** [comment]
Hi @muhammedaksam 

Did you try (if possible on your host) enabling the function "symlink" on the PHP settings? Is that module enabled?
The issue was only fixed after I activated it.

**Comment by sebadamus** [comment]
Also in Hostinger, could fix the symlink error just enabling it from the Hostinger Panel.  Thanks!
