### ISSUE TITLE
wizard.errors.undefined during on-boarding process

### ISSUE THREAD

**Issue by Benjamest** [bytefury/crater#5]
Hi,

On the Site URL & Database page I input all the data fields and click save & continue. The script populates the database, getting as far as 30 tables and 58 rows before responding with 

```
{
"message": "Server Error"
}
```

Could you advise how to go about resolving this?

Current system:
PHP: 7.2.5
MYSQL: 5.7.22
Apache: 2.4.33 (Win32)

**Comment by Benjamest** [comment]
Nevermind. It was a max_execution_time issue.

**Comment by claudemifsud** [comment]
Most freelancers & small businesses start on a shared hosting environment, having a low execution time set by the hosting providers. This process is ideally amended to allow installation on such environments.

**Comment by mohitpanjwani** [comment]
> Most freelancers & small businesses start on a shared hosting environment, having a low execution time set by the hosting providers. This process is ideally amended to allow installation on such environments.

We'll look into making this step perform better so it runs smoothly on lower execution time. or maybe we could try splitting the tasks into 2 different steps. 

In the current version, the database step does most of the work.

**Comment by amanijoseph87** [comment]
I have the same error on a shared host, is there any workaround,
