### ISSUE TITLE
Can`t Install [Mysql Step]

### ISSUE THREAD

**Issue by BaxAndrei** [bytefury/crater#506]
**Describe the bug**
I can't go beyond the database installation step. If I put the correct data, I get the error below, if it is incorrect data, it displays the generic error (SQLSTATE[42000] [1044] Access denied for user 'xxxxxx'@'localhost' to database 'xxxxxx).

**Expected behavior**
No error should occur. The database should be initialized and move on, completing the installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/12484505/125420848-e7adc9cc-7925-4348-b9c0-d68a8f71a176.png)

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4.21
- Database type and version: 5.7.34 - MySQL Community Server (GPL)

**Optional info**
- OS:  [e.g. Ubuntu] Windows 10 21H1
- Browser: [e.g. chrome, safari] Google Chrome | 91.0.4472.124 (Official Build) (64-bit)

EDIT: Temp workaround: I set requirements check to false.

**Comment by VitaliKrasnik** [comment]
You have to use these credentials
- Database Name: `crater`
- Database Username: `crater`
- Database Password: `crater`

**Comment by mohitpanjwani** [comment]
https://github.com/bytefury/crater/issues/515

Please check my response here.

**Comment by BaxAndrei** [comment]
> #515
> 
> Please check my response here.

I used this method as a work around before I saw that issue, then I saw it. Thank you.
