### ISSUE TITLE
Goddady hosting issue

### ISSUE THREAD

**Issue by ptools-sonny** [bytefury/crater#515]
**Describe the bug**
Goddady installation issue.

**Expected behavior**
I filled all the infos correct but I gets error message like below
"Undefined offset: 1" with php 7.4
"Undefined array key 1" with php 8

**Screenshots**
 
![Screenshot_1](https://user-images.githubusercontent.com/51441208/126740474-c0b6c70d-280f-4a59-8f1f-a5b35b49263a.jpg)

 

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: tried 7.4 and 8.0
- Database type and version: MySQL 5.6.49-cll-lve - MySQL Community Server (GPL)
**Optional info**
- OS:  Godaddy shared
- Browser: [e.g. chrome, safari]

**Comment by mohitpanjwani** [comment]
> **Describe the bug**
> Goddady installation issue.
> 
> **Expected behavior**
> I filled all the infos correct but I gets error message like below
> "Undefined offset: 1" with php 7.4
> "Undefined array key 1" with php 8
> 
> **Screenshots**
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/51441208/126740474-c0b6c70d-280f-4a59-8f1f-a5b35b49263a.jpg)
> 
> **Please complete the following information:**
> 
> * Crater version: 4.2.0
> * PHP version: tried 7.4 and 8.0
> * Database type and version: MySQL 5.6.49-cll-lve - MySQL Community Server (GPL)
>   **Optional info**
> * OS:  Godaddy shared
> * Browser: [e.g. chrome, safari]

Hey, It looks like there's an issue is with MYSQL Version Checker. 

I think we need to skip the installation check if no version is returned from the checker in the next update.

However If you wish to skip this check manually for now, you can comment out the lines from 81 to 88 on file:`app/Space/EnvironmentManager.php`: 

<img width="763" alt="CleanShot 2021-07-23 at 13 42 48@2x" src="https://user-images.githubusercontent.com/8002555/126754747-016a6b3f-f1d9-4692-82cd-06f5c7a07d62.png">

**Comment by ptools-sonny** [comment]
Thanks for your quick reply! 
I have commented them out but still have an issue like below.
As you mentioned it must be something to do with Mysql...
Any helps would be appreciate it!

Thanks!

![image](https://user-images.githubusercontent.com/51441208/126755494-45fcbbfe-c2f2-488e-ad8a-23b4659a619d.png)

**Comment by mohitpanjwani** [comment]
Hey, You're welcome. 

Ok so this Mysql version is not supported with Crater as it looks like it doesn't support JSON Data Type. The minimum required version for Crater is MySQL: `5.7.7`

**Comment by ptools-sonny** [comment]
:( Sure thing!
Then just wait until they update their shared hosting environment!

Thanks again!
