### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by b4allb4u** [bytefury/crater#518]
Dear Team! 

I am unable to install the package on my hostinger shared hosting plan.  If any detailed documentation is highly appreciable.

I have followed the documentation steps 

Step 1: Download
Download (opens new window)the latest Crater package. **Done**

Step 2: Upload to Server
Upload the downloaded zip file to your Server and unzip it, you should see the Crater folder: **Done**

Step 3: I have created a subdomain like **crater.b4allb4u.com**. How can I Point my subdomain to the public directory inside the Crater folder?

Step 4: Complete installation wizard ( Required little bit more information )

I am getting this page
![image](https://user-images.githubusercontent.com/24243794/126894590-ef960d65-972a-4edf-a7a3-729eb8500076.png)

**Comment by b4allb4u** [comment]
can anyone help me to resolve this issue? I have uploaded the latest version of crater 4.2.0 into my subdomain crater.b4allb4u.com and run the URL https://crater.b4allb4u.com/public/on-boarding, but nothing has happened only an empty page has been displayed. I have also added SSL security to this subdomain.
![image](https://user-images.githubusercontent.com/24243794/126902514-1a8b003a-041c-4bb2-8d42-6a1e580155d6.png)

Server Details: 
Hosting Provider: hostinger.in
Plan : shared premium hosting plan
PHP version: 7.4
Database: MariaDB

**Comment by mohitpanjwani** [comment]
> can anyone help me to resolve this issue? I have uploaded the latest version of crater 4.2.0 into my subdomain crater.b4allb4u.com and run the URL https://crater.b4allb4u.com/public/on-boarding, but nothing has happened only an empty page has been displayed. I have also added SSL security to this subdomain.
> ![image](https://user-images.githubusercontent.com/24243794/126902514-1a8b003a-041c-4bb2-8d42-6a1e580155d6.png)
> 
> Server Details:
> Hosting Provider: hostinger.in
> Plan : shared premium hosting plan
> PHP version: 7.4
> Database: MariaDB

You need to point your subdomain to the public folder which exists inside the crater folder. 

Are you able to change the path of your subdomain to point a different directory? I haven’t used hostinger personally so i am not sure if it allows this. If it doesn’t allow you to do that then crater won’t work on this provider.

**Comment by b4allb4u** [comment]
Thanks a lot for your support! Finally, I have installed the application on my server!
