### ISSUE TITLE
Whitelabelling the user interface of the dashboard (logos, meta title, favicons, fonts etc.)

### ISSUE THREAD

**Issue by alfianridwan** [bytefury/crater#519]
Hey. Not sure if someone posted this before, but I looked up the documentation and couldn't find any guide or references to adjust the UI.

I'm not proficient in writing PHP so could anyone guide me to where I can adjust the dashboard logos, primary colours, meta title, favicons etc. in terms of file structure, page templates?

The reason being is I'm looking to do a custom whitelabel of the dashboard. However, I only know HTML, CSS, JS but I'm willing to learn some PHP if it's necessary to whitelabel the UI.

Thanks in advance!

**Comment by tobidwest** [comment]
It's on the roadmap: https://github.com/bytefury/crater
Most likely, this can be done via the settings page in a future release.

**Comment by alfianridwan** [comment]
@tobidwest ah yes I saw that. What I meant was what are the main files that I can edit the HTML markup and CSS stylings manually to show the changes? The HTML and CSS code I've inspected on the browser I can't find them in the `public` folder.

**Comment by mohitpanjwani** [comment]
Hey @alfianridwan, The free license doesn't allow updating the logos & other copyright information which is why its not documented. 

We're already working on a way to allow white label license holders to update all of this directly from the UI. 

You can read more about the license here: https://craterapp.com/license

**Comment by alfianridwan** [comment]
@mohitpanjwani Ah I see, thanks! What about the invoice/expenses templates though? I can't find a way to replace the fonts or adjust the structure. From what I remember, there isn't a section in the documentation that shows the structure on how to create custom invoice templates.

**Comment by mohitpanjwani** [comment]
> @mohitpanjwani Ah I see, thanks! What about the invoice/expenses templates though? I can't find a way to replace the fonts or adjust the structure. From what I remember, there isn't a section in the documentation that shows the structure on how to create custom invoice templates.

That's true. The documentation on Custom Templates can certainly be improved: https://docs.craterapp.com/guide/custom-templates.html

I'll consider working on that to make it easier for users to create/modify custom templates.

**Comment by lonesomewalker** [comment]
> Hey @alfianridwan, The free license doesn't allow updating the logos & other copyright information which is why its not documented.
> 
> We're already working on a way to allow white label license holders to update all of this directly from the UI.
> 
> You can read more about the license here: https://craterapp.com/license

Sorry to bother you, but that is not true.
As long as there is no redistribution, everybody is free to change the files.
https://github.com/bytefury/crater/blob/master/LICENSE
Otherwise it would become VERY problematic to host this on Github... :-)

**Comment by mohitpanjwani** [comment]
> > Hey @alfianridwan, The free license doesn't allow updating the logos & other copyright information which is why its not documented.
> > We're already working on a way to allow white label license holders to update all of this directly from the UI.
> > You can read more about the license here: https://craterapp.com/license
> 
> Sorry to bother you, but that is not true.
> As long as there is no redistribution, everybody is free to change the files.
> https://github.com/bytefury/crater/blob/master/LICENSE
> Otherwise it would become VERY problematic to host this on Github... :-)

You are redistributing the code as soon as you fork the repository and make the changes. In strict terms of the license, you are free to make the changes however you like as long as you keep the name & link of the original author/product visible in all the pages of the app.

**Comment by lonesomewalker** [comment]
Nope.
If i run this software on my server i do not redistribute it.

**Comment by mohitpanjwani** [comment]
> Nope.
> If i run this software on my server i do not redistribute it.

<img width="599" alt="CleanShot 2021-09-06 at 15 26 20@2x" src="https://user-images.githubusercontent.com/8002555/132198900-72932ec6-5f6c-485c-9615-3a5d3b169028.png">

**Comment by mohitpanjwani** [comment]
Redistributions & use in source and binary forms. So it doesn't matter where you use it, you have to credit the author.

**Comment by lonesomewalker** [comment]
Yes. I have seen that.
But please learn english, since redistribution is not the one you might think.
If i use something for MYSELF, there is no redistribution.

**Comment by lonesomewalker** [comment]
Also, just scanned your repo, there is a lot of references to GPL...
Better be friendly or get a lot of emails from other copyright owners.

Thx

**Comment by mohitpanjwani** [comment]
> Yes. I have seen that.
> But please learn english, since redistribution is not the one you might think.
> If i use something for MYSELF, there is no redistribution.

do you see the `USE` part? Sure it's my bad regarding the definition of redistribution.  

Btw your reply seems very rude. I'll avoid replying to you after this comment. You shouldn't be asking people to learn english. If you want people to hear you then get some manners first.

**Comment by lonesomewalker** [comment]
I have also seen that USE part.
But you can't mix that the way you want when you violate other licenses -> your own usage is not legal...
(therefore, where are YOUR manners?)

Thing is: i know that you need money for a living, because as it is written in the license... (promotional value).
But instead on still stick to this, how about really going open source?
Earning money with offering support/customization?

Seeing the open issues, the license won't bring you customers which check for quality.
But yes, you are free to ignore my opinion :-)
