### ISSUE TITLE
Currency signs missing on pdf

### ISSUE THREAD

**Issue by WrdVdb** [bytefury/crater#52]
The currency sign (€ in my case) is not shown properly on the pdf files.

![currency-sign](https://user-images.githubusercontent.com/36230484/70751713-5b43e280-1d31-11ea-9c50-6bc7d0e30e91.png)

Am I missing a library or a font?

**Comment by WrdVdb** [comment]
The font "DejaVu Sans" is fixed in the helper. This font is missing from my computer.

`
    if ($currency->swap_currency_symbol) {
        $currency_with_symbol = $format_money.'<span style="font-family: DejaVu Sans;">'.$currency->symbol.'</span>';
    } else {
        $currency_with_symbol = '<span style="font-family: DejaVu Sans;">'.$currency->symbol.'</span>'.$format_money;
    }
    return $currency_with_symbol;
}`

**Comment by mohitpanjwani** [comment]
This should no longer be an issue in V4. 

Please re-open if you still encounter this after updating.
