### ISSUE TITLE
PL language not visible in settings 

### ISSUE THREAD

**Issue by szymonwylegala** [bytefury/crater#532]
Hi,
I am currently translating into Polish lang on the crowdin.com
The Polish language file (json) is in Crater but cannot be turned on in the settings page.

I added a line in the file crater.php in supported languages and a lines in the file i18n.js (import pl from './pl.json' & pl in messages)
However, when Polish is chosen, all words are still in English. 

How to fix it?

**Comment by szymonwylegala** [comment]
I forgot to compile the assets, everything is fine now :)
`npm run dev`

**Comment by gokkstudio** [comment]
Is there a way to get it working without running `npm run dev` ? I don't have access to terminal on WHM.
I tried on localhost but something is screwed on my wampp...
