### ISSUE TITLE
What about relations?

### ISSUE THREAD

**Issue by Davidnadejdin** [bytefury/crater#55]
https://github.com/bytefury/crater/blob/80be7a492de3cb1b4b68658add99e76b607d054d/app/Http/Controllers/PaymentController.php#L26

**Comment by mohitpanjwani** [comment]
Please provide more information about what you are asking for.

**Comment by Davidnadejdin** [comment]
> Please provide more information about what you are asking for.

https://laravel.com/docs/6.x/eloquent-relationships
