### ISSUE TITLE
Recurring Expenses

### ISSUE THREAD

**Issue by matimoon** [bytefury/crater#556]
Pretty much most of the big name accounting software companies are missing "Recurring Expenses"
For example a dropbox subscription or other recurring payment that needs to be accounted for.
It would be great to have the expense intervals for the specific paymetnt be set to daily, weekly, monthly, quarterly, yearly etc..

Hope that someone is able to integrate that.
Thank you so much for the incredible work!

**Comment by sebastiancretu** [comment]
This would still mean that you will need to manually upload your receipts. Or do you have any workflow in mind ?

**Comment by matimoon** [comment]
There are no real receipts for DropBox or Netflix or such monthly subscriptions. So I think it would be helpful for an automation that creates those expenses to the interval needed.
A checkbox with an interval of daily, weekly, monthly, quarterly, yearly selection box to the expense you create.
