### ISSUE TITLE
Can't login/wrong redirect

### ISSUE THREAD

**Issue by RoelStierum** [bytefury/crater#594]
**Describe the bug**

I have port forwarded my crater installation and changed it in the docker-compose.yml file under nginx ports (from 80:80 to myport:80), the site is reachable on my public ip + my specified port. When I try to log in, it accepts my entered credentials as suspected and redirects me to the admin/dashboard page. After the redirect, I got redirected to the login page again and it shows me a message prompt with the following text: Succes! logged out succesfully (see added screenshot).

**Expected behavior**

I expect to get redirected to the crater/admin/dashboard page, so I can use the software as intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/60602417/140580074-b26d105b-4cc8-4411-b76b-d01031c2cc9a.png)

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4.x
- Database type and version: mysql

**Optional info**
- OS:  Ubuntu server (docker)
- Browser: chrome/firefox

**Comment by RoelStierum** [comment]
Fixed it by editing the .env file with the correct settings

**Comment by augmentedagent** [comment]
Can you provide any details of what you changed in the .env to get it working? Same issue here, but all I changed was the host port, and the ports aren't specified in the .env.
