### ISSUE TITLE
Getting Error Please check your internet connection or wait until servers are back online

### ISSUE THREAD

**Issue by 25Kishan** [bytefury/crater#596]
![Screenshot from 2021-11-11 13-51-18](https://user-images.githubusercontent.com/41118257/141415320-d134b7ee-df3a-470b-b46e-f194ce278a7e.png)

**Comment by mohitpanjwani** [comment]
Please provide full information asked in the issue template.

**Comment by 25Kishan** [comment]
**Describe the bug**
Please check your internet connection or wait until servers are back online facing this message after setting up my database credentials

**Expected behavior**
What I am doing wrong. Why it is showing this error.

**Screenshots**
![Screenshot from 2021-11-11 13-51-18](https://user-images.githubusercontent.com/41118257/141422073-6b8cdb2f-6982-4889-a799-d9a3dda382ac.png)


**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4.3
- Database type and version: mysql  Ver 8.0.27-0ubuntu0.20.04.1

**Optional info**
- OS:  Ubuntu 20.04.1
- Browser: chrome

**Comment by mohitpanjwani** [comment]
Which server are you using to run this? 
- Nginx
- Apache
- PHP Builtin Server (php artisan serve)

**Comment by 25Kishan** [comment]
Apache

**Comment by 25Kishan** [comment]
I am following the manual way to set up this project. So I just Clone this repository then hit the composer install command and then I create a new env file and copy the content of the env example into the env file after that I generate a key using the artisan command and then I hit the php artisan serve command.
So am I doing anything wrong?

**Comment by mohitpanjwani** [comment]
> I am following the manual way to set up this project. So I just Clone this repository then hit the composer install command and then I create a new env file and copy the content of the env example into the env file after that I generate a key using the artisan command and then I hit the php artisan serve command. So am I doing anything wrong?

You have to use something like Nginx or Apache in order for this to work. It does not work with `php artisan serve` as it doesn't use Apache. It runs a builtin PHP server which has some issues with our installation wizard.

**Comment by 25Kishan** [comment]
Ohky.
I will try with Apache.
Thanks for helping me.

**Comment by afoysal** [comment]
@mohitpanjwani . How can I install it in my local machine ?
