### ISSUE TITLE
Tax Handling per Item

### ISSUE THREAD

**Issue by philiplb** [bytefury/crater#60]
Hi,

I'm currently evaluating Crater a bit and is the following possible (as I haven't found it)?
In Germany, the tax depends on the item. Sometimes, it is reduced, sometimes it is the regular amount.
Can I set the tax per item and don't have to select it in the actual invoice? This way I don't need to remember which item has what tax rate.

**Comment by mohitpanjwani** [comment]
Hi! Yes it’s possible. 

Just select Tax per item on settings page. That way you can add tax on each item instead of invoice total.

**Comment by philiplb** [comment]
Hi,
thank you for the answer!
I see that at https://demo.craterapp.com/admin/settings/tax-types "Tax Per Item" is switched on but on managing the items at https://demo.craterapp.com/admin/items , I can't assign them a tax. How could I connect them so on creating the invoice, the tax for the added item(s) is already set?
