### ISSUE TITLE
Taxes and shipping costs

### ISSUE THREAD

**Issue by philiplb** [bytefury/crater#61]
Hi,

can Crater handle the German laws of VAT and shipping costs? Aka "what VAT has the shipping costs"? If I have items worth 100 € with 7 % VAT and items worth 200 € with 19 % VAT in my invoice, the VAT of the shipping costs would consist of 1/3 7 % and 2/3 19 %.

**Comment by mohitpanjwani** [comment]
You can add taxes per-item but the automatic calculation of shipping cost/etc is not supported by default. 

You can check the demo and see if it suits your needs.
