### ISSUE TITLE
How to install in sharedhost (max_execution_time)

### ISSUE THREAD

**Issue by amanijoseph87** [bytefury/crater#62]
Hi, thank you guys for contributing and develop this nice software. I am new here so I will go straight to my problem.

I have a problem installing this on a shared host (Godaddy) as it says `server error` while populating the database, I think its max_execution_time, I try to increase it on (Godaddy Cpanel) but I continue to have the same problem.

Is there a workaround for this, can you guys share installed DB & password to install directly on PHPMyAdmin..? Please help I need this so much.

**Comment by mohitpanjwani** [comment]
hey! We've just released a new version which should probably fix issues with installation and if something fails, it will show the errors. 

Btw if the issue is with max_execution_timeout, we cannot help regarding that right now. You'll have to increase the timeout
