### ISSUE TITLE
[enhancement] Issue template

### ISSUE THREAD

**Issue by nhedger** [bytefury/crater#63]
Hi,

I think it would be a good idea to come up with some sort of issue template for this project. Currently, I see lot of new issues being opened but most of them lack the necessary information to investigate properly.

I believe a strict minimum would be:

- Crater version.
- PHP version
- Database type and version

A simple description and steps to reproduce the issue would also go a long way.

Just my two cents :)

**Comment by mohitpanjwani** [comment]
That’s a very good suggestion. I was thinking about it but you made it easier 👍

With the increasing number of issues, its getting hard for us to manage everything.
This will surely help.

**Comment by mohitpanjwani** [comment]
Also, I need to spend some time tagging the issues properly after we are done with the latest update.

**Comment by mohitpanjwani** [comment]
Added issue templates 👍
