### ISSUE TITLE
Password minimum character is different between front-end and back-end

### ISSUE THREAD

**Issue by devlim** [bytefury/crater#65]
**Describe the bug**
Password minimum character on front-end is 5 character(register and login) while back-end(api) is 8 character.

**Expected behavior**
Front-end and back-end password minimum character should be the same.

**Code**
`/app/Http/Controllers/Auth/AccessTokensController.php`
```
public function store(Request $request)
{
    $request->validate([
        'username' => 'required|email',
        'password' => 'required|string|min:8',
    ]);
    ...
}
```

`/resources/assets/js/views/auth/Login.vue`
```
validations: {
    loginData: {
        ...
        password: {
            required,
            minLength: minLength(5)
        }
    }
}
```

`/resources/assets/js/views/wizard/UserProfile.vue`
...
password: {
    required,
    minLength: minLength(5)
},
...

**Please complete the following information:**
- Crater version: 2.0.2
- PHP version: PHP 7.3.11
- Database type and version: mysql  Ver 15.1 Distrib 10.4.8-MariaDB,

**Comment by mohitpanjwani** [comment]
Thanks! it has been fixed in https://github.com/bytefury/crater/releases/tag/2.1.0
