### ISSUE TITLE
Empty PDF rendered in Docker

### ISSUE THREAD

**Issue by BirkhoffLee** [bytefury/crater#69]
**Describe the bug**
The invoice PDF cannot be properly rendered. The Laravel error log:
```
[2019-12-14 15:56:07] production.ERROR: The resource owner or authorization server denied the request. {"exception":"[object] (League\\OAuth2\\Server\\Exception\\OAuthServerException(code: 9): The resource ow
ner or authorization server denied the request. at /app/vendor/league/oauth2-server/src/Exception/OAuthServerException.php:223)
[stacktrace]
#0 /app/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(100): League\\OAuth2\\Server\\Exception\\OAuthServerException::accessDenied('The JWT string ...', NULL, Object(InvalidA
rgumentException))
#1 /app/vendor/league/oauth2-server/src/ResourceServer.php(84): League\\OAuth2\\Server\\AuthorizationValidators\\BearerTokenValidator->validateAuthorization(Object(Zend\\Diactoros\\ServerRequest))
#2 /app/vendor/laravel/passport/src/Guards/TokenGuard.php(175): League\\OAuth2\\Server\\ResourceServer->validateAuthenticatedRequest(Object(Zend\\Diactoros\\ServerRequest))

[previous exception] [object] (InvalidArgumentException(code: 0): The JWT string must have two dots at /app/vendor/lcobucci/jwt/src/Parser.php:95)
[stacktrace]
#0 /app/vendor/lcobucci/jwt/src/Parser.php(59): Lcobucci\\JWT\\Parser->splitJwt('null')
#1 /app/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(70): Lcobucci\\JWT\\Parser->parse('null')
#2 /app/vendor/league/oauth2-server/src/ResourceServer.php(84): League\\OAuth2\\Server\\AuthorizationValidators\\BearerTokenValidator->validateAuthorization(Object(Zend\\Diactoros\\ServerRequest))
#3 /app/vendor/laravel/passport/src/Guards/TokenGuard.php(175): League\\OAuth2\\Server\\ResourceServer->validateAuthenticatedRequest(Object(Zend\\Diactoros\\ServerRequest))
#4 /app/vendor/laravel/passport/src/Guards/TokenGuard.php(127): Laravel\\Passport\\Guards\\TokenGuard->getPsrRequestViaBearerToken(Object(Illuminate\\Http\\Request))
```

**Screenshots**
Same if download the pdf.  
<img width="1099" alt="CleanShot 2019-12-15 at 01 04 16@2x" src="https://user-images.githubusercontent.com/8148095/70851945-d7c3f600-1ed6-11ea-99e1-5fc7f7153b5d.png">

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: 7.3.12
- Database type and version: MariaDB

**Optional info**
- OS: Docker, alpine
- Browser: FireFox

**Comment by Kigamba** [comment]
I am also experiencing the same issue. I used the sample `docker-compose.yaml` file to setup the application. No other changes were made.

I deployed the application on this commit `a48439785c908d8f34ed1afecc8d94b1c0014738`

<img width="1026" alt="Screen Shot 2019-12-16 at 16 52 44" src="https://user-images.githubusercontent.com/23360506/70912212-888bdb80-2024-11ea-9990-cbc735add26a.png">

**Comment by BirkhoffLee** [comment]
I think this issue only exists in the Docker setup - not sure which part of the installation was the culprit. Can anyone take a look at https://github.com/bytefury/crater/blob/master/Dockerfile#L21 ?

**Comment by ndmacioce** [comment]
Experiencing same. Using the documentation steps for docker-compose.

**Comment by sylvaindumont** [comment]
@BirkhoffLee Disabling `enable_html5_parser` [here](https://github.com/bytefury/crater/blob/master/config/dompdf.php#L240) as proposed in [this comment in laravel-dompdf](https://github.com/barryvdh/laravel-dompdf/issues/302#issuecomment-565720031) fixes the issue.

But this flag was enabled to fix currency symbols in [this commit](https://github.com/bytefury/crater/commit/ddb0ff1b8a7fa2bc05ef671d7f834a92d058a669) and disabling it breaks the currency symbols again.

**Comment by sylvaindumont** [comment]
the currency symbols bug is coming from a missing font and missing quotes around `DejaVu Sans` and is already reported in #52, replacing `DejaVu Sans` by `open-sans` fixes the currency symbols

**Comment by BirkhoffLee** [comment]
Nice find! Should we probably switch to Open Sans so we don’t need to use the experimental parser anymore?

**Comment by mohitpanjwani** [comment]
> Nice find! Should we probably switch to Open Sans so we don’t need to use the experimental parser anymore? @mohitpanjwani
> […](#)

We decided to use Dejavu-sans as it was packaged with dompdf and suggested solution.

If switching to open sans fixes the issue then  we can do that 👍

**Comment by sylvaindumont** [comment]
sorry for the misleading fix, I meant `sans-serif` not `open-sans`...
I am using the following fix (`enable_html5_parser: false` and `sans-serif` font for currency symbols) for a few days and it doesn't seem to cause other bugs
I can submit a pr with these changes to allow others to test if it doesn't cause any regressions

**Comment by karnaf** [comment]
I had the same problem (empty PDF, error 500 in preview)
In my case, my machine was missing the PHP GD extension

**Comment by proea** [comment]
@mohitpanjwani the fix is ready to merge
