### ISSUE TITLE
[Idea] Internal Taxes

### ISSUE THREAD

**Issue by DarkGhostHunter** [bytefury/crater#7]
Basically, an Invoice includes a fixed amount the client must pay. Let's say $100.000.

The normal tax is 15%, to say a random percentage. The amount received is $100.000, but from it $85.000 are gross income.

I've seen many payment gateways that take their cut over the amount paid, like for example 2%. That means:

* $15.000 in state tax.
* $2.000 in Gateway tax (costs).
* $83.000 gross income.

It would be good to have an internal tax, not set in the invoice, but internally (after tax? post tax? internal tax?) to avoid surprises when retrieving the income from the gateway service.

**Comment by rusenask** [comment]
yeah, thought the same, maybe even calculate things like VAT? It's quite easy. Currently I am using quickbooks online for invoicing and I really hate it :)  Was thinking about writing my own and now I saw this, yay! :D

**Comment by mohitpanjwani** [comment]
I like the idea but we need to think about how we can add it to the current flow and how this relates to current reports.

**Comment by edbizarro** [comment]
One way is sort by :+1: and filter by feature request tag on the issue list
