### ISSUE TITLE
Nothing after select a estimates convert to invoice 

### ISSUE THREAD

**Issue by lamtszhin0528** [bytefury/crater#70]
Nothing to show after select a [estimates] and [convert to invoice]

![螢幕截圖 2019-12-15 上午2 04 06](https://user-images.githubusercontent.com/58826592/70852672-368d6d80-1edf-11ea-8b44-efd4e0be94eb.png)

Version 2.1.0

**Comment by Mak-3000** [comment]
The same here

**Comment by janbomber** [comment]
got http 500 error
response => {message: "Server Error"}

**Comment by mkovtun-smartech** [comment]
hotfix:
![Screenshot 2019-12-18 at 17 35 15](https://user-images.githubusercontent.com/26116629/71094921-d8050f80-21bc-11ea-8ec0-bcdcbcf04c26.png)

**Comment by mohitpanjwani** [comment]
This should no longer be an issue in V4. 

Please re-open if you still encounter this after updating.
