### ISSUE TITLE
Clone invoice

### ISSUE THREAD

**Issue by lamtszhin0528** [bytefury/crater#71]
We need to make a invoice / bill to some customer monthly 
such as your mobile phone or service plan, each invoice would be same, just the date is different.

So if I can select the last invoice , and [clone] ,  I can copy all item, customer, price and/or remark. then save as a new invoice

**Comment by mohitpanjwani** [comment]
This is done! I'll push an update this week which will include a way to clone invoices.

**Comment by mohitpanjwani** [comment]
Featured added on: 
https://github.com/bytefury/crater/commit/4c33a5d88c06e0309cf407e4b5c8f0721a368a0d
