### ISSUE TITLE
View and print payment as receipt

### ISSUE THREAD

**Issue by diaznash** [bytefury/crater#72]
While using this in the demo, i'd like to be able to view a payment/receipt as pdf. It will also be helpful to be able to print a receipt/payment for a client.

**Comment by mohitpanjwani** [comment]
We've added a payment receipt pdf which will be included in the next update this week.

Here's how it looks:
![Payment Receipt](https://user-images.githubusercontent.com/8002555/71413612-ffeeea00-2678-11ea-9e67-37e502471168.png)

**Comment by diaznash** [comment]
That will be helpful also I hope the receipts can be printed. Thanks for the response. 
Am a designer if you need help with creating concepts I’ll be able to help.
