### ISSUE TITLE
Edit doesn't work

### ISSUE THREAD

**Issue by Mak-3000** [bytefury/crater#73]
**Describe the bug**
Edit any thing is not saved, if I tried to edit item, customer, invoice, payment, expenses, even settings, nothing saved, And It should save editing of course. 

![download](https://user-images.githubusercontent.com/58821703/70869839-7b73db80-1f95-11ea-88a0-04c3ff7ba404.png)

- Crater version: 2.1.0
- PHP version: 7.3.12
- Database type and version: Mariadb 10.1.43

- OS:  [Windows 10]
- Browser: [chrome, Firefox]

**Comment by Mak-3000** [comment]
All settings don't save any modifications!! Any idea to fix that issue?

**Comment by mohitpanjwani** [comment]
Hi, @Mak-3000,

We're working on fixing issues with maria-DB, windows, and docker this week. 

I'll let you know as soon as we have an update on this one.

**Comment by mohitpanjwani** [comment]
This should no longer be an issue in V4.
