### ISSUE TITLE
Error in the mailing list link

### ISSUE THREAD

**Issue by Istom1n** [bytefury/crater#74]
**Describe the bug**
In message footer, GitHub link redirect on `https://github.com/bytefury**co**/crater` 

**Expected behavior**
Page not  found

**Please complete the following information:**
- Crater version: last
- PHP version: no matter
- Database type and version: URL

**Optional info**
- OS: any
- Browser: any

**Comment by mohitpanjwani** [comment]
Thanks for letting us know. We will update the template 👌

**Comment by Istom1n** [comment]
You're welcome, sorry, I didn't find it themselves

Sincerely,
Ivan Istomin

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
