### ISSUE TITLE
Fresh Installation Database Error

### ISSUE THREAD

**Issue by mshoaibdev** [bytefury/crater#76]
Downloaded fresh zip file, when I try to install it gives a database error,

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crater.settings' doesn't exist (SQL: select * from `settings` where `option` = profile_complete limit 1)

**Screenshots**
![image](https://user-images.githubusercontent.com/17811076/70859807-b266d480-1f36-11ea-8b39-5fa8e8e52e3e.png)

- Crater version:  2.1.0
- PHP version:  7.3
- Database type and version:

**Comment by astalpaert** [comment]
Did you created a database with the name 'crater' before saving this form?

**Comment by mshoaibdev** [comment]
It clearly says table not found, so yeh I did create a database with the name of crater.

**Comment by LTroya** [comment]
@mshoaibdev  if you are using the docker from this project. `Database Host` is wrong. It's `db` instead of `127.0.0.1`

**Comment by mohitpanjwani** [comment]
@mshoaibdev Please mention your database type and version as well. The error you are getting is on database step so that's required in order for us to check.
