### ISSUE TITLE
Ability to download Invoice as PDF and "Mark as sent"

### ISSUE THREAD

**Issue by AdrianoCahete** [bytefury/crater#86]
**Is your feature request related to a problem? Please describe.**
Sometimes we just need to create the invoice and send from another service instead of email (MS Teams/Slack in my case).

**Describe the solution you'd like**
So, instead of send by email, give us the ability to download and "Mark as sent" directly.

**Comment by mohitpanjwani** [comment]
This issue was fixed in https://github.com/bytefury/crater/releases/tag/3.0.0
