### ISSUE TITLE
Bug on fresh install with docker

### ISSUE THREAD

**Issue by Romaixn** [bytefury/crater#88]
**Bug**
On a fresh install with docker, docker-compose up block on "Command Cancelled!" message.

```
Step 13/15 : RUN touch database/database.sqlite &&     cp .env.example .env &&     php artisan config:cache &&     php artisan passport:keys &&     php artisan key:generate &&     chown -R www-data:www-data . &&     chmod -R 755 . &&     chmod -R 775 storage/framework/ &&     chmod -R 775 storage/logs/ &&     chmod -R 775 bootstrap/cache/
 ---> Running in 0b6ec3606c20
Configuration cache cleared!
Configuration cached successfully!
Encryption keys generated successfully.
**************************************
*     Application In Production!     *
**************************************

Command Cancelled!
```

The script block on this message.

**Informations**
- Crater version: 2.1.0

**Comment by stanier** [comment]
Same issue here.  Have been trying for weeks to deploy this thing in a container both through docker-compose and manual.  Finally tried it in a Ubuntu 18.04 VM and this is the message I've been getting, no ports are showing up in netstat either.

**Comment by stanier** [comment]
Literally right after posting this, it moved onto another build step.

Apparently this is an intermediate container giving this output and it's part of the build process.  After letting it sit for ~5 minutes, it moves onto pulling the fs layer and nginx, then launches the final container with port 8080 exposed.

So try it again and just let it sit?  Feel like we need better documentation on this.

**Comment by BirkhoffLee** [comment]
I'm not experiencing this issue on my end, as of the latest commit.

**Comment by Romaixn** [comment]
Indeed, you just had to wait! Thanks :+1:

**Comment by Romaixn** [comment]
Indeed, you just had to wait! Thanks :+1:
