### ISSUE TITLE
Provide pre-built docker images

### ISSUE THREAD

**Issue by kolaente** [bytefury/crater#90]
**Is your feature request related to a problem? Please describe.**
As someone who just wants to use crater, I would love to have pre-built docker images of crater for me to just throw at my server and integrate them better in my existing setup. That way, I don't have to deal with building and pusing the image every time I want to update it.

This could be set up easily using [docker automated builds](https://docs.docker.com/docker-hub/builds/) or some CI System.

**Describe the solution you'd like**
Pre-built docker images to pull.

**Describe alternatives you've considered**
Self-Building the image.

**Comment by BirkhoffLee** [comment]
Given the fact that the encryption keys of the app is being generated at build stage, providing pre-built images can’t be considered safe right now until we use another approach to build the image

**Comment by kolaente** [comment]
@BirkhoffLee Wouldn't it be possible to provide the key at run time via a config option?

**Comment by mohitpanjwani** [comment]
@BirkhoffLee we actually regenerate they encryption keys of the app on onboarding wizard already, so that's not a problem.

I am looking into fixing the issues with docker and also work on creating a prebuilt docker image.

**Comment by mohitpanjwani** [comment]
Crater already provides a pretty good setup using the docker-compose: https://docs.craterapp.com/installation.html#docker-installation

Any other solutions or contributions to make it better are always welcome but for now, I'm closing this issue.

**Comment by kolaente** [comment]
The provided docker-compose still requires me to build the image and, more importantly, clone the crater repo. Because I need to adjust the `docker-compose.yml` file to run crater on my server (paths, reverse proxy configuration) I can't just upgrade with a simple `git pull` but need to make sure any adjustments I previously made to the `docker-compose.yml` in the repo are still working as expected.
If there was a pre-built, standalone docker image of crater, that would simplify things a lot for me.

**Comment by kolaente** [comment]
@mohitpanjwani Would you accept a PR?
