### ISSUE TITLE
Company logo is missing

### ISSUE THREAD

**Issue by adampatterson** [bytefury/crater#94]
**Describe the bug**
I have just installed and configured Crater 2.1.0 and when previewing my invoice the logo which I uploaded seems to be missing.

I had a look under `/public/` and can see the symlink, It is pointed at `/storage/app/public`

I can see the uploaded image in that folder but the network admin tab in chrome shows that the file is missing.

I uploading a JPG and also tried a PNG.

**Screenshots**
![image](https://user-images.githubusercontent.com/31537/71328681-86b89100-24d8-11ea-9552-d81f23fd5f20.png)

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: 7.2.1
- Database type and version: MySQL - 5.7.28

**Optional info**
- OS:  Ubuntu 16
- Browser: Chrome

**Comment by eboye** [comment]
If it's over https on localhost, try without SSL as it's probably self signed.

**Comment by adampatterson** [comment]
That worked, I had my .env set to HTTPS while using Cloudflare.
