### ISSUE TITLE
Many icons are not loaded in sidemenu

### ISSUE THREAD

**Issue by FrankyJust** [bytefury/crater#98]
I want to use different icons in side-menu, but I've noticed that many icons of the Font-Awesome library seem not to be loaded. E.g. icon bell is loaded, but icon user-graduate isn't loaded. What could be the issue?

**Comment by mohitpanjwani** [comment]
You have to import the specific icon and add it to the library in order to use it: 

Here's where crater does it: `resources/assets/plugins/vue-font-awesome/index.js`

For more info, take a look at how `vue-fontawesome` works
