### ISSUE TITLE
Activate translation?

### ISSUE THREAD

**Issue by baxterbln** [bytefury/crater#99]
Hello,
i´m working on the translation to german. How can i activate this file?

I have add a de.json file in the plugins folder and add the language into the following files:
- i18n.js
- OnboardingController.php
- CompanyController.php

After this i change the language to German.

But into the interface has the new language no effect and i see only the placeholders.

Here the complete german translation as text file (json not allowed to attach)
[de.txt](https://github.com/bytefury/crater/files/3995654/de.txt)

**Comment by mohitpanjwani** [comment]
Hey, Thanks for showing interest. 

You can get some idea by checking this PR changes on how to add translation: 
https://github.com/bytefury/crater/pull/87

I am working on a translation guide but until then you can check this out and see if you can figure it out. If you have any other questions after that, just comment here and I'll get back to you

**Comment by baxterbln** [comment]
I read it, and make changes on the same files, but no effect.

**Comment by mohitpanjwani** [comment]
Did you run `npm run dev` or `npm run production` after you made the changes to the language files? 

Make sure to do that, otherwise, your changes won't be reflected on the frontend as you have to compile after making changes to any js or scss files.

**Comment by baxterbln** [comment]
Yep, no works;-)

And here the last complete version of the german language file.
[de.txt](https://github.com/bytefury/crater/files/4000205/de.txt)
